### ISSUE TITLE
Minecolonies 1.18.2 Forge Incompatibility

### ISSUE THREAD

**Issue by PresBKennedy** [Yesssssman/epicfightmod#1028]
Epic Fight crashes the game when using the build tool to preview any structure added by Minecolonies that has an armor stand in it. I think Epic Fight is trying to apply animation or get information from the armor stand, and its preview rather than an interactable entity and it crashes. 

Any of the Medieval townhalls level 5 will crash the game when previewing them while having epic fight installed. Here is the crash report from my modpack below. I created a new mod pack only installing epic fight and Minecolonies and tried to preview the structures in game and got the same result.

[crash-2022-05-23_08.58.34-client.txt](https://github.com/Yesssssman/epicfightmod/files/8755740/crash-2022-05-23_08.58.34-client.txt)

> Time: 5/23/22, 8:58 AM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.GameRules.m_46207_(net.minecraft.world.level.GameRules$Key)" because the return value of "net.minecraft.world.level.Level.m_46469_()" is null
	at yesman.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:337) ~[EpicFight-18.1.18-beta.jar%2395!/:18.1.18] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_764_Events_renderLivingEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:52) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:30) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:129) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.client.BlueprintRenderer.draw(BlueprintRenderer.java:260) ~[structurize-1.18.2-1.0.399-RELEASE.jar%23158!/:1.18.2-1.0.399-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.BlueprintHandler.draw(BlueprintHandler.java:75) ~[structurize-1.18.2-1.0.399-RELEASE.jar%23158!/:1.18.2-1.0.399-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.StructureClientHandler.renderStructure(StructureClientHandler.java:20) ~[structurize-1.18.2-1.0.399-RELEASE.jar%23158!/:1.18.2-1.0.399-RELEASE] {re:classloading}
	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:62) ~[structurize-1.18.2-1.0.399-RELEASE.jar%23158!/:1.18.2-1.0.399-RELEASE] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_867_ClientEventSubscriber_renderWorldLastEvent_RenderLevelLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:228) ~[forge-1.18.2-40.1.20-universal.jar%23193!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1061) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:833) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23189!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.20.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by PresBKennedy** [comment]
I'm using forge, version 40.1.20 and Minecraft 1.18.2. Playing on Windows.

**Comment by Yesssssman** [comment]
This is already fixed in recent MInecolnies.
