### ISSUE TITLE
ItShallNotTick crash with Epic Fight

### ISSUE THREAD

**Issue by magsum** [Yesssssman/epicfightmod#1061]
net.minecraft.world.entity.monster.Witch.m_6504_(Witch.java:214) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,re:classloading,pl:mixin:APP:hexplat.mixins.json:MixinWitch,pl:mixin:A}
	at yesman.epicfight.api.animation.types.RangedAttackAnimation.doAttack(RangedAttackAnimation.java:16) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:156) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.update(ServerAnimator.java:70) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.serverTick(LivingEntityPatch.java:112) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:122) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:mixin,re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[EpicFight-18.1.20-beta.jar%23157!/:18.1.20] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_283_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) ~[forge-1.18.2-40.1.51-universal.jar%23313!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2214) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:AdditionalAdditions.mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:bigbrain.mixins.json:LivingEntityMixin,pl:mixin:APP:META-INF/blockrunner.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:debugify-common.mixins.json:basic.server.mc30391.LivingEntityMixin,pl:mixin:APP:debugify-common.mixins.json:basic.server.mc84873.LivingEntityMixin,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc228976.LivingEntityMixin,pl:mixin:APP:debugify-common.mixins.json:basic.client.mc93384.LivingEntityMixin,pl:mixin:APP:debugify-common.mixins.json:gameplay.client.mc12829.LivingEntityMixin,pl:mixin:APP:difficultraids.mixin.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:APP:hardcorerevival.mixins.json:LivingEntityAccessor,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:iguanatweaksreborn.mixins.json:LivingEntityMixin,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:origins_classes.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:pehkui.mixins.json:LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.LivingEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat117plus.LivingEntityMixin,pl:mixin:APP:pollen-common.mixins.json:LivingEntityMixin,pl:mixin:APP:pollen.mixins.json:LivingEntityMixin,pl:mixin:APP:quark.mixins.json:LivingEntityAccessor,pl:mixin:APP:secondchanceforge.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:spirit.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:dual.LivingEntityMixin,pl:mixin:APP:META-INF/tinyskeletons.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:unionlib.mixins.json:LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinLivingEntity,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:pehkui.mixins.json:compat115plus.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:AdditionalAdditions.mixins.json:MobMixin,pl:mixin:APP:domesticationinnovation.mixins.json:MobMixin,pl:mixin:APP:hexplat.mixins.json:MixinMob,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:pehkui.mixins.json:MobEntityMixin,pl:mixin:APP:pehkui.mixins.json:compat116plus.MobEntityMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevellMixin,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevelSnowMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at dev.wuffs.itshallnottick.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:59) ~[ItShallNotTick-1.0.20-build.21.jar%23196!/:1.0.20-build.21] {re:mixin,re:classloading}
	at dev.wuffs.itshallnottick.TickOptimizer.entityTicking(TickOptimizer.java:22) ~[ItShallNotTick-1.0.20-build.21.jar%23196!/:1.0.20-build.21] {re:mixin,re:classloading}
	at net.minecraft.world.level.Level.m_46653_(Level.java:1570) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevellMixin,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevelSnowMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevellMixin,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevelSnowMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:witch (net.minecraft.world.entity.monster.Witch)
	Entity ID: 197
	Entity Name: Witch
	Entity's Exact location: 3951.30, 64.00, -1484.56
	Entity's Block location: World: (3951,64,-1485), Section: (at 15,0,3 in 246,4,-93; chunk contains blocks 3936,-64,-1488 to 3951,319,-1473), Region: (7,-3; contains chunks 224,-96 to 255,-65, blocks 3584,-64,-1536 to 4095,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AABB:[3950.998969651341d,64.0d,-1484.8578443701515d,3951.598969675183d,65.95000004768372d,-1484.2578443463096d],AbsorptionAmount:0.0f,ActiveEffects:[{Ambient:0b,Amplifier:0b,CurativeItems:[{Count:1b,id:"minecraft:milk_bucket"}],Duration:102,Id:10b,ShowIcon:1b,ShowParticles:1b,"forge:id":"minecraft:regeneration"}],Air:300s,ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],ArmorItems:[{},{},{},{}],Attributes:[{Base:0.0d,Name:"epicfight:armor_negation"},{Base:0.0d,Modifiers:[{Amount:0.0014000000953674316d,Name:"im_modifier",Operation:0,UUID:[I;2088655917,514868042,-2054210888,525501228]}],Name:"minecraft:generic.knockback_resistance"},{Base:1.0d,Name:"epicfight:max_strikes"},{Base:16.0d,Modifiers:[{Amount:-0.0342548328574776d,Name:"Random spawn bonus",Operation:1,UUID:[I;-1472073633,-1707915210,-1683502470,806016878]}],Name:"minecraft:generic.follow_range"},{Base:0.08d,Name:"forge:entity_gravity"},{Base:1.0d,Name:"forge:swim_speed"},{Base:2.0d,Modifiers:[{Amount:0.011200000762939453d,Name:"im_modifier",Operation:0,UUID:[I;2088655917,514868042,-2054210888,525501228]}],Name:"minecraft:generic.attack_damage"},{Base:52.0d,Name:"epicfight:weight"},{Base:0.0d,Name:"forge:step_height_addition"},{Base:0.5d,Name:"epicfight:impact"},{Base:26.0d,Modifiers:[{Amount:0.0d,Name:"RAID_PLAYER_COUNT_HEALTH_BOOST",Operation:0,UUID:[I;-2106411548,-1516222846,-1380757415,-1897914404]},{Amount:0.5d,Name:"im_modifier",Operation:0,UUID:[I;2088655917,514868042,-2054210888,525501228]}],Name:"minecraft:generic.max_health"},{Base:0.25d,Modifiers:[{Amount:5.600000381469727E-4d,Name:"im_modifier",Operation:0,UUID:[I;2088655917,514868042,-2054210888,525501228]}],Name:"minecraft:generic.movement_speed"}],Brain:{memories:{}},BucklerDashing:0b,BucklerUseTimer:15,CanJoinRaid:1b,CanPickUpLoot:0b,CanUpdate:1b,ChargeCooldown:240,CitadelData:{},DeathTime:0s,FallDistance:0.0f,FallFlying:0b,Fire:-1s,ForgeCaps:{"agricraft:eat_crop_goal":{},"apoli:powers":{Powers:[]},"champions:champion":{affixes:[],tier:0},"consecration:undying":{smite:0},"malum:living_data":{exposedSoul:0.0f,soulHarvestProgress:0.0f,soulless:0b,spawnerSpawned:0b},"ortus:entity_data":{},"pollen:synced_data":{}},ForgeData:{},HandDropChances:[0.085f,0.085f],HandItems:[{},{}],Health:26.5f,HurtByTimestamp:0,HurtTime:0s,IMFlags:{CanBreakBlocks:2,CanFly:2,GearEnchanted:1b,IsRideSummoned:0b,IsThrown:0b,MagicRes:0.0016f,ModifiedArmor:1b,ModifiedAttributes:1b,ModifiedHeld:1b,ProjBoost:1.008f},Invulnerable:0b,LeftHanded:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:0b,PatrolLeader:0b,Patrolling:0b,PersistenceRequired:0b,PortalCooldown:0,Pos:[3951.298969663262d,64.0d,-1484.5578443582306d],RaidId:2,Rotation:[339.68036f,0.0f],Tags:["in.checked"],UUID:[I;-1658103873,-441300732,-1435918505,1887276588],Wave:3}
Stacktrace:
	at dev.wuffs.itshallnottick.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:59) ~[ItShallNotTick-1.0.20-build.21.jar%23196!/:1.0.20-build.21] {re:mixin,re:classloading}
	at dev.wuffs.itshallnottick.TickOptimizer.entityTicking(TickOptimizer.java:22) ~[ItShallNotTick-1.0.20-build.21.jar%23196!/:1.0.20-build.21] {re:mixin,re:classloading}
	at net.minecraft.world.level.Level.m_46653_(Level.java:1570) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:APP:itshallnottick.mixins.json:EntityTickMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevellMixin,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevelSnowMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alternate_current.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevellMixin,pl:mixin:APP:immersive_weathering.mixins.json:ServerLevelSnowMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23308!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

________________

Weirdly enough, I was not around any witches, yet this happened.

**Comment by Yesssssman** [comment]
Is there any mod called hexplat? It was crashed my mixin code in hexplat mod or something

**Comment by Yesssssman** [comment]
well I'm sorry to say this but it can't be fixed in my side cause the mixin source code of hexplat prevents the game logic working properly.
