### ISSUE TITLE
New crash during chunk loading (Crash Report)

### ISSUE THREAD

**Issue by raponoves** [Yesssssman/epicfightmod#11]
---- Minecraft Crash Report ----
// You're mean.

Time: 2/22/21 5:34 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.entity.Entity.func_70068_e(Entity.java:1182) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:A}
	at maninhouse.epicfight.client.renderer.entity.ArmatureRenderer.shouldRenderNameTag(ArmatureRenderer.java:148) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:47) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:264) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:387) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_420_Events_renderLivingEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:1072) ~[?:?] {re:classloading}
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1345) ~[?:?] {re:classloading}
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1331) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:310) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$11204/860997097.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1798) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/297031141.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.entity.Entity.func_70068_e(Entity.java:1182) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:endergetic.mixins.json:EntityMixin,pl:mixin:A}
	at maninhouse.epicfight.client.renderer.entity.ArmatureRenderer.shouldRenderNameTag(ArmatureRenderer.java:148) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:47) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:264) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:387) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_420_Events_renderLivingEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:1072) ~[?:?] {re:classloading}
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1345) ~[?:?] {re:classloading}
	at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1331) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_225623_a_(LivingRenderer.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:47) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.renderer.entity.MobRenderer.func_225623_a_(MobRenderer.java:20) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
-- Entity being rendered --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.ZombieEntity)
	Entity ID: 600
	Entity Name: Zombie
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.ZombieRenderer@7a1c5bbe
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 0.8199997
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:310) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$11204/860997097.run(Unknown Source) ~[?:?] {}

-- Block Entity Details --
Details:
	Name: minecraft:mob_spawner // net.minecraft.tileentity.MobSpawnerTileEntity
	Block: Block{minecraft:spawner}
	Block location: World: (315,39,569), Chunk: (at 11,2,9 in 19,35; contains blocks 304,0,560 to 319,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Block: Block{minecraft:spawner}
	Block location: World: (315,39,569), Chunk: (at 11,2,9 in 19,35; contains blocks 304,0,560 to 319,255,575), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1798) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:dungeons_gear.mixins.json:GameRendererMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['0tlus'/163, l='ClientLevel', x=276.35, y=74.90, z=567.91]]
	Chunk stats: Client Chunk Cache: 2209, 581
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,63,231), Chunk: (at 0,3,7 in 5,14; contains blocks 80,0,224 to 95,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1101 game time, 1101 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$475/297031141.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 557192536 bytes (531 MB) / 2903506944 bytes (2769 MB) up to 4831838208 bytes (4608 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5184m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		EndRemastered-R352.jar                            |End Remastered 3.5.2          |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		TRansliterationLib-1.0.2.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.2               |DONE      |NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.3.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		notenoughanimations-1.1.0.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.1.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.4.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.4.0              |DONE      |NOSIGNATURE
		PassableFoliage-1.16.4-2.2.0.jar                  |Passable Foliage              |passablefoliage               |2.2.0               |DONE      |NOSIGNATURE
		EpicFightMod-1.16.4-2.0.1.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
		XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.12.0              |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
		citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
		alexsmobs-1.5.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.1               |DONE      |NOSIGNATURE
		earthmobsmod-1.16.4-0.4.2.jar                     |Earth Mobs Mod                |earthmobsmod                  |1.16.4-0.4.2        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guardvillagers-1.16.4-1.1.10.jar                  |Guard Villagers               |guardvillagers                |1.1.10              |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.13.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.13            |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.126.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.126           |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.4.0.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.4.0        |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		charmonium-forge-1.16.4-2.2.2.jar                 |Charmonium                    |charmonium                    |2.2.1               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		SubWild-1.16.5-1.1.2.jar                          |Subterranean Wilderness       |subwild                       |1.1.2               |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
	Crash Report UUID: adfd9923-be9f-4108-8a2c-d4a2e9b750fb
	Launched Version: forge-35.1.28
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.14758 Compatibility Profile Context 21.2.2 27.20.14535.1000, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, file/NewDefault+v1.38[MC1.16.2-1.16.5].zip, file/Animated-Mobs-1.16.3.zip
	Current Language: English (US)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.2.2 27.20.14535.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by koderian** [comment]
Yo, same issue here!!! Running on a server, but anytime a player gets near some entities it crashes and the screen turns f*cking weird. 
![parsecd_X5av0lduZV](https://user-images.githubusercontent.com/44537031/108779401-e8c0bc00-750a-11eb-8b9d-f26a68bf0e6c.jpg)

logs: https://paste.ubuntu.com/p/F4yVnrQmkt/
logs: https://paste.ubuntu.com/p/dhYkKpmZJv/

**Comment by koderian** [comment]
more logs: https://paste.ubuntu.com/p/hSpWHytYY4/

**Comment by koderian** [comment]
@Yesssssman This is a urgent issue. Can't play more then 5 minutes without it going bezerk

**Comment by raponoves** [comment]
@Yesssssman Yeah, mod version is completely unplayable.

**Comment by Yesssssman** [comment]
I'm not sure does the drowned really occurs this issue, but I tested modified version for 10 mins without crashes, I uploaded 2.0.2 version in curseforge.
