### ISSUE TITLE
World loading stuck at 0%

### ISSUE THREAD

**Issue by Ohgodthisis** [Yesssssman/epicfightmod#12]
so i recently got a mac for playing minecraft with alot of mods but to my suprise it didn't work because it kept getting stuck at 0%
and when i opened the console to see what happens when it got to the loading part it kept repeating this line:
[12:40:04] [Client thread/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_281]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.network.play.server.SPacketEntityHeadLook.func_149381_a(SourceFile:42) ~[jx.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147267_a(NetHandlerPlayClient.java:644) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketEntityHeadLook.func_148833_a(SourceFile:38) ~[jx.class:?]
	at net.minecraft.network.play.server.SPacketEntityHeadLook.func_148833_a(SourceFile:11) ~[jx.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_281]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

**Comment by Yesssssman** [comment]
I can't see any problems with my code in crash report you attached. Maybe there're uncompatible mods exist together.
