### ISSUE TITLE
[Bug|Crash]: Game crashes upon hitting anything.

### ISSUE THREAD

**Issue by Sofjiet** [Yesssssman/epicfightmod#1201]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.16.5

### What happened?

Game crashes upon hitting any entity in the game, the crash log:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/22/22 2:14 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;
  at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[epicfight:16.6.2] {re:mixin,re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[epicfight:16.6.2] {re:mixin,re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[epicfight:16.6.2] {re:classloading}
  at net.minecraftforge.eventbus.ASMEventHandler_20_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
  at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[forge:?] {re:classloading}
  at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
  at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
  at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[epicfight:16.6.2] {re:mixin,re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[epicfight:16.6.2] {re:mixin,re:classloading}
  at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[epicfight:16.6.2] {re:classloading}
  at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[epicfight:16.6.2] {re:classloading}
  at net.minecraftforge.eventbus.ASMEventHandler_20_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
  at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
  at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[forge:?] {re:classloading}
  at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
  at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Player being ticked --
Details:
  Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
  Entity ID: 189
  Entity Name: Sofjet
  Entity's Exact location: 61.97, 64.00, -32.19
  Entity's Block location: World: (61,64,-33), Chunk: (at 13,4,15 in 3,-3; contains blocks 48,0,-48 to 63,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
  at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312] {}

-- System Details --
Details:
  Minecraft Version: 1.16.5
  Minecraft Version ID: 1.16.5
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_312, Temurin
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
  Memory: 965309168 bytes (920 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
  CPUs: 8
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms1024M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
  ModLauncher launch target: fmlclient
  ModLauncher naming: srg
  ModLauncher services: 
    /mixin-0.8.4.jar mixin PLUGINSERVICE 
    /eventbus-4.0.0.jar eventbus PLUGINSERVICE 
    /forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
    /forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
    /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
    /forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
    /forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
    /mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
    /forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
  FML: 36.2
  Forge: net.minecraftforge:36.2.34
  FML Language Providers: 
    javafml@36.2
    minecraft@1
  Mod List: 
    forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
    forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
    EpicFight-16.6.2.jar                              |Epic Fight                    |epicfight                     |16.6.2              |DONE      |Manifest: NOSIGNATURE
  Crash Report UUID: 257f7bb0-6757-4de9-9e07-21d3ed64a212
  Player Count: 1 / 8; [ServerPlayerEntity['Sofjet'/189, l='ServerLevel[New World]', x=61.97, y=64.00, z=-32.19]]
  Data Packs: vanilla, mod:forge, mod:epicfight
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'forge'
[14:14:46] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Mateusz\AppData\Roaming\Crystal-Launcher\instances\u.test\.minecraft\crash-reports\crash-2022-09-22_14.14.46-server.txt

**Comment by MetalKnight56** [comment]
Closing this issue as the user violated the support policy by not using the recommended forge version
