### ISSUE TITLE
1.18.2 Fails to load it correctly.

### ISSUE THREAD

**Issue by IntrovertedGamer** [Yesssssman/epicfightmod#1215]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/15/22, 8:50 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.60-universal.jar%23131!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:170) ~[forge-1.18.2-40.1.60-universal.jar%23131!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:555) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:397) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:549) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:879) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.forge.Mixin_FixInternalByteBufAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23126!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.60.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
-- MOD epicfight --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderLevelStageEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!/:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.60.jar%23127!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: EpicFight-18.3.7.jar
	Failure message: Epic Fight (epicfight) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/client/event/RenderLevelStageEvent
	Mod Version: 18.3.7
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.RenderLevelStageEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[javafmllanguage-1.18.2-40.1.60.jar%23128!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.60.jar%23127!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1742208000 bytes (1661 MiB) / 2998927360 bytes (2860 MiB) up to 4697620480 bytes (4480 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8984
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 32589.43
	Virtual memory used (MB): 23564.97
	Swap memory total (MB): 24576.00
	Swap memory used (MB): 3928.40
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4480m -Xms256m
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 essential-loader TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
		kotlinforforge@3.6.0
	Mod List: 
		mowziesmobs-1.5.29.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.29              |COMMON_SET|Manifest: NOSIGNATURE
		blue_skies-1.18.2-1.3.12.jar                      |Blue Skies                    |blue_skies                    |1.3.12              |COMMON_SET|Manifest: NOSIGNATURE
		ConfigMenusForge-v3.2.0-1.18.2-Forge.jar          |Config Menus for Forge        |configmenusforge              |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		villagerdrops-forge-1.18.2-v1.0.1.jar             |Villagers Drop Emeralds on Dea|villagerdrops                 |1.18.2              |COMMON_SET|Manifest: NOSIGNATURE
		Enlightened End BB V1.5.jar                       |Enlightened End               |nourished_end                 |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |COMMON_SET|Manifest: NOSIGNATURE
		allay-forge-1.18.x-4.0.0.jar                      |YDM's Allay Mod               |allay                         |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		weirdmobs-1-18-2.jar                              |YDM's WeirdMobs mod           |weirdmobs                     |3.0                 |COMMON_SET|Manifest: NOSIGNATURE
		the-conjurer-1.18.2-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		LibraryFerret-Forge-1.18.2-2.0.0.jar              |Library ferret                |libraryferret                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar   |Entity Collision FPS Fix      |entitycollisionfpsfix         |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		kingvillager-1.10.jar                             |The King of the Village       |kingvillager                  |1.10                |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |COMMON_SET|Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |COMMON_SET|Manifest: NOSIGNATURE
		Neat 1.8-30.jar                                   |Neat                          |neat                          |1.8-30              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		EpicFight-18.3.7.jar                              |Epic Fight                    |epicfight                     |18.3.7              |ERROR     |Manifest: NOSIGNATURE
		paperdoll-forge-1.1.0-mc1.18.jar                  |PaperDoll                     |paperdoll                     |1.1.0-mc1.18        |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+15.jar                  |Clumps                        |clumps                        |8.0.0+15            |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.2-5.8.5-forge.jar                 |Journeymap                    |journeymap                    |5.8.5               |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |COMMON_SET|Manifest: NOSIGNATURE
		village-employment-1.18.2-1.5.1.jar               |Village Employment            |village_employment            |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		StepUp-1.18.0-0.1.1.jar                           |StepUp                        |stepup                        |1.18.0-0.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		balm-3.1.0+0.jar                                  |Balm                          |balm                          |3.1.0+0             |COMMON_SET|Manifest: NOSIGNATURE
		blueprint-1.18.2-5.4.3.jar                        |Blueprint                     |blueprint                     |5.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		easy_piglins-1.18.2-1.0.0.jar                     |Easy Piglins                  |easy_piglins                  |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		structure_gel-1.18.2-2.4.6.jar                    |Structure Gel API             |structure_gel                 |2.4.6               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.18.2-2.1.50d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.50d-1.18.2      |COMMON_SET|Manifest: NOSIGNATURE
		illagersweararmor-1.1.5.jar                       |Illagers Wear Armor           |zillagersweararmor            |1.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		smoothchunk-1.18.2-1.9.jar                        |Smoothchunk mod               |smoothchunk                   |1.18.2-1.9          |COMMON_SET|Manifest: NOSIGNATURE
		lucky-block-forge-1.18.2-13.1.jar                 |Lucky Block                   |lucky                         |1.18.2-13.1         |COMMON_SET|Manifest: NOSIGNATURE
		repurposed_structures_forge-5.1.14+1.18.2.jar     |Repurposed Structures         |repurposed_structures         |5.1.14+1.18.2       |COMMON_SET|Manifest: NOSIGNATURE
		morevillagers-forge-1.18.2-3.3.2.jar              |More Villagers                |morevillagers                 |3.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |COMMON_SET|Manifest: NOSIGNATURE
		BetterCrates-1.18.2-1.0.0.jar                     |Better Crates                 |bettercrates                  |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.18-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.18              |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		extragolems-18.2.3.jar                            |Extra Golems                  |golems                        |18.2.3              |COMMON_SET|Manifest: NOSIGNATURE
		easy_villagers-1.18.2-1.0.11.jar                  |Easy Villagers                |easy_villagers                |1.18.2-1.0.11       |COMMON_SET|Manifest: NOSIGNATURE
		Cataclysm-0.19.jar                                |Cataclysm Mod                 |cataclysm                     |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.55-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.55-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.2-4.37.jar                        |Collective                    |collective                    |4.37                |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |COMMON_SET|Manifest: NOSIGNATURE
		villagertools-1.18-1.0.2.jar                      |villagertools                 |villagertools                 |1.18-1.0.2          |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		Villagers_Sell_Animals_1.0.1_Forge_1.18.2.jar     |Villagers Sell Animals        |villagersellanimals           |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18.2-1.8.1.jar          |Better Third Person           |betterthirdperson             |1.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		witherstormmod-1.18.2-2.1.jar                     |Cracker's Wither Storm Mod    |witherstormmod                |2.1                 |COMMON_SET|Manifest: NOSIGNATURE
		Regrowth-1.18.2-1.40.0.30c.jar                    |Regrowth                      |regrowth                      |1.18.2-1.40.0.30c   |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.18.2-1.0.424-ALPHA.jar              |Structurize                   |structurize                   |1.18.2-1.0.424-ALPHA|COMMON_SET|Manifest: NOSIGNATURE
		multi-piston-1.18.2-1.2.15-ALPHA.jar              |Multi-Piston                  |multipiston                   |1.18.2-1.2.15-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		infinitemusic-1.5.1-1.18.1-forge.jar              |Infinite Music                |infinitemusic                 |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		minecolonies-1.18.2-1.0.966-RELEASE.jar           |MineColonies                  |minecolonies                  |1.18.2-1.0.966-RELEA|COMMON_SET|Manifest: NOSIGNATURE
		structures_compass-1.18.2-1.4.1.jar               |Structures Compass            |structures_compass            |1.18.2-1.4.1        |COMMON_SET|Manifest: NOSIGNATURE
		sapience-1.18.2-1.0.0.jar                         |Sapience                      |sapience                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-4.9.83-forge.jar                     |Architectury                  |architectury                  |4.9.83              |COMMON_SET|Manifest: NOSIGNATURE
		helpwanted_forge_1_18_2-1.0.6.jar                 |Example Mod                   |helpwanted                    |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		identity-2.3.0-1.18.2-forge.jar                   |Identity                      |identity                      |2.3.0-1.18.2        |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.18.2-3.5.2.jar                      |FallingTree                   |fallingtree                   |3.5.2               |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		illageandspillage-1.18.2-1.1.2.jar                |Illage and Spillage           |illageandspillage             |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.39.jar                    |GeckoLib                      |geckolib3                     |3.0.39              |COMMON_SET|Manifest: NOSIGNATURE
		better_respawn-1.18.2-1.0.0.jar                   |Better Respawn                |better_respawn                |1.18.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		Essential (forge_1.18.2).jar                      |Essential                     |essential                     |10597+deploy-staging|COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: c1139187-ae46-4a62-a97f-915d806f928a
	FML: 40.1
	Forge: net.minecraftforge:40.1.60

**Comment by Yesssssman** [comment]
No way to support this since it's not the latest forge version.
