### ISSUE TITLE
[Bug|Crash]: Failed to load description for particle beautify:glowessence_particles on Forge 41.0.80

### ISSUE THREAD

**Issue by MarbleGateKeeper** [Yesssssman/epicfightmod#1238]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Crash on start.
Simply install forge = 41.0.80 and latest version of this mod, and then game crashes on start.

```
java.lang.IllegalStateException: Failed to load description for particle beautify:glowessence_particles
	at net.minecraft.client.particle.ParticleEngine.m_107316_(ParticleEngine.java:278) ~[client-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.ParticleEngineAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleEngine.m_172284_(ParticleEngine.java:192) ~[client-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.ParticleEngineAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.io.FileNotFoundException: beautify:particles/glowessence_particles.json
	at net.minecraft.server.packs.resources.MultiPackResourceManager.m_142591_(MultiPackResourceManager.java:50) ~[client-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MultiPackResourceManagerMixin,pl:mixin:A}
	at net.minecraft.client.particle.ParticleEngine.m_107316_(ParticleEngine.java:228) ~[client-1.18.2-20220404.173914-srg.jar%23127!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:accessor.ParticleEngineAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	... 8 more
```

**Comment by MarbleGateKeeper** [comment]
not an issue of this mod itself.
