### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Commander99** [Yesssssman/epicfightmod#1256]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I use the latest 1.16.5 forge version and the latest epic fight version 16.6.4. Everytimes i attack a mob my game is crashing (exit code -1) There are no other mods installed. 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 26.12.22 18:22
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;
	at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.particle.HitParticleType$$Lambda$3299/1015367506.apply(Unknown Source) ~[?:?] {}
	at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[?:16.6.4] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[?:16.6.4] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[?:16.6.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_21_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2565/480733305.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5663/576811632.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.particle.HitParticleType$$Lambda$3299/1015367506.apply(Unknown Source) ~[?:?] {}
	at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[?:16.6.4] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[?:16.6.4] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[?:16.6.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_21_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2565/480733305.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 386
	Entity Name: LuckyDuke6593
	Entity's Exact location: -232.72, 67.00, 171.03
	Entity's Block location: World: (-233,67,171), Chunk: (at 7,4,11 in -15,10; contains blocks -240,0,160 to -225,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5663/576811632.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 9859107608 bytes (9402 MB) / 10871635968 bytes (10368 MB) up to 17179869184 bytes (16384 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.9.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.9
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.9-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.9-universal.jar                 |Forge                         |forge                         |36.2.9              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		EpicFight-16.6.4.jar                              |Epic Fight                    |epicfight                     |16.6.4              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5efc0a42-30c8-45fe-bb5d-18650bc2ee77
	Player Count: 1 / 8; [ServerPlayerEntity['LuckyDuke6593'/386, l='ServerLevel[Neue Welt]', x=-232.72, y=67.00, z=171.03]]
	Data Packs: vanilla, mod:forge, mod:epicfight
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by MetalKnight56** [comment]
Closed issue as user broke the support policy
