### ISSUE TITLE
[Bug|Crash]: 1.16.5 Entity Ticking Error (i will add FML report if needed)

### ISSUE THREAD

**Issue by HoluBeks** [Yesssssman/epicfightmod#1270]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Hello Everyone and Devs of EF mod.
I really dont know what happened, i used this mod like 1 y ago and it works perfectly!!! i was really excited bcs its very good work and Top Animation mod for Minecraft but now when i Creating new Mod/plugin Mohist Server... I got Crashes... :(
!!! I TESTING MODS IN SINGLEPLAYER, not in server for those who will telling me "its bcs the server!!!"
Every time when i hit the  any entity it crash my game and give me the error report be like Entity Ticking player/particle
Please someone help or fix? I really wanna use this mod for my Server since Season 1 will End.... bcs S1 of my server will be post apocalyptic world :D

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/19/23 9:14 PM
Description: Ticking player

java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;
	at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.particle.HitParticleType$$Lambda$3941/2023501911.apply(Unknown Source) ~[?:?] {}
	at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[?:16.6.0] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[?:16.6.0] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[?:16.6.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_33_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3312/183958540.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:library_of_exile-mixins.json:ServerPlayerMixin,pl:mixin:APP:mmorpg-mixins.json:ServerPlayerEntityAccessor,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6559/1187497363.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at yesman.epicfight.particle.HitParticleType.lambda$static$1(HitParticleType.java:22) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.particle.HitParticleType$$Lambda$3941/2023501911.apply(Unknown Source) ~[?:?] {}
	at yesman.epicfight.particle.HitParticleType.spawnParticleWithArgument(HitParticleType.java:58) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.spawnHitParticle(AttackAnimation.java:322) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:231) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[?:16.6.0] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:162) ~[?:16.6.0] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:92) ~[?:16.6.0] {re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[?:16.6.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_33_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3312/183958540.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:library_of_exile-mixins.json:LivingEntityMixin,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:mmorpg-mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 185
	Entity Name: HoluBeks
	Entity's Exact location: -51.37, 66.00, -224.11
	Entity's Block location: World: (-52,66,-225), Chunk: (at 12,4,15 in -4,-15; contains blocks -64,0,-240 to -49,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:library_of_exile-mixins.json:ServerPlayerMixin,pl:mixin:APP:mmorpg-mixins.json:ServerPlayerEntityAccessor,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6559/1187497363.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2022601168 bytes (1928 MB) / 2718957568 bytes (2593 MB) up to 6293553152 bytes (6002 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6752m -Xms256m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		World_of_Exile-1.16.5-1.4.3.jar                   |Dungeons of Exile             |world_of_exile                |NONE                |DONE      |Manifest: NOSIGNATURE
		Divine_Missions-1.16.5-1.0.1.jar                  |Divine Missions               |divine_missions               |NONE                |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Library_of_Exile-1.16.5-1.2.3.jar                 |Library Of Exile              |library_of_exile              |NONE                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		Project_MMO-1.16.5-3.67.6.jar                     |Project MMO                   |pmmo                          |1.16.5-3.67.6       |DONE      |Manifest: NOSIGNATURE
		EpicFight-16.6.0-ALPHA.jar                        |Epic Fight                    |epicfight                     |16.6.0              |DONE      |Manifest: NOSIGNATURE
		Mine_and_Slash_BETA-1.16.5-4.0.18.jar             |Mine and Slash                |mmorpg                        |NONE                |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.1004.jar                         |Just Enough Items             |jei                           |7.7.1.1004          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 26cc4e03-60ab-4576-8913-86ae44f00d14
	Player Count: 1 / 8; [ServerPlayerEntity['HoluBeks'/185, l='ServerLevel[New World]', x=-51.37, y=66.00, z=-224.11]]
	Data Packs: vanilla, mod:world_of_exile (incompatible), mod:divine_missions (incompatible), mod:forge, mod:library_of_exile (incompatible), mod:curios, mod:pmmo (incompatible), mod:epicfight, mod:mmorpg, mod:jei
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by HoluBeks** [comment]
BTW, ignore these mods above... i tested all variants and its still giving me crash error and also if it will be needed, I will add FML report and some video proof :D, i really want to fix it

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please check your forge version first and use the latest.
