### ISSUE TITLE
Exception ticking world idk

### ISSUE THREAD

**Issue by brandonmaster590** [Yesssssman/epicfightmod#13]
it keeps crashing like every 6mins
here's the log:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2/23/21 5:56 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at maninhouse.epicfight.capabilities.entity.LivingData.getEntityState(LivingData.java:579) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.attackEntityFrom(LivingData.java:174) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.attackEvent(EntityEvents.java:273) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_137_EntityEvents_attackEvent_LivingAttackEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:336) ~[forge:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:932) ~[?:?] {re:computing_frames,re:mixin,re:classloading,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.Entity.func_241841_a(Entity.java:1981) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:notenoughcrashes.mixins.json:MixinEntity,pl:mixin:A}
	at net.minecraft.entity.monster.CreeperEntity.func_241841_a(CreeperEntity.java:196) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.majruszs_difficulty.events.monster_spawn.ChargeCreeperOnSpawn.onExecute(ChargeCreeperOnSpawn.java:25) ~[majruszs_difficulty:0.5.1] {re:classloading}
	at com.majruszs_difficulty.events.monster_spawn.OnEnemyToBeSpawnedEvent.onSpawn(OnEnemyToBeSpawnedEvent.java:23) ~[majruszs_difficulty:0.5.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_118_OnEnemyToBeSpawnedEvent_onSpawn_SpecialSpawn.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:211) ~[forge:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:174) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.lambda$tickChunks$5(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_281] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinIntegratedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Brandonmaster590'/199, l='ServerLevel[idk 2]', x=-186.07, y=50.00, z=-161.30]]
	Chunk stats: ServerChunkCache: 2114
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,72,-224), Chunk: (at 0,4,0 in -12,-14; contains blocks -192,0,-224 to -177,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 20883 game time, 20883 day time
	Level name: idk 2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 38807 (now: false), thunder time: 134352 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinIntegratedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161359424 bytes (153 MB) / 838365184 bytes (799 MB) up to 2670985216 bytes (2547 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmn128M -Xmx2560M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.26.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.26.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.26.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.26.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.26.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.26
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.26-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		TreeChop-1.16.4-0.12.2.jar                        |HT's TreeChop                 |treechop                      |0.12.2              |DONE      |NOSIGNATURE
		notenoughcrashes-3.1.6-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.1.6               |DONE      |NOSIGNATURE
		solpotato-1.16.X-1.1.0.jar                        |Spice of Life: Potato Edition |solpotato                     |1.16.X-1.1.0        |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.0.2.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.2               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.4-1.1.9.jar                   |Guard Villagers               |guardvillagers                |1.1.9               |DONE      |NOSIGNATURE
		majruszs-difficulty-1.16.4-0.5.1.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |0.5.1               |DONE      |NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.3               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		DamageTilt-1.16-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.26-universal.jar                |Forge                         |forge                         |36.0.26             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		majrusz-library-1.16.4-1.3.0.jar                  |Majrusz Library               |majrusz_library               |1.3.0               |DONE      |NOSIGNATURE
		wonderful-enchantments-1.16.4-1.0.4.jar           |Wonderful Enchantments        |wonderful_enchantments        |1.0.4               |DONE      |NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		EpicFightMod-1.16.4-2.0.2.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
	Crash Report UUID: 9e51bfab-5e98-4b21-ab63-407033be8655
	Suspected Mods: Epic Fight Mod (epicfight), Majrusz's Progressive Difficulty (majruszs_difficulty), Forge (forge), Forge (forge), Majrusz's Progressive Difficulty (majruszs_difficulty), Epic Fight Mod (epicfight)
	Player Count: 1 / 8; [ServerPlayerEntity['Brandonmaster590'/199, l='ServerLevel[idk 2]', x=-186.07, y=50.00, z=-161.30]]
	Data Packs: vanilla, mod:farmersdelight, mod:yungsapi, mod:treechop, mod:notenoughcrashes, mod:solpotato (incompatible), mod:bookshelf, mod:enchdesc, mod:guardvillagers, mod:majruszs_difficulty, mod:spiderstpo, mod:dungeons_plus, mod:jei, mod:forge, mod:majrusz_library, mod:wonderful_enchantments, mod:tlskincape (incompatible), mod:bettermineshafts (incompatible), mod:bettercaves (incompatible), mod:epicfight, mod:structure_gel, mod:damagetilt (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8681
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Yesssssman** [comment]
Please note me it still occurs when 2.0.3 version updated.

**Comment by brandonmaster590** [comment]
its not crashing anymore thank!

**Comment by brandonmaster590** [comment]
found some modeling bugs. baby zombie have adult armor and idk if you added the bout sitting animation or not but imma put it here
![2021-02-25_21 24 18](https://user-images.githubusercontent.com/59051287/109415607-38f8bc00-79ec-11eb-90c1-1e315176e117.png)
![2021-02-27_13 56 16](https://user-images.githubusercontent.com/59051287/109415612-3bf3ac80-79ec-11eb-8366-7436dc199645.png)
