### ISSUE TITLE
1.16.4 Game crashes once i start walking / left mouse click

### ISSUE THREAD

**Issue by Nezaniatoyimia** [Yesssssman/epicfightmod#14]
i literally have no other mods besides this one, Help?
Here's the crash log:

Time: 2/23/21 8:48 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at maninhouse.epicfight.client.events.engine.ControllEngine.sneakKeyPressed(ControllEngine.java:169) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.ControllEngine$Events.keyboardEvent(ControllEngine.java:457) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_57_Events_keyboardEvent_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:729) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:887) ~[?:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.call(ReflectorMethod.java:133) ~[?:?] {re:classloading}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:548) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:622) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:621) ~[?:?] {re:classloading,xf:OptiFine:default}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:388) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at maninhouse.epicfight.client.events.engine.ControllEngine.sneakKeyPressed(ControllEngine.java:169) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.events.engine.ControllEngine$Events.keyboardEvent(ControllEngine.java:457) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_57_Events_keyboardEvent_KeyInputEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.fireKeyInput(ForgeHooksClient.java:729) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at net.optifine.reflect.Reflector.call(Reflector.java:887) ~[?:?] {re:classloading}
	at net.optifine.reflect.ReflectorMethod.call(ReflectorMethod.java:133) ~[?:?] {re:classloading}
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:548) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.KeyboardListener.lambda$null$7(KeyboardListener.java:622) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.KeyboardListener.lambda$setupCallbacks$8(KeyboardListener.java:621) ~[?:?] {re:classloading,xf:OptiFine:default}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Jan_the_wizard'/393, l='ClientLevel', x=-207.93, y=76.00, z=234.56]]
	Chunk stats: Client Chunk Cache: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,76,224), Chunk: (at 0,4,0 in -13,14; contains blocks -208,0,224 to -193,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 171 game time, 171 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10014941736 bytes (9550 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx10239M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.4_HD_U_G6_pre12.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.4-1.16.jar                |TLSkinCape                    |tlskincape                    |1.6                 |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		EpicFightMod-1.16.4-2.0.2.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
	Crash Report UUID: e30cbebb-2f28-4cde-8672-d1852b1d9a47
	Launched Version: ForgeOptiFine 1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.16.4_HD_U_G6_pre12
	OptiFine Build: 20210110-191159
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13 V6 Medium.zip
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Yesssssman** [comment]
Don't use 35.1.37 version now cause it ruined my mod entirely.

**Comment by TronXyrzX** [comment]
> Don't use 35.1.37 version now cause it ruined my mod entirely.

this same issue happens when i use the 1.14.4 version. What version of forge should i use?
