### ISSUE TITLE
[Bug|Crash]: crashing with stellarity mod/datapack 1.20.1 

### ISSUE THREAD

**Issue by thiccmeme** [Yesssssman/epicfightmod#1405]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

the dragon fight is the issue, everything else on both single and multiplayer running 1.20.1 forge version 47.2.1 and epic fight 20.5.15. 

when the dragon goes to perch/ activate it's ground fighting mode added by epic fight the game crashes, this issue is repeatable on both client and server side installations. 

I believe this line of the log summarizes the issue: (I have also attached the full log file)

[17Oct.2023 16:42:41.699] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.dimension.end.EndDragonFight.m_64098_()" because the return value of "net.minecraft.world.entity.boss.enderdragon.EnderDragon.m_31158_()" is null
	at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.DragonFlyingPhase.findNewTarget(DragonFlyingPhase.java:59) ~[EpicFight-20.5.15.jar%23309!/:20.5.15]
	at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.DragonFlyingPhase.m_6989_(DragonFlyingPhase.java:34) ~[EpicFight-20.5.15.jar%23309!/:20.5.15]
	at net.minecraft.world.entity.boss.enderdragon.EnderDragon.m_8107_(EnderDragon.java:245) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?]

[latest.log](https://github.com/Yesssssman/epicfightmod/files/12968000/latest.log)

**Comment by LuksMart** [comment]
How do i fix this? got the same crash problem

**Comment by Yesssssman** [comment]
Sorry I forgot to mention, Fixed in the latest version
