### ISSUE TITLE
[Bug|Crash]: Epicfight Pirates addon isnt loading

### ISSUE THREAD

**Issue by MacMandotcom** [Yesssssman/epicfightmod#1416]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epicfight Pirates

### Minecraft Version

1.18.2

### What happened?

It says ''Epic Fight Pirates (efmpirates) has failed to load correctly"

This is the latest.log:

[16:06:57] [main/INFO]: ModLauncher running: args [--username, MacMan, --version, epic fight tt, --gameDir, C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt, --assetsDir, C:\Users\Toshiba\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 0bbbb9b5491d4e2d9f77680ef6c38f34, --accessToken, ????????, --clientId, null, --xuid, null, --userType, mojang, --versionType, release, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[16:06:57] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[16:06:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Toshiba/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[16:06:59] [main/INFO]: Found mod file appleskin-forge-mc1.18.2-2.5.1.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file carryon-1.18.2-1.17.1.12.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file DualGreatsword-1.9.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file EF_Knuckles_extended_18.2.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file EpicFight-18.5.15-beta.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file EpicfightPirates-1.2.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file epicsamurai-0.0.2-1.18.2-forge.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file falchionmoveset-18.5.0.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file FallingTree-1.18.2-3.5.5.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file FpsReducer2-forge-1.18.2-2.0.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file geckolib-forge-1.18-3.0.57.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file jei-1.18.2-forge-10.2.1.1005.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file journeymap-1.18.2-5.9.7-forge.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file MmmMmmMmmMmm-1.18.2-1.5.2.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file Neat-1.8-31.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file Patchouli-1.18.2-71.1.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file selene-1.18.2-1.17.14.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file ShoulderSurfing-Forge-1.18.2-2.6.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file tl_skin_cape_forge_1.18_1.18.2-1.25.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:06:59] [main/INFO]: Found mod file WeaponsOfMiracles-18.1.7.24.jar of type MOD with provider {mods folder locator at C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\mods}
[16:07:00] [main/WARN]: Mod file C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[16:07:00] [main/WARN]: Mod file C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[16:07:00] [main/WARN]: Mod file C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[16:07:00] [main/WARN]: Mod file C:\Users\Toshiba\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[16:07:00] [main/INFO]: Found mod file fmlcore-1.18.2-40.2.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: Found mod file mclanguage-1.18.2-40.2.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: Found mod file forge-1.18.2-40.2.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4163f1cd
[16:07:00] [main/INFO]: No dependencies to load found. Skipping!
[16:07:06] [main/INFO]: Compatibility level set to JAVA_17
[16:07:06] [main/ERROR]: Mixin config epicsamurai.mixins.json does not specify "minVersion" property
[16:07:08] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[16:07:08] [main/INFO]: Launching target 'forgeclient' with arguments [--version, epic fight tt, --gameDir, C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt, --assetsDir, C:\Users\Toshiba\AppData\Roaming\.minecraft\assets, --uuid, 0bbbb9b5491d4e2d9f77680ef6c38f34, --username, MacMan, --assetIndex, 1.18, --accessToken, ????????, --clientId, null, --xuid, null, --userType, mojang, --versionType, release, --width, 925, --height, 530]
[16:07:08] [main/WARN]: Reference map 'arclight.mixins.refmap.json' for epicsamurai.mixins.json could not be read. If this is a development environment you can ignore this message
[16:07:09] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net.optifine.shaders.ShadersRender)
[16:07:09] [main/WARN]: @Mixin target net.optifine.shaders.ShadersRender was not found shouldersurfing.mixins.json:MixinShadersRender
[16:07:20] [pool-3-thread-1/WARN]: @Final field f_31427_:[I in epicfight.mixins.json:MixinWitherBoss should be final
[16:07:20] [pool-3-thread-1/WARN]: @Final field f_31428_:[I in epicfight.mixins.json:MixinWitherBoss should be final
[16:07:34] [Render thread/WARN]: Assets URL 'union:/C:/Users/Toshiba/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2374!/assets/.mcassetsroot' uses unexpected schema
[16:07:34] [Render thread/WARN]: Assets URL 'union:/C:/Users/Toshiba/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2374!/data/.mcassetsroot' uses unexpected schema
[16:07:34] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:07:34] [Render thread/INFO]: Setting user: MacMan
[16:07:35] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[16:07:42] [modloading-worker-0/INFO]: register skill efdg:earthquake
[16:07:42] [modloading-worker-0/INFO]: register skill efdg:dualgreatsword
[16:07:42] [modloading-worker-0/INFO]: Forge mod loading, version 40.2.0, for MC 1.18.2 with MCP 20220404.173914
[16:07:42] [modloading-worker-0/INFO]: MinecraftForge v40.2.0 Initialized
[16:07:42] [modloading-worker-0/INFO]: register skill wom:ender_step
[16:07:42] [modloading-worker-0/INFO]: register skill wom:ender_obscuris
[16:07:42] [modloading-worker-0/INFO]: register skill wom:dodge_master
[16:07:42] [modloading-worker-0/INFO]: register skill wom:precise_roll
[16:07:42] [modloading-worker-0/INFO]: register skill wom:shadow_step
[16:07:42] [modloading-worker-0/INFO]: register skill wom:bull_charge
[16:07:42] [modloading-worker-0/INFO]: register skill wom:demon_mark_passive
[16:07:42] [modloading-worker-0/INFO]: register skill wom:torment_passive
[16:07:42] [modloading-worker-0/INFO]: register skill wom:ruine_passive
[16:07:42] [modloading-worker-0/INFO]: register skill wom:lunar_eclipse_passive
[16:07:42] [modloading-worker-0/INFO]: register skill wom:satsujin_passive
[16:07:42] [modloading-worker-0/INFO]: register skill wom:charybdis
[16:07:42] [modloading-worker-0/INFO]: register skill wom:agony_plunge
[16:07:42] [modloading-worker-0/INFO]: register skill wom:true_berserk
[16:07:42] [modloading-worker-0/INFO]: register skill wom:plunder_perdition
[16:07:42] [modloading-worker-0/INFO]: register skill wom:sakura_state
[16:07:42] [modloading-worker-0/INFO]: register skill wom:ender_blast
[16:07:42] [modloading-worker-0/INFO]: register skill wom:ender_fusion
[16:07:42] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: efmpirates, class reascer.efmpirates.main.EpicfightPirates
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%2376!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%2375!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: yesman/epicfight/gameasset/Models
	at reascer.efmpirates.main.EpicfightPirates.<init>(EpicfightPirates.java:31) ~[EpicfightPirates-1.2.jar%2358!/:1.2]
	... 14 more
Caused by: java.lang.ClassNotFoundException: yesman.epicfight.gameasset.Models
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at reascer.efmpirates.main.EpicfightPirates.<init>(EpicfightPirates.java:31) ~[EpicfightPirates-1.2.jar%2358!/:1.2]
	... 14 more
[16:07:43] [modloading-worker-0/INFO]: register skill wom:demonic_ascension
[16:07:43] [modloading-worker-0/INFO]: register skill wom:regierung
[16:07:43] [modloading-worker-0/INFO]: register skill wom:lunar_echo
[16:07:43] [modloading-worker-0/INFO]: register skill wom:counter_attack
[16:07:43] [modloading-worker-0/INFO]: register skill wom:perfect_bulwark
[16:07:43] [modloading-worker-0/INFO]: register skill wom:vengeful_parry
[16:07:43] [modloading-worker-0/INFO]: register skill wom:arrow_tenacity
[16:07:43] [modloading-worker-0/INFO]: register skill wom:pain_anticipation
[16:07:43] [modloading-worker-0/INFO]: register skill wom:pain_retribution
[16:07:43] [modloading-worker-0/INFO]: register skill wom:vampirize
[16:07:43] [modloading-worker-0/INFO]: register skill wom:critical_knowledge
[16:07:43] [modloading-worker-0/INFO]: register skill wom:heart_shield
[16:07:43] [modloading-worker-0/INFO]: register skill wom:mindset
[16:07:43] [modloading-worker-0/INFO]: register skill wom:adrenaline
[16:07:43] [modloading-worker-0/INFO]: register skill wom:dancing_blade
[16:07:43] [modloading-worker-0/INFO]: register skill falchionmoveset:falchion_art
[16:07:43] [modloading-worker-0/INFO]: register skill wom:meditation
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:basic_attack
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:air_attack
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:roll
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:step
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:knockdown_wakeup
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:guard
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:parrying
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:impact_guard
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:berserker
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:death_harvest
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:emergency_escape
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:endurance
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:forbidden_strength
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:hypervitality
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:stamina_pillager
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:swordmaster
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:technician
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:sweeping_edge
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:dancing_edge
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:the_guillotine
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:grasping_spire
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:heartpiercer
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:steel_whirlwind
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:battojutsu
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:battojutsu_passive
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:rushing_tempo
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:relentless_combo
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:liechtenauer
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:sharp_stab
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:eviscerate
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:blade_rush
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:wrathful_lighting
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:tsunami
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:everlasting_allegiance
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:meteor_slam
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:revelation
[16:07:43] [modloading-worker-0/INFO]: register skill epicfight:demolition_leap
[16:07:44] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[16:07:44] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
[16:07:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state
[16:07:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state
[16:07:46] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RenderLevelStageEvent$RegisterStageEvent to a broken mod state
[16:07:46] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state
[16:07:46] [Render thread/INFO]: Narrator library for x64 successfully loaded
[16:07:47] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state
[16:07:47] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state
[16:07:47] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state
[16:07:47] [Render thread/INFO]: Reloading ResourceManager: Default
[16:07:48] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state
[16:07:50] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:07:59] [Worker-Main-6/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:16] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:16] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:26] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[16:08:27] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (2- High Definition Audio Device)
[16:08:27] [Render thread/INFO]: Sound engine started
[16:08:28] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:28] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:08:28] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state
[16:08:30] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state
[16:08:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state
[16:08:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16:08:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:08:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:33] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:08:33] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[16:08:35] [Render thread/FATAL]: Preparing crash report with UUID 61171230-52bc-43d7-8875-f92f80768649
[16:08:35] [Render thread/FATAL]: Crash report saved to C:\Users\Toshiba\AppData\Roaming\.minecraft\versions\epic fight tt\crash-reports\crash-2023-10-25_16.08.35-fml.txt
[16:08:35] [Render thread/FATAL]: Preparing crash report with UUID ec2507fb-3894-471d-a01d-445eae374063

**Comment by MetalKnight56** [comment]
Epic AFight pirates is yet to be updated to support epic fight's latest versions. Please contact said mod's author about this issue.
