### ISSUE TITLE
[Bug]: 400 mods + report

### ISSUE THREAD

**Issue by Dare-Demonai** [Yesssssman/epicfightmod#1423]
### Have you checked if a similar issue is already reported by someone else?

- [ ] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight Dodge and Roll 

### Minecraft Version

1.18.2

### What happened?

Dodge and Roll is not working.
I learned the skill book and remapped the controls but it is still not working.
For some reason, every time I dodge or roll nothing happens but my stamina is being consumed.
I'm using Epic Fight mod in a modpack so I don't know if it's a compatibility issue. As I scan my mod packs I don't see anything that would be incompatible with the mod.

**Comment by Dare-Demonai** [comment]
After testing the mod alone, the dodge works. I'm now trying to find out what mod causes the bug. I'll update as soon as I can since I have over 400+ mods

**Comment by Dare-Demonai** [comment]
I don't know if this is useful, but I still haven't found the cause, I checked my logs and this is what I found.


[04:21:32] [Server thread/ERROR]: 
[04:21:32] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket@2aeda0f, suppressing error
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "entityType" is null
	at TRANSFORMER/vmh@1.2.2-forge-1.18.2/com.rikurob.vmh.util.ScalingHandler.ScaleEntity(ScalingHandler.java:30)
	at TRANSFORMER/vmh@1.2.2-forge-1.18.2/com.rikurob.vmh.event.EntityJoinsWorldEvent.execute(EntityJoinsWorldEvent.java:61)
	at TRANSFORMER/vmh@1.2.2-forge-1.18.2/com.rikurob.vmh.event.EntityJoinsWorldEvent.onEntitySpawned(EntityJoinsWorldEvent.java:24)
	at net.minecraftforge.eventbus.ASMEventHandler_204_EntityJoinsWorldEvent_onEntitySpawned_EntityJoinWorldEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManager.java:80)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157533_(PersistentEntitySectionManager.java:72)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8872_(ServerLevel.java:846)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_7967_(ServerLevel.java:754)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.api.animation.types.DodgeAnimation.begin(DodgeAnimation.java:56)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.api.animation.ServerAnimator.playAnimation(ServerAnimator.java:31)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.playAnimationSynchronized(LivingEntityPatch.java:411)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.playAnimationSynchronized(ServerPlayerPatch.java:195)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.playAnimationSynchronized(LivingEntityPatch.java:407)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.skill.dodge.DodgeSkill.executeOnServer(DodgeSkill.java:121)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.skill.SkillContainer.requestExecute(SkillContainer.java:176)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.network.client.CPExecuteSkill.lambda$handle$0(CPExecuteSkill.java:73)
	at TRANSFORMER/forge@40.2.10/net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:213)
	at TRANSFORMER/epicfight@18.5.16/yesman.epicfight.network.client.CPExecuteSkill.handle(CPExecuteSkill.java:66)
	at TRANSFORMER/forge@40.2.10/net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115)

**Comment by Dare-Demonai** [comment]
After three days of searching and wandering aimlessly, I can finally say I FOUND IT!

RANSFORMER/vmh@1.2.2-forge-1.18.2/com.rikurob.vmh.util.ScalingHandler.ScaleEntity(ScalingHandler.java:30)
at TRANSFORMER/vmh@1.2.2-forge-1.18.2/com.rikurob.vmh.event.EntityJoinsWorldEvent.execute(EntityJoinsWorldEvent.java:61)
at TRANSFORMER/vmh@1.2.2-forge


ITS THE VARIABLE MOB HEIGHT MOD
