### ISSUE TITLE
[Bug|Crash]: NullPointerException

### ISSUE THREAD

**Issue by FortyTwoCn** [Yesssssman/epicfightmod#1435]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Crashes from time to time, and I don't know how to reproduce  it 
```
java.lang.NullPointerException: Ticking entity
	at yesman.epicfight.gameasset.Animations.lambda$build$7(Animations.java:1075) ~[?:16.6.4] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.api.animation.types.StaticAnimation$Event.testAndExecute(StaticAnimation.java:259) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.StaticAnimation.lambda$tick$2(StaticAnimation.java:137) ~[?:16.6.4] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_172] {}
	at yesman.epicfight.api.animation.types.StaticAnimation.tick(StaticAnimation.java:125) ~[?:16.6.4] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.api.animation.types.MainFrameAnimation.tick(MainFrameAnimation.java:46) ~[?:16.6.4] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.api.animation.types.ActionAnimation.tick(ActionAnimation.java:73) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.api.animation.types.procedural.EnderDragonActionAnimation.tick(EnderDragonActionAnimation.java:106) ~[?:16.6.4] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[?:16.6.4] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[?:16.6.4] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.tick(EnderDragonPatch.java:135) ~[?:16.6.4] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[?:16.6.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_624_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[CatServer-1.16.5-98eabb0e-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[CatServer-1.16.5-98eabb0e-server.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinForgeHooks,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2575) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:mixins.mega.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:kubejs-common.mixins.json:LivingEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ExpInvokerMixin,pl:mixin:APP:ars_nouveau.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:343) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:756) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:811) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:twilightforest:hitbox,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:APP:assets/astralsorcery/astralsorcery.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:529) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.entity_load_deadlock.ServerLevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1049) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172] {}
```

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer supported.
