### ISSUE TITLE
[1.12.2]throw Exception in server

### ISSUE THREAD

**Issue by AKreedz** [Yesssssman/epicfightmod#146]
[forge server, forge version:14.23.5.2854]
I change to battle mode,and punch.

> java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at maninthehouse.epicfight.capabilities.entity.LivingData.getAttackDirectionPitch(LivingData.java:323) ~[LivingData.class:?]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.lambda$getPoseByTime$2(AttackAnimation.java:218) ~[AttackAnimation.class:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.getPoseByTime(AttackAnimation.java:217) ~[AttackAnimation.class:?]
	at maninthehouse.epicfight.animation.types.DynamicAnimation.getLinkAnimation(DynamicAnimation.java:72) ~[DynamicAnimation.class:?]
	at maninthehouse.epicfight.animation.types.attack.AAAnimation.getLinkAnimation(AAAnimation.java:59) ~[AAAnimation.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:36) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.capabilities.entity.LivingData.getAttackDirectionPitch(LivingData.java:323) ~[LivingData.class:?]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.lambda$getPoseByTime$2(AttackAnimation.java:218) ~[AttackAnimation.class:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.getPoseByTime(AttackAnimation.java:217) ~[AttackAnimation.class:?]
	at maninthehouse.epicfight.animation.types.DynamicAnimation.getLinkAnimation(DynamicAnimation.java:72) ~[DynamicAnimation.class:?]
	at maninthehouse.epicfight.animation.types.attack.AAAnimation.getLinkAnimation(AAAnimation.java:59) ~[AAAnimation.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:36) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@d8948cd from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.capabilities.entity.LivingData.getAttackDirectionPitch(LivingData.java:323) ~[LivingData.class:?]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.lambda$getPoseByTime$2(AttackAnimation.java:218) ~[AttackAnimation.class:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.getPoseByTime(AttackAnimation.java:217) ~[AttackAnimation.class:?]
	at maninthehouse.epicfight.animation.types.DynamicAnimation.getLinkAnimation(DynamicAnimation.java:72) ~[DynamicAnimation.class:?]
	at maninthehouse.epicfight.animation.types.attack.AAAnimation.getLinkAnimation(AAAnimation.java:59) ~[AAAnimation.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:36) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more
Caused by: java.lang.RuntimeException: Attempted to load class bib for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.capabilities.entity.LivingData.getAttackDirectionPitch(LivingData.java:323) ~[LivingData.class:?]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.lambda$getPoseByTime$2(AttackAnimation.java:218) ~[AttackAnimation.class:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_281]
	at maninthehouse.epicfight.animation.types.attack.AttackAnimation.getPoseByTime(AttackAnimation.java:217) ~[AttackAnimation.class:?]
	at maninthehouse.epicfight.animation.types.DynamicAnimation.getLinkAnimation(DynamicAnimation.java:72) ~[DynamicAnimation.class:?]
	at maninthehouse.epicfight.animation.types.attack.AAAnimation.getLinkAnimation(AAAnimation.java:59) ~[AAAnimation.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:36) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
	... 5 more

**Comment by Yesssssman** [comment]
Version pls?

**Comment by AKreedz** [comment]
> Version pls?

2.1.0,I try your new version 2.1.2 and now there is no exception,nice work.
