### ISSUE TITLE
[Bug|Crash]: Cannot invoke "yesman.epicfight.skill.SkillDataKey.readFromBuffer(

### ISSUE THREAD

**Issue by wujekbobixon** [Yesssssman/epicfightmod#1560]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

![image](https://github.com/Yesssssman/epicfightmod/assets/33070347/9a8d8d24-a345-4674-9af3-2f4cb74164a2)
After using a combat mode, uchigatana doesnt work  and double jump also step  crash game

**Comment by wujekbobixon** [comment]
lol that mod work normal on single but after update on server just crashing a client from server

**Comment by wujekbobixon** [comment]
[00:58:27] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null
	Index: 6
	Listeners:
 0: HIGHEST
 1: ASM: thut.essentials.land.LandEventsHandler$InteractEventHandler@27b203e8 interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
 2: HIGH
 3: net.minecraftforge.eventbus.EventBus$$Lambda$4180/0x0000000801a71598@43f1f1cb
 4: NORMAL
 5: ASM: class xyz.przemyk.simpleplanes.misc.CommonEventHandler interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
 6: ASM: class yesman.epicfight.events.PlayerEvents rightClickItemServerEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
 7: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@41358fad curioRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
 8: ASM: class thut.essentials.commands.land.claims.Deed interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickItem;)V
 9: ASM: class com.aetherteam.aether.event.listeners.abilities.ToolAbilityListener onEntityInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.skill.BattojutsuPassive.onReset(BattojutsuPassive.java:45)
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.skill.BattojutsuPassive.lambda$onInitiate$1(BattojutsuPassive.java:30)
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22)
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73)
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.events.PlayerEvents.rightClickItemServerEvent(PlayerEvents.java:60)
	at TRANSFORMER/epicfight@20.7.2/yesman.epicfight.events.__PlayerEvents_rightClickItemServerEvent_RightClickItem.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:771)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:282)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by EnyelBTW** [comment]
Try intalling the spit it out mod to your client that should fix it
I had the same issue

**Comment by wujekbobixon** [comment]
Still the same problem with this mod ;( 
![image](https://github.com/Yesssssman/epicfightmod/assets/33070347/048a4365-3b0c-473c-9f9a-243416cd39f2)
https://www.curseforge.com/minecraft/mc-mods/spit-it-out
