### ISSUE TITLE
[Bug|Crash]: yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null

### ISSUE THREAD

**Issue by wujekbobixon** [Yesssssman/epicfightmod#1566]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Hey i have problem the same with uchigatana after join to server that item disconnecting me from server server got a erorr
 ```
[19:01:29]` [Server thread/ERROR] inecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@5de70206, suppressing error
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "yesman.epicfight.skill.SkillDataManager.getDataValue(yesman.epicfight.skill.SkillDataKey)" is null
	at yesman.epicfight.skill.BattojutsuPassive.onReset(BattojutsuPassive.java:45) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.skill.BattojutsuPassive.lambda$onInitiate$1(BattojutsuPassive.java:30) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.events.PlayerEvents.rightClickItemServerEvent(PlayerEvents.java:60) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.events.__PlayerEvents_rightClickItemServerEvent_RightClickItem.invoke(.dynamic) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onItemRightClick(ForgeHooks.java:771) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:282) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:physicsmod.mixins.json:fabricapi.MixinServerPlayerInteractionManager,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1087) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
[19:01:35] [Server thread/INFO] inecraft/ServerGamePacketListenerImpl]: wujekbobixon lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataKey.readFromBuffer(io.netty.buffer.ByteBuf)" because the return value of "yesman.epicfight.skill.SkillDataKey.byId(int)" is null
[19:01:35] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon left the game
[19:01:43] [Server thread/INFO] inecraft/PlayerList]: wujekbobixon[] logged in with entity id 3624 at (1811.1480150020448, 77.1212968405392, 2406.884291292329)
[19:01:43] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon joined the game
[19:01:43] [Server thread/INFO] [spawnermod/]: Sending config to player.
[19:01:46] [Server thread/INFO] inecraft/ServerGamePacketListenerImpl]: wujekbobixon lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataKey.readFromBuffer(io.netty.buffer.ByteBuf)" because the return value of "yesman.epicfight.skill.SkillDataKey.byId(int)" is null
```
animation doesnt work on this weapon and after join again to server double jump also disconnecting. Additionally, after joining the server and starting with this weapon in your hand, the stamina regenerates and crashes from the game after loading. 
![image](https://github.com/Yesssssman/epicfightmod/assets/33070347/2874a58d-d95b-48d4-8ad4-343c80016487)

**Comment by MetalKnight56** [comment]
Update the mod

**Comment by wujekbobixon** [comment]
@MetalKnight56  Bro it is a last update ?   ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}

**Comment by MetalKnight56** [comment]
> @MetalKnight56 Bro is it a last update ? ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading} if yes that error show me above

what, EpicFight-20.7.3 fixed your issue... i don't understand what you just tried to say....

**Comment by wujekbobixon** [comment]
@MetalKnight56  I just want to tell my friend that this weapon kicks you out of the server and now I discovered that double jumping after leaving the server and entering about 5 minutes later also throws you out of the server. Only then restarting Minecraft helps with this double jump

**Comment by wujekbobixon** [comment]
If you want, I can send you my mod pack, if it helps, and here's the clips, buddy 

https://github.com/Yesssssman/epicfightmod/assets/33070347/5e500fb6-b428-4389-a827-3e0e43c2683d


https://github.com/Yesssssman/epicfightmod/assets/33070347/f0a044b2-3f1b-4a50-9d91-d2e8f25354e3


https://github.com/Yesssssman/epicfightmod/assets/33070347/61fa01d9-0b1a-4e04-95ef-86c91417c3ed

**Comment by MetalKnight56** [comment]
> @MetalKnight56 If you want, I can send you my mod pack, if it helps, and here's the clips, buddy
And can you attach your logs please?

**Comment by wujekbobixon** [comment]
While joining  with weapon in hand 
```

[02:36:09] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon joined the game
[02:36:09] [Server thread/INFO] [spawnermod/]: Sending config to player.
[02:36:14] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "java.lang.Boolean.booleanValue()" because "val" is null
	Index: 5
	Listeners:
 0: NORMAL
 1: ASM: com.github.alexthe666.citadel.server.CitadelEvents@4dd9932b onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 2: ASM: class thut.essentials.defuzz.SpawnDefuzzer EntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 3: ASM: com.mrcrayfish.framework.event.ForgeEvents@2f331b00 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 4: ASM: class reascer.wom.events.WOMLivingEntityEvents onUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 5: ASM: class yesman.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 6: ASM: class com.aetherteam.aether.event.listeners.capability.AetherPlayerListener onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 7: ASM: class com.aetherteam.aether.event.listeners.abilities.ArmorAbilityListener onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 8: net.minecraftforge.eventbus.EventBus$$Lambda$4148/0x0000000801a62548@68831ab
 9: ASM: thut.essentials.land.LandEventsHandler$EntityEventHandler@173e5021 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 10: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@3084e182 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 11: ASM: thut.essentials.util.PlayerMover@704662c2 playerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
 12: ASM: class thut.essentials.commands.land.claims.Claim livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "val" is null
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillDataKey.lambda$createBooleanKey$6(SkillDataKey.java:85)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillDataKey.writeToBuffer(SkillDataKey.java:146)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.network.server.SPModifySkillData.toBytes(SPModifySkillData.java:44)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.network.EpicFightNetworkManager.sendToClient(EpicFightNetworkManager.java:53)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.network.EpicFightNetworkManager.sendToPlayer(EpicFightNetworkManager.java:65)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillDataManager.syncData(SkillDataManager.java:94)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillDataManager.setDataSync(SkillDataManager.java:79)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.BattojutsuPassive.setConsumption(BattojutsuPassive.java:61)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillContainer.setResource(SkillContainer.java:114)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.Skill.updateContainer(Skill.java:259)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.skill.SkillContainer.update(SkillContainer.java:262)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:200)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:115)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98)
	at TRANSFORMER/epicfight@20.7.3/yesman.epicfight.events.__EntityEvents_updateEvent_LivingTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.20/net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
321:324: symbol lookup error: /usr/lib/peer_name_spoofer.so: undefined symbol: dlsym
[02:36:14] [Server thread/WARN] inecraft/ServerConnectionListener]: Failed to handle packet for /ip
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:530) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puffish_skills.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:epicfight.mixins.json:MixinServerPlayer,pl:mixin:APP:thutessentials.mixins.json:MixinServerPlayerEntity,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerPlayerTimeInAirMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.wildlands.json:CommonMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because "val" is null
	at yesman.epicfight.skill.SkillDataKey.lambda$createBooleanKey$6(SkillDataKey.java:85) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.skill.SkillDataKey.writeToBuffer(SkillDataKey.java:146) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.network.server.SPModifySkillData.toBytes(SPModifySkillData.java:44) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:121) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryEncode(IndexedMessageCodec.java:119) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:134) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at yesman.epicfight.network.EpicFightNetworkManager.sendToClient(EpicFightNetworkManager.java:53) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:mixin,re:classloading}
	at yesman.epicfight.network.EpicFightNetworkManager.sendToPlayer(EpicFightNetworkManager.java:65) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:mixin,re:classloading}
	at yesman.epicfight.skill.SkillDataManager.syncData(SkillDataManager.java:94) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.skill.SkillDataManager.setDataSync(SkillDataManager.java:79) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.skill.BattojutsuPassive.setConsumption(BattojutsuPassive.java:61) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.skill.SkillContainer.setResource(SkillContainer.java:114) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.skill.Skill.updateContainer(Skill.java:259) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.skill.SkillContainer.update(SkillContainer.java:262) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:runtimedistcleaner:A}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:200) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:115) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading}
	at yesman.epicfight.events.__EntityEvents_updateEvent_LivingTickEvent.invoke(.dynamic) ~[EpicFight-20.7.3.jar%23143!/:20.7.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.20.1-47.2.20-universal.jar%23174!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puffish_skills.mixins.json:LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.LivingEntityMixin,pl:mixin:APP:aether.mixins.json:common.accessor.LivingEntityAccessor,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:epicfight.mixins.json:MixinLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityAccessor,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puffish_skills.mixins.json:PlayerEntityMixin,pl:mixin:APP:aether.mixins.json:common.PlayerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.PlayerAccessor,pl:mixin:APP:epicfight.mixins.json:MixinPlayer,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.PlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.HoneyShieldPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:items.PlayerDamageShieldInvoker,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[server-1.20.1-20230612.114412-srg.jar%23169!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puffish_skills.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:epicfight.mixins.json:MixinServerPlayer,pl:mixin:APP:thutessentials.mixins.json:MixinServerPlayerEntity,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerPlayerMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.ServerPlayerTimeInAirMixin,pl:mixin:A}
	... 9 more
[02:36:14] [Server thread/INFO] inecraft/ServerGamePacketListenerImpl]: wujekbobixon lost connection: Internal server error
[02:36:14] [Server thread/INFO] inecraft/MinecraftServer]: wujekbobixon left the game 

```

**Comment by MetalKnight56** [comment]
Try removing WOM, Citadel (and mods reliant on it such as alex's caves and others), essentials and all mrcrayfishes mods

**Comment by wujekbobixon** [comment]
@MetalKnight56 But I only updated EPIC FIGHT and WOM. Previously, this weapon probably worked on 6.3. And one more question because I would like to add your attributes for example stamina in puffskill (mod). What type and attribute should I enter? Or where can I find them? 
```
  "staminar+10%": {
    "title": "+10% Stamina Epic Fight",
    "icon": {
      "type": "effect",
      "data": {
        "effect": "jump_boost"
      }
    },
    "rewards": [
      {
        "type": "epicfight:attribute",
        "data": {
          "attribute": "epicfight:player.staminar",
          "value": 0.1,
          "operation": "multiply_total"
        }
      }
    ]
  },
```

**Comment by wujekbobixon** [comment]
@MetalKnight56  My friend, I found it to be the fault of the current WOM version.  If this caused you a problem, I'm sorry
