### ISSUE TITLE
[Bug|Crash]: When I activate the passive skill swordmaster and attack, an Internal Server Error occurs.

### ISSUE THREAD

**Issue by rolestack** [Yesssssman/epicfightmod#1589]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.18.2

### What happened?

Activating the swordmaster skill is not a problem, but when I use a normal attack, an error occurs within a few seconds and there is a disconnect problem with the server.

```
[10:47:18] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
Minecraft    |  Index: 11
Minecraft    |  Listeners:
Minecraft    |          0: NORMAL
Minecraft    |          1: ASM: class com.tarinoita.solapplepie.tracking.benefits.BenefitsHandler tickBenefits(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          2: ASM: org.infernalstudios.infernalexp.events.MiscEvents@ea5bf50 onLivingEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          3: ASM: class mods.thecomputerizer.reputation.common.event.TweakEvents livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          4: ASM: com.nameless.impactful.EventHandler@574d6b16 onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          5: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@633b9f9f onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          6: ASM: class com.itayfeder.restored_earth.events.EntityTickEventHandler livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          7: ASM: class com.mlib.contexts.OnEntityTick onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          8: ASM: class reascer.wom.events.WOMLivingEntityEvents onUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          9: ASM: class net.mcreator.undeadrevamp.init.EntityAnimationFactory onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          10: ASM: class com.legacy.blue_skies.events.SkiesEvents onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          11: ASM: class yesman.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          12: ASM: insane96mcp.progressivebosses.module.wither.feature.MiscFeature@23de806c onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          13: ASM: insane96mcp.progressivebosses.module.wither.feature.HealthFeature@4bb5804 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          14: ASM: insane96mcp.progressivebosses.module.wither.feature.MinionFeature@44fe5f1e update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          15: ASM: insane96mcp.progressivebosses.module.wither.feature.AttackFeature@3ac6b173 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          16: ASM: insane96mcp.progressivebosses.module.dragon.feature.HealthFeature@66ee13cb onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          17: ASM: insane96mcp.progressivebosses.module.dragon.feature.RewardFeature@3a02429f onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          18: ASM: insane96mcp.progressivebosses.module.dragon.feature.MinionFeature@4ecd94ef update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          19: ASM: insane96mcp.progressivebosses.module.dragon.feature.LarvaFeature@4db3f37f update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          20: ASM: insane96mcp.progressivebosses.module.elderguardian.feature.HealthFeature@60181966 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          21: ASM: insane96mcp.progressivebosses.module.elderguardian.feature.MinionFeature@192ab678 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          22: ASM: com.afunproject.dawncraft.classes.EventHandler@5bf6eb3d tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          23: ASM: class tschipp.callablehorses.common.events.EntityEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          24: net.minecraftforge.eventbus.EventBus$$Lambda$1496/0x00007fb8746dc250@2c858d8e
Minecraft    |          25: net.minecraftforge.eventbus.EventBus$$Lambda$1496/0x00007fb8746dc250@9094493
Minecraft    |          26: ASM: class com.teamabnormals.savage_and_ravage.core.other.SREvents onUpdateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          27: ASM: class com.teamabnormals.savage_and_ravage.core.other.SREvents livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          28: ASM: com.github.alexthe666.citadel.server.CitadelEvents@1d97a516 onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          29: ASM: L_Ender.cataclysm.event.ServerEventHandler@626f154c onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          30: ASM: class net.mcreator.enlightened_end.init.AnimationSyncFactory onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          31: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@58c002ed onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          32: ASM: com.afunproject.dawncraft.integration.quests.FollowMeQuestEvents@505fbbed entityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          33: ASM: class com.simibubi.create.foundation.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          34: ASM: class com.simibubi.create.content.equipment.extendoGrip.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          35: ASM: class com.simibubi.create.content.equipment.armor.DivingHelmetItem breatheUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          36: ASM: class com.simibubi.create.content.equipment.armor.DivingBootsItem accellerateDescentUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          37: ASM: vazkii.quark.content.tools.module.ParrotEggsModule@5b5b83d0 entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          38: ASM: vazkii.quark.content.tweaks.module.VexesDieWithTheirMastersModule@45ee0bd8 checkWhetherAlreadyDead(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          39: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@16ef99ee onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          40: ASM: vazkii.quark.content.tweaks.module.PigLittersModule@6259253 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          41: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@4606ed0c onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          42: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@3d1b37ff onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          43: net.minecraftforge.eventbus.EventBus$$Lambda$1496/0x00007fb8746dc250@46c49e77
Minecraft    |          44: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@577009b7 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          45: ASM: net.joefoxe.hexerei.events.WitchArmorEvent@35902dad onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
Minecraft    |          46: net.minecraftforge.eventbus.EventBus$$Lambda$1496/0x00007fb8746dc250@29c7f89b
Minecraft    | java.lang.ArithmeticException
Minecraft    |
Minecraft    | >....Negative index in crash report handler (0/10)
[10:47:18] [Server thread/WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /218.155.71.164:55594
Minecraft    | net.minecraft.ReportedException: Ticking player
Minecraft    |  at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:krypton.mixins.json:shared.player.ServerPlayerEntityMixin,pl:mixin:APP:epicfight.mixins.json:MixinServerPlayer,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:207) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:wildbackport-common.mixins.json:network.ServerGamePacketListenerImplMixin,pl:mixin:APP:braincell.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:timeout_fixes.mixins.json:ServerPlayNetHandlerKeepAliveMixin,pl:mixin:APP:radium.mixins.json:entity.collisions.replace_streams.ServerPlayNetworkHandlerMixin,pl:mixin:APP:dragonmounts.mixins.json:EnsureSafeFlyingVehicleMixin,pl:mixin:APP:toofast.mixins.json:MixinServerNetPlayHandler,pl:mixin:APP:dannys_expansion.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.network.Connection.m_129483_(Connection.java:245) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:krypton.mixins.json:shared.network.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:krypton.mixins.json:shared.network.pipeline.encryption.ClientConnectionMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
Minecraft    |  at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:blueprint.mixins.json:DedicatedServerMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
Minecraft    |  at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23294!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:saturn.mixins.json:allocations.server_directory.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:A}
Minecraft    |  at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
Minecraft    | Caused by: java.lang.ArithmeticException
[10:47:18] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Aminimi1 lost connection: Internal server error
[10:47:18] [Server thread/INFO] [minecraft/DedicatedServer]: Aminimi1 left the game
```

**Comment by rolestack** [comment]
Also, when I moving an error occurs within a few to tens of seconds and there is a disconnect problem with the server.

Below is my server environment

- Container: itzg/minecraft-server:java17-jdk
- docker-compose.yaml
  ```
  version: "3"
  services:
    minecraft:
      image: itzg/minecraft-server:java17-jdk
      container_name: Minecraft
      tty: true
      stdin_open: true
      ports:
        - "25565:25565"
      environment:
        MODRINTH_DOWNLOAD_DEPENDENCIES: required
        TYPE: CURSEFORGE
        CF_SERVER_MOD: /serverpack/DawnCraft-2.0.3.zip"  <-- Official serverpack
        VERSION: 1.18.2
        EULA: "TRUE"
        MODE: "survival"
        PVP: "FALSE"
        MEMORY: ""
        JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
  ```

**Comment by Yesssssman** [comment]
Not an epic fight side issue.
