### ISSUE TITLE
Server error while trying to punch entities in battle mode

### ISSUE THREAD

**Issue by yuompioka** [Yesssssman/epicfightmod#160]
Forge Mod Loader version 14.23.5.2855
Latest Mohist 1.12.2 core
Mod version 2.1.3

Punching NPCs from Custom NPCs as well as vanilla mobs gives this error, damage is not dealt either, vanilla mobs, NPCs do not use battle mode:
```[net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at maninthehouse.epicfight.animation.types.ActionAnimation.onActivate(ActionAnimation.java:52) ~[ActionAnimation.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:35) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
	at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more

**Comment by yuompioka** [comment]
Fixed with new 2.2.0 version. You're awesome!
