### ISSUE TITLE
[Bug|Crash]: Incompatibility issue with Armourer Workshop in newest dev version [20.7.5]

### ISSUE THREAD

**Issue by Aurarobe** [Yesssssman/epicfightmod#1608]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Armourer Workshop

### Minecraft Version

1.20.1

### What happened?

The game crashes after a few seconds in world with error pointing at possibly a typo in the unreleased epic fight version:
Caused by: java.lang.NoSuchFieldError: lefrArm
	at yesman.epicfight.client.renderer.patched.entity.PatchedLivingEntityRenderer.md5e54bf$armourers_workshop$lambda$aw$init$6$0(PatchedLivingEntityRenderer.java:627) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at moe.plushie.armourers_workshop.core.armature.thirdparty.EpicFightModelHolder.lambda$createHolder$0(EpicFightModelHolder.java:56) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at moe.plushie.armourers_workshop.core.armature.thirdparty.EpicFightModelHolder.createHolder(EpicFightModelHolder.java:56) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at moe.plushie.armourers_workshop.core.armature.thirdparty.EpicFightModelHolder.of(EpicFightModelHolder.java:23) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at moe.plushie.armourers_workshop.init.client.EpicFlightWardrobeHandler.onPrepareModel(EpicFlightWardrobeHandler.java:94) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at yesman.epicfight.client.renderer.patched.entity.PatchedLivingEntityRenderer.aw$prepareModel(PatchedLivingEntityRenderer.java:581) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at yesman.epicfight.client.renderer.patched.entity.PatchedLivingEntityRenderer.md5e54bf$armourers_workshop$lambda$aw$init$4$2(PatchedLivingEntityRenderer.java:617) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at moe.plushie.armourers_workshop.init.platform.forge.NotificationCenterImpl.lambda$observer$1(NotificationCenterImpl.java:28) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at moe.plushie.armourers_workshop.init.platform.forge.NotificationCenterImpl.lambda$observer$2(NotificationCenterImpl.java:28) ~[armourersworkshop-forge-1.20.1-2.1.2.jar%23187!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at yesman.epicfight.client.renderer.patched.entity.PatchedLivingEntityRenderer.render(PatchedLivingEntityRenderer.java:73) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at yesman.epicfight.client.renderer.patched.entity.PatchedLivingEntityRenderer.render(PatchedLivingEntityRenderer.java:39) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at yesman.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:276) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at yesman.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:431) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at yesman.epicfight.client.events.engine.__Events_renderLivingEvent_Pre.invoke(.dynamic) ~[epicfight-20.7.5.jar%23201!/:20.7.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:18) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	... 22 more

full crash log:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14971420/latest.log)

**Comment by MetalKnight56** [comment]
And why are you trying to use a version that's not even released yet ??

**Comment by Aurarobe** [comment]
i wanted to test out the new mermod compat and accidentally ran into this issue so i thought i should report it incase it's overlooked before the update come out >.>

**Comment by Aurarobe** [comment]
it seems the issue is on Armourer's Workshop side, therefore i will close the issue: https://github.com/Armourers-Workshop/Armourers-Workshop/blob/ccf12d9bb4d51884951fc14fa2bca5cc56189768/versions/library/forge/src/main/java/moe/plushie/armourers_workshop/compatibility/forge/mixin/ForgeEpicFightRendererMixin.java#L127

**Comment by MetalKnight56** [comment]
> it seems the issue is on Armourer's Workshop side, therefore i will close the issue: https://github.com/Armourers-Workshop/Armourers-Workshop/blob/ccf12d9bb4d51884951fc14fa2bca5cc56189768/versions/library/forge/src/main/java/moe/plushie/armourers_workshop/compatibility/forge/mixin/ForgeEpicFightRendererMixin.java#L127

issues are only ever fixed after the update's launched. We fix the current standing issues with 20.7.4 and if new ones arrise in 20.7.5 we'll fix them in 20.7.6
