### ISSUE TITLE
ClassCastException: java.util.HashMap$Node cannot be cast to net.minecraft.world.entity.EntityType in EpicFight mod on Minecraft 1.19.2 server[Bug|Crash]: 

### ISSUE THREAD

**Issue by eerr992** [Yesssssman/epicfightmod#1669]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

You can enter without adding a data package, but if you add a data package, you will have invalid player data

[08:54:35 INFO]: Initializing Storage: 'file' (Type: FILE)
[08:54:35 INFO]: WebServer bound to: /[0:0:0:0:0:0:0:0]:8100
[08:54:35 WARN]: There are no valid maps configured, please check your map-configs! Disabling BlueMap...
[08:54:35 INFO]: WebServer started.
[08:55:22 INFO]: UUID of player HeedfulBear4835 is 7c845bb0-2e88-3b8a-b59f-33ec8ae9572a
[08:55:23 INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@72de5eb0
[08:55:23 ERROR]: Exception caught during firing event: class java.util.HashMap$Node cannot be cast to class net.minecraft.world.entity.EntityType (java.util.HashMap$Node is in module java.base of loader 'bootstrap'; net.minecraft.world.entity.EntityType is in module minecraft@1.19.2 of loader 'TRANSFORMER' @306c9b2c)
        Index: 5
        Listeners:
                0: NORMAL
                1: ASM: org.embeddedt.modernfix.forge.init.ModernFixForge@ccf05b2 onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                2: ASM: class immersive_aircraft.forge.ForgeBusEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                3: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@2c1e64eb
                4: ASM: net.mehvahdjukaar.moonlight.forge.MoonlightForge@6626c1f4 onDataSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                5: ASM: class yesman.epicfight.events.WorldEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@778d2f77
                7: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@f6ee64d
                8: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@ee65a40
                9: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@51805e4b
                10: net.minecraftforge.eventbus.EventBus$$Lambda/0x00000261dc787338@4f68359b
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class net.minecraft.world.entity.EntityType (java.util.HashMap$Node is in module java.base of loader 'bootstrap'; net.minecraft.world.entity.EntityType is in module minecraft@1.19.2 of loader 'TRANSFORMER' @306c9b2c)
        at TRANSFORMER/epicfight@19.5.24/yesman.epicfight.api.data.reloader.MobPatchReloadListener.lambda$getDataStream$3(MobPatchReloadListener.java:536)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at TRANSFORMER/epicfight@19.5.24/yesman.epicfight.events.WorldEvents.synchronizeWorldData(WorldEvents.java:95)
        at TRANSFORMER/epicfight@19.5.24/yesman.epicfight.events.WorldEvents.onDatapackSync(WorldEvents.java:51)
        at yesman.epicfight.events.__WorldEvents_onDatapackSync_OnDatapackSyncEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:318)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:298)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:197)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:181)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:168)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:78)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:253)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1136)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:327)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1057)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:894)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281)
        at java.base/java.lang.Thread.run(Thread.java:1583)

[08:55:23 ERROR]: Couldn't place player in world
java.lang.ClassCastException: class java.util.HashMap$Node cannot be cast to class net.minecraft.world.entity.EntityType (java.util.HashMap$Node is in module java.base of loader 'bootstrap'; net.minecraft.world.entity.EntityType is in module minecraft@1.19.2 of loader 'TRANSFORMER' @306c9b2c)
        at yesman.epicfight.api.data.reloader.MobPatchReloadListener.lambda$getDataStream$3(MobPatchReloadListener.java:536) ~[%5B史诗战斗%5D%20EpicFight-19.5.24.jar%23235!/:19.5.24]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at yesman.epicfight.events.WorldEvents.synchronizeWorldData(WorldEvents.java:95) ~[%5B史诗战斗%5D%20EpicFight-19.5.24.jar%23235!/:19.5.24]
        at yesman.epicfight.events.WorldEvents.onDatapackSync(WorldEvents.java:51) ~[%5B史诗战斗%5D%20EpicFight-19.5.24.jar%23235!/:19.5.24]
        at yesman.epicfight.events.__WorldEvents_onDatapackSync_OnDatapackSyncEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2369!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:318) ~[eventbus-6.0.5.jar%2369!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:298) ~[eventbus-6.0.5.jar%2369!/:?]
        at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:197) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:181) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:168) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:78) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.network.Connection.m_129483_(Connection.java:253) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1136) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:327) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1057) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:894) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.19.2-20220805.130853-srg.jar%23317!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Yesssssman** [comment]
This will be fixed in the next update.

**Comment by eerr992** [comment]
> 这将在下一次更新中修复。

I fixed this issue in Epic Fight Mod 19.5.25, which was a bug in Epic Fight Mod 19.5.24

**Comment by Yesssssman** [comment]
It has been fixed in 19.5.25
