### ISSUE TITLE
[Bug|Crash]: The server crashes because of ravager animations

### ISSUE THREAD

**Issue by Nurb78** [Yesssssman/epicfightmod#1698]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

Hello, I was playing a modpack with my friend yesterday in exaroton, we were fighting a pillager raid and then the server crashed when the ravager attacked me, idk why this is happening but I just noticed how immediately charged at me, I hope someone help me to fix this if there is a solution for it, Here's the crash report:

<html>
<body>

[12Jul2024 23:59:19.961] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
695 | Index: 3
696 | Listeners:
697 | 0: NORMAL
698 | 1: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@735173e1 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
699 | 2: ASM: class com.minecraftabnormals.abnormals_core.core.events.CompatEvents onUpdateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
700 | 3: ASM: class yesman.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
701 | 4: ASM: com.github.alexthe666.citadel.server.CitadelEvents@3e7fcbeb onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
702 | 5: ASM: com.github.alexthe666.citadel.server.CitadelEvents@3e7fcbeb onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
703 | 6: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@43f619bc onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
704 | 7: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@2149c3be
705 | 8: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@23777f08
706 | 9: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@a249589
707 | 10: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@13c09067
708 | 11: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@7b396d32 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
709 | 12: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@69b81499 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
710 | 13: ASM: vazkii.quark.content.world.module.BiotiteModule@4bfe12fc onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
711 | 14: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@7c7bf592
712 | 15: ASM: tschipp.carryon.common.event.ItemEvents@1e579ad2 dropNonHotbarItems(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
713 | 16: ASM: tschipp.carryon.common.event.ItemEntityEvents@5a557a0f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
714 | 17: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@189320a tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
715 | 18: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@6094f1df onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
716 | 19: LOWEST
717 | 20: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
718 | java.lang.NoSuchMethodError: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
719 | at yesman.epicfight.world.capabilities.entitypatch.mob.RavagerPatch.onHurtSomeone(RavagerPatch.java:62)
720 | at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:217)
721 | at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162)
722 | at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74)
723 | at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115)
724 | at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95)
725 | at net.minecraftforge.eventbus.ASMEventHandler_185_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
726 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
727 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
728 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
729 | at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326)
730 | at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114)
731 | at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
732 | at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612)
733 | at net.minecraft.world.World.func_217390_a(World.java:554)
734 | at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405)
735 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
736 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
737 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
738 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
739 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
740 | at java.lang.Thread.run(Thread.java:750)
741 |  
742 | [12Jul2024 23:59:19.969] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4593b5aa-c223-4401-a844-8ef7d19f93ad
743 | [12Jul2024 23:59:19.972] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
744 | net.minecraft.crash.ReportedException: Ticking entity
745 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
746 | at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
747 | at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
748 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
749 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
750 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
751 | Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
752 | at yesman.epicfight.world.capabilities.entitypatch.mob.RavagerPatch.onHurtSomeone(RavagerPatch.java:62) ~[epicfight:16.6.4]
753 | at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:217) ~[epicfight:16.6.4]
754 | at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[epicfight:16.6.4]
755 | at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[epicfight:16.6.4]
756 | at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[epicfight:16.6.4]
757 | at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[epicfight:16.6.4]
758 | at net.minecraftforge.eventbus.ASMEventHandler_185_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
759 | at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
760 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
761 | at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
762 | at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?]
763 | at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
764 | at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
765 | at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?]
766 | at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
767 | at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?]
768 | at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
769 | ... 5 more
770 | [12Jul2024 23:59:19.976] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /server/./crash-reports/crash-2024-07-12_23.59.19-server.txt
771 | [12Jul2024 23:59:19.976] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
772 | [12Jul2024 23:59:19.977] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
773 | [12Jul2024 23:59:20.027] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Le_Lighting_Rod lost connection: Server closed
774 | [12Jul2024 23:59:20.028] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Le_Lighting_Rod left the game
775 | [12Jul2024 23:59:20.029] [Server thread/INFO] [com.alrex.parcool.ParCool/]: Limitation of c4e24e4a-d453-3e74-a451-4fbfc9f1e86e was unloaded
776 | [12Jul2024 23:59:20.070] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
777 | java.lang.IllegalStateException: Removing entity while ticking!
778 | at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:950) ~[?:?]
779 | at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:971) ~[?:?]
780 | at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:967) ~[?:?]
781 | at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:339) ~[?:?]
782 | at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1021) ~[?:?]
783 | at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366) ~[?:?]
784 | at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213167_f(SourceFile:79) ~[?:?]
785 | at net.minecraft.network.play.ServerPlayNetHandler.func_194028_b(ServerPlayNetHandler.java:296) ~[?:?]
786 | at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:742) ~[?:?]
787 | at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:557) ~[?:?]
788 | at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
789 | at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
790 | at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
791 | at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
792 | [12Jul2024 23:59:20.443] [Server thread/INFO] [net.minecraft.network.rcon.RConThread/]: Thread Query Listener stopped
793

<br class="Apple-interchange-newline">
</body>
</html>[12Jul2024 23:59:19.961] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@735173e1 onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: class com.minecraftabnormals.abnormals_core.core.events.CompatEvents onUpdateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		3: ASM: class yesman.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		4: ASM: com.github.alexthe666.citadel.server.CitadelEvents@3e7fcbeb onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		5: ASM: com.github.alexthe666.citadel.server.CitadelEvents@3e7fcbeb onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		6: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@43f619bc onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@2149c3be
		8: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@23777f08
		9: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@a249589
		10: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@13c09067
		11: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@7b396d32 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		12: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@69b81499 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		13: ASM: vazkii.quark.content.world.module.BiotiteModule@4bfe12fc onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		14: net.minecraftforge.eventbus.EventBus$$Lambda$2686/939878311@7c7bf592
		15: ASM: tschipp.carryon.common.event.ItemEvents@1e579ad2 dropNonHotbarItems(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		16: ASM: tschipp.carryon.common.event.ItemEntityEvents@5a557a0f onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		17: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@189320a tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		18: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@6094f1df onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		19: LOWEST
		20: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NoSuchMethodError: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
	at yesman.epicfight.world.capabilities.entitypatch.mob.RavagerPatch.onHurtSomeone(RavagerPatch.java:62)
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:217)
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162)
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74)
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115)
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95)
	at net.minecraftforge.eventbus.ASMEventHandler_185_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326)
	at net.minecraft.entity.LivingEntity.func_[700](https://exaroton.com/log/#L700)71_h_(LivingEntity.java:2114)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:750)

[12Jul2024 23:59:19.969] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4593b5aa-c223-4401-a844-8ef7d19f93ad
[12Jul2024 23:59:19.972] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.monster.RavagerEntity.func_213684_dX()I
	at yesman.epicfight.world.capabilities.entitypatch.mob.RavagerPatch.onHurtSomeone(RavagerPatch.java:62) ~[epicfight:16.6.4]
	at yesman.epicfight.api.animation.types.AttackAnimation.hurtCollidingEntities(AttackAnimation.java:217) ~[epicfight:16.6.4]
	at yesman.epicfight.api.animation.types.AttackAnimation.tick(AttackAnimation.java:162) ~[epicfight:16.6.4]
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:74) ~[epicfight:16.6.4]
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:115) ~[epicfight:16.6.4]
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:95) ~[epicfight:16.6.4]
	at net.minecraftforge.eventbus.ASMEventHandler_185_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:612) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:405) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_[711](https://exaroton.com/log/#L711)90_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
[12Jul2024 23:59:19.976] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /server/./crash-reports/crash-2024-07-12_23.59.19-server.txt
[12Jul2024 23:59:19.976] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[12Jul2024 23:59:19.977] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[12Jul2024 23:59:20.027] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: Le_Lighting_Rod lost connection: Server closed
[12Jul2024 23:59:20.028] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Le_Lighting_Rod left the game
[12Jul2024 23:59:20.029] [Server thread/INFO] [com.alrex.parcool.ParCool/]: Limitation of c4e24e4a-d453-3e74-a451-4fbfc9f1e86e was unloaded
[12Jul2024 23:59:20.070] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.world.server.ServerWorld.removeEntity(ServerWorld.java:950) ~[?:?]
	at net.minecraft.world.server.ServerWorld.removePlayer(ServerWorld.java:971) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217434_e(ServerWorld.java:967) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:339) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1021) ~[?:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213167_f(SourceFile:79) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_194028_b(ServerPlayNetHandler.java:296) ~[?:?]
	at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:742) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_[712](https://exaroton.com/log/#L712)60_j(MinecraftServer.java:557) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:514) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
[12Jul2024 23:59:20.443] [Server thread/INFO] [net.minecraft.network.rcon.RConThread/]: Thread Query Listener stopped

**Comment by Yesssssman** [comment]
Sorry, but we do not support 1.16.5 anymore. It seems like there are version mismatches between Minecraft and Forge.

**Comment by Nurb78** [comment]
> Sorry, but we do not support 1.16.5 anymore. It seems like there are version mismatches between Minecraft and Forge.

But there's is not a way I can solve this? I'm not a programmer to understand why is even crashing, so please, can you tell me what is happening?
