### ISSUE TITLE
[Bug|Crash]: Cannot invoke "yesman.epicfight.client.ClientEngine.isBattleMode()" because the return value of "yesman.epicfight.client.ClientEngine.getInstance()" is null

### ISSUE THREAD

**Issue by ZekerZhayard** [Yesssssman/epicfightmod#1699]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-14 19:37:37
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "yesman.epicfight.client.ClientEngine.isBattleMode()" because the return value of "yesman.epicfight.client.ClientEngine.getInstance()" is null
	at yesman.epicfight.client.input.CombatKeyMapping.isActiveAndMatches(CombatKeyMapping.java:18) ~[EpicFight-20.7.4.jar%23189!/:20.7.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.settings.KeyMappingLookup.getAll(KeyMappingLookup.java:75) ~[forge-1.20.1-47.3.1-universal.jar%23207!/:?] {re:classloading}
	at net.minecraft.client.KeyMapping.m_90837_(KeyMapping.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kuma_api.mixins.json:KeyMappingAccessor,pl:mixin:APP:balm.mixins.json:KeyMappingAccessor,pl:mixin:APP:balm.mixins.json:KeyMappingMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:422) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:462) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:461) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading,re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading,re:mixin}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Epic Fight (epicfight), Version: 20.7.4
		at TRANSFORMER/epicfight@20.7.4/yesman.epicfight.client.input.CombatKeyMapping.isActiveAndMatches(CombatKeyMapping.java:18)
Stacktrace:
	at yesman.epicfight.client.input.CombatKeyMapping.isActiveAndMatches(CombatKeyMapping.java:18) ~[EpicFight-20.7.4.jar%23189!/:20.7.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.settings.KeyMappingLookup.getAll(KeyMappingLookup.java:75) ~[forge-1.20.1-47.3.1-universal.jar%23207!/:?] {re:classloading}
	at net.minecraft.client.KeyMapping.m_90837_(KeyMapping.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kuma_api.mixins.json:KeyMappingAccessor,pl:mixin:APP:balm.mixins.json:KeyMappingAccessor,pl:mixin:APP:balm.mixins.json:KeyMappingMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:422) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:462) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:461) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicfight.mixins.json:MixinKeyboardHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading,re:mixin}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading,re:mixin}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources, programmer_art, builtin/builtin_resource_packs/legacy_dead_king_resource_pack
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23202!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.11, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 1229235456 bytes (1172 MiB) / 2281701376 bytes (2176 MiB) up to 8422162432 bytes (8032 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3ea0
	Graphics card #0 versionInfo: DriverVersion=26.20.100.7985
	Graphics card #1 name: NVIDIA GeForce MX250
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d13
	Graphics card #1 versionInfo: DriverVersion=26.21.14.4223
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 14405.74
	Virtual memory used (MB): 11253.17
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 761.16
	JVM Flags: 11 total; -Xmx8005m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7985, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources, programmer_art, builtin/builtin_resource_packs/legacy_dead_king_resource_pack
	Current Language: zh_cn
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mowziesmobs-1.6.5.jar                             |Mowzie's Mobs                 |mowziesmobs                   |1.6.4               |SIDED_SETU|Manifest: NOSIGNATURE
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.7.jar                   |GeckoLib 4                    |geckolib                      |4.4.7               |SIDED_SETU|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.4.0.9.jar                     |Just Enough Items             |jei                           |15.4.0.9            |SIDED_SETU|Manifest: NOSIGNATURE
		lithostitched-forge-1.20.1-1.1.6.jar              |Lithostitched                 |lithostitched                 |1.1.5               |SIDED_SETU|Manifest: NOSIGNATURE
		caelus-forge-3.2.0+1.20.1.jar                     |Caelus API                    |caelus                        |3.2.0+1.20.1        |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |SIDED_SETU|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.4.jar                   |Waystones                     |waystones                     |14.1.4              |SIDED_SETU|Manifest: NOSIGNATURE
		The-Man-From-The-Fog-1.3-1.20.1.jar               |The Man From The Fog          |man                           |1.3                 |SIDED_SETU|Manifest: NOSIGNATURE
		EpicFight-20.7.4.jar                              |Epic Fight                    |epicfight                     |20.7.4              |SIDED_SETU|Manifest: NOSIGNATURE
		WeaponsOfMiracles-20.1.7.40.jar                   |Weapons of Minecraft          |wom                           |20.1.7.40           |SIDED_SETU|Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.23-forge.jar                |Journeymap                    |journeymap                    |5.9.23              |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
		alexscaves-1.1.4.jar                              |Alex's Caves                  |alexscaves                    |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		artifacts-forge-9.5.11.jar                        |Artifacts                     |artifacts                     |9.5.11              |SIDED_SETU|Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.2.1.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.2.1        |SIDED_SETU|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |SIDED_SETU|Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |SIDED_SETU|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |SIDED_SETU|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.3.6-all.jar                   |Balm                          |balm                          |7.3.6               |SIDED_SETU|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.1-universal.jar                 |Forge                         |forge                         |47.3.1              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[Forge]CTOV-v3.4.5.jar                            |ChoiceTheorem's Overhauled Vil|ctov                          |3.4.5               |SIDED_SETU|Manifest: NOSIGNATURE
		expandability-forge-9.0.4.jar                     |ExpandAbility                 |expandability                 |9.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.2508-universal.jar      |The Twilight Forest           |twilightforest                |4.3.2508            |SIDED_SETU|Manifest: NOSIGNATURE
		epicpaladins-0.1.1-1.20.1-forge.jar               |Epic Paladins                 |epicpaladins                  |0.1.1-1.20.1-forge  |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: f978d9c8-f97b-4a71-912a-1837f3b03c74
	FML: 47.3
	Forge: net.minecraftforge:47.3.1
```

**Comment by Yesssssman** [comment]
Is this random?

**Comment by ilikegamba** [comment]
Hi have you solved this im facing the same issue

**Comment by IamTomgamer** [comment]
i'm also having this issue with:
minecraft 1.20.1 forge 47.4.9
mods:
EMF, ETF, Alshanex's Familiars, Architectury API, Balm, Born in Chaos, Butchery, Caelus, Cloth Config API, Curios API, EasyNPC, EasyNPC - Epic Fight, EFM Extended, EFM Fixes, Epic Compat: Parcool, Epic Fight, Fzzy Config, Geckolib, Gravestone Mod, Hardcore Revival, Identity Fix (Morph), Iron's spells & spellbooks, Kotlin for Forge, Mutant Mobs, Nyf's spiders, Parcool, PlayerAnimator, Pufferfish's skills, Pufferfish's Attributes, Pufferfish's Unofficial Additions, Puzzles Lib, Simple Health Bar, Simple Voice Chat, Simply Swords, Solid Mobs, SuperMartijn642's Config Lib, Waystones

[Modrinth Modpack.zip](https://github.com/user-attachments/files/23354562/Modrinth.Modpack.zip)
