### ISSUE TITLE
Crash when mobs spawn

### ISSUE THREAD

**Issue by Kurojime** [Yesssssman/epicfightmod#171]
I could only deduce that it happens due to a mob as it played fine when in Peaceful but when switched to Normal, it crashes

[crash-2021-04-11_11.01.32-server.txt](https://github.com/Yesssssman/epicfightmod/files/6291202/crash-2021-04-11_11.01.32-server.txt)

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/11/21 11:01 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:58) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:72) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:44) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:29) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:22) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:76) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_935_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2552/960281601.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$13442/2025240799.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.ServerChunkManagerMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$12352/1596534571.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.ServerChunkManagerMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:alloc.chunk_ticking.ServerChunkManagerMixin,pl:mixin:APP:sodium.mixins.json:world.chunk_access.ServerChunkManagerMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:coremod,pl:mixin:APP:sodium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:alloc.world_ticking.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:sodium.mixins.json:world.tick_scheduler.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$11560/1501606800.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by koderian** [comment]
Same issue #72 and #64
