### ISSUE TITLE
Hard crashing, using no mods besides optifine and journeymap

### ISSUE THREAD

**Issue by InviteKnight** [Yesssssman/epicfightmod#185]
I never really learned how to understand crash reports, but this is what it's been saying for me: 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maninhouse.epicfight.capabilities.entity.projectile.CapabilityProjectile.onJoinWorld(CapabilityProjectile.java:34) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:88) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_38_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2575/313184147.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_82196_d(AbstractSkeletonEntity.java:184) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4}
	at maninhouse.epicfight.entity.ai.ArcherGoal.func_75246_d(ArcherGoal.java:157) ~[?:1.0] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(GoalSelector.java:136) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.AbstractSkeletonEntity.func_70636_d(AbstractSkeletonEntity.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:bows.5,xf:fml:forge:bows.4}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$6078/734222817.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.entity.monster.SkeletonEntity)
	Entity ID: 2089
	Entity Name: Skeleton
	Entity's Exact location: 587.51, 65.00, 1827.76
	Entity's Block location: World: (587,65,1827), Chunk: (at 11,4,3 in 36,114; contains blocks 576,0,1824 to 591,255,1839), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
	Entity's Momentum: 0.00, -0.08, 0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Erodus'/161, l='ServerLevel[Drehmal v2.1.1 PRIMORDIAL]', x=514.10, y=67.00, z=1852.40]]
	Chunk stats: ServerChunkCache: 8966
	Level dimension: minecraft:overworld
	Level spawn location: World: (26461,215,-302), Chunk: (at 13,13,2 in 1653,-19; contains blocks 26448,0,-304 to 26463,255,-289), Region: (51,-1; contains chunks 1632,-32 to 1663,-1, blocks 26112,0,-512 to 26623,255,-1)
	Level time: 176571693 game time, 38448 day time
	Level name: Drehmal v2.1.1 PRIMORDIAL
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: vanilla, fabric, forge, Spigot, Paper
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5701/182130143.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

**Comment by ethanp919** [comment]
The newest update is hard crashing for me as well when shooting an arrow at any mob. I rolled back to the previous update and have no issues so it's definitely something in the current build.

**Comment by Yesssssman** [comment]
Ok. I'll upload a fixed version as soon as possible.
