### ISSUE TITLE
Damage player-to-player server issue (fatal error)

### ISSUE THREAD

**Issue by yuompioka** [Yesssssman/epicfightmod#186]
Forge Mod Loader version 14.23.5.2855
Latest Mohist 1.12.2 core
Mod version 2.2.0

Error occurs when I try to punch another player with fist/weapon. Average animations work, but punch and punch with weapons animations don't play. Punching mobs, NPCs from Custom NPCs works as intended for both players (featuring [this issue](https://github.com/Yesssssman/epicfightmod/issues/160))

```
[11:41:45 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
        at maninthehouse.epicfight.animation.types.ActionAnimation.onActivate(ActionAnimation.java:52) ~[ActionAnimation.class:?]
        at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:35) ~[AnimatorServer.class:?]
        at maninthehouse.epicfight.animation.AnimatorServer.playAnimation(AnimatorServer.java:27) ~[AnimatorServer.class:?]
        at maninthehouse.epicfight.network.client.CTSPlayAnimation$Handler.lambda$onMessage$0(CTSPlayAnimation.java:69) ~[CTSPlayAnimation$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

**Comment by Yesssssman** [comment]
Are there any other mods?

**Comment by yuompioka** [comment]
Here's the list
![image](https://user-images.githubusercontent.com/82111626/115148769-ca3df380-a069-11eb-8757-2430e29479ad.png)
Should I trying removing all of them to find whether it's incompatibility or mod problem?

**Comment by Yesssssman** [comment]
Yeah, It's very helpful if you find which mod has incompatibility with mine.
