### ISSUE TITLE
[Bug|Crash]: Custom weapon Datapack Crash, and other datapack editor problems

### ISSUE THREAD

**Issue by TrollLikesPizza** [Yesssssman/epicfightmod#1861]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When using "epicfight-forge-20.9.5-1.20.1.jar" and in Minecraft using "Soul Snatch" ability on a custom weapon, the game crashes.
The Custom weapon I'm using is from mod "Simple Swords"(Caelestis) but i tried it with other weapons from other mods and the case was the same, and it worked before but it hadn't had any animation (sword from the ground animation)
The same problem appears with "Demonic Ascension" ability on a custom weapon.
Particle hit effect form solar animations can't be overwrite by other hit effects like "epicfight.cut"

Another problem that i found is: When a weapon has "animation change"(like when you are below certain amount of health you change fighting style and statistics like damage) it only refreshes when you change inventory slots.

I put the datapack that im making in "steps to reproduce"

Crash Report:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-11-18 18:43:10
Description: Ticking player

java.lang.NoSuchMethodError: 'void yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.modifyLivingMotionByCurrentItem()'
	at reascer.wom.skill.weaponinnate.SoulSnatchSkill.lambda$onInitiate$3(SoulSnatchSkill.java:150) ~[WeaponsOfMiracles-20.1.8.5.2.jar%23176!/:20.1.8.5.2] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.end(AttackAnimation.java:178) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at reascer.wom.animation.attacks.BasicMultipleAttackAnimation.end(BasicMultipleAttackAnimation.java:321) ~[WeaponsOfMiracles-20.1.8.5.2.jar%23176!/:20.1.8.5.2] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:71) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:149) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:248) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:113) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:103) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.events.__EntityEvents_updateEvent_LivingTickEvent.invoke(.dynamic) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.20.1-47.3.0-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinPlayer,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simplyswords-common.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinServerGamePacketListenerImpl,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Weapons of miracle (wom), Version: 20.1.8.5.2
		Issue tracker URL: https://github.com/Reascer/WeaponsOfMinecraft/issues
		at TRANSFORMER/wom@20.1.8.5.2/reascer.wom.skill.weaponinnate.SoulSnatchSkill.lambda$onInitiate$3(SoulSnatchSkill.java:150)

	Epic Fight (epicfight), Version: 20.9.5
		Issue tracker URL: https://github.com/Yesssssman/epicfightmod/issues
		at TRANSFORMER/epicfight@20.9.5/yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22)
Stacktrace:
	at reascer.wom.skill.weaponinnate.SoulSnatchSkill.lambda$onInitiate$3(SoulSnatchSkill.java:150) ~[WeaponsOfMiracles-20.1.8.5.2.jar%23176!/:20.1.8.5.2] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:22) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.world.entity.eventlistener.PlayerEventListener.triggerEvents(PlayerEventListener.java:73) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.api.animation.types.AttackAnimation.end(AttackAnimation.java:178) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at reascer.wom.animation.attacks.BasicMultipleAttackAnimation.end(BasicMultipleAttackAnimation.java:321) ~[WeaponsOfMiracles-20.1.8.5.2.jar%23176!/:20.1.8.5.2] {re:classloading}
	at yesman.epicfight.api.animation.ServerAnimator.tick(ServerAnimator.java:71) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.tick(LivingEntityPatch.java:149) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.tick(PlayerPatch.java:248) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.tick(ServerPlayerPatch.java:113) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:mixin,re:classloading}
	at yesman.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:103) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading}
	at yesman.epicfight.events.__EntityEvents_updateEvent_LivingTickEvent.invoke(.dynamic) ~[epicfight-forge-20.9.5-1.20.1.jar%23169!/:20.9.5] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264) ~[forge-1.20.1-47.3.0-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinPlayer,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 184
	Entity Name: TrolLikesPizza
	Entity's Exact location: 39.15, 72.00, -75.14
	Entity's Block location: World: (39,72,-76), Section: (at 7,8,4 in 2,4,-5; chunk contains blocks 32,-64,-80 to 47,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:simplyswords-common.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.epicfight.json:MixinServerGamePacketListenerImpl,pl:mixin:A}
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23178!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.13, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1811598984 bytes (1727 MiB) / 2600468480 bytes (2480 MiB) up to 6308233216 bytes (6016 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 2
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5333
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Virtual memory max (MB): 21469.51
	Virtual memory used (MB): 15228.39
	Swap memory total (MB): 5346.72
	Swap memory used (MB): 1012.16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6016m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['TrolLikesPizza'/184, l='ServerLevel[New Worldytwestyessman fix]', x=39.15, y=72.00, z=-75.14]]
	Data Packs: vanilla, mod:knights, mod:forge, mod:mobbattle (incompatible), mod:epicfight, mod:wom (incompatible), file/knightforwk.zip, mod:wukong (incompatible), mod:geckolib, mod:architectury (incompatible), mod:cloth_config (incompatible), mod:simplyswords (incompatible), mod:falchionmoveset, mod:refm
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		knights_1.20.1_5.3.jar                            |knights                       |knights                       |2.2.0               |DONE      |Manifest: NOSIGNATURE
		wukong-forge1.20.1-20.0.1.11.jar                  |Epic Fight - Wukong Moveset   |wukong                        |20.0.1.11           |DONE      |Manifest: NOSIGNATURE
		mobbattle-1.20.1-2.4.9-forge.jar                  |Mob Battle Mod                |mobbattle                     |1.20.1-2.4.9        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.9.jar                   |GeckoLib 4                    |geckolib                      |4.4.9               |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.136-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.136            |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.56.0-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.56.0-1.20.1       |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		falchionmoveset-20.8.2.jar                        |falchion moveset              |falchionmoveset               |20.8.2              |DONE      |Manifest: NOSIGNATURE
		epicfight-forge-20.9.5-1.20.1.jar                 |Epic Fight                    |epicfight                     |20.9.5              |DONE      |Manifest: NOSIGNATURE
		refm-0.2.0-1.20.1.jar                             |Rapier For EpicFightMod       |refm                          |0.2                 |DONE      |Manifest: NOSIGNATURE
		WeaponsOfMiracles-20.1.8.5.2.jar                  |Weapons of miracle            |wom                           |20.1.8.5.2          |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4aef4c9c-058d-4926-84e5-18e75719f0be
	FML: 47.3
	Forge: net.minecraftforge:47.3.0
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\troll\AppData\Roaming\PrismLauncher\instances\Epic fight MOdpack c2 tst\.minecraft\crash-reports\crash-2024-11-18_18.43.10-server.txt
[18:43:11] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New Worldytwestyessman fix]'/minecraft:overworld
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New Worldytwestyessman fix]'/minecraft:the_end
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[New Worldytwestyessman fix]'/minecraft:the_nether
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (New Worldytwestyessman fix): All chunks are saved
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:43:12] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
Process exited with code -1.

### Steps to Reproduce

[earthtestt.zip](https://github.com/user-attachments/files/17604570/earthtestt.zip)

**Comment by Yesssssman** [comment]
Please provide crash repo

**Comment by Yesssssman** [comment]
Update wom version 20.1.8.5.5 or over

**Comment by HaktyGaona** [comment]
> Update wom version 20.1.8.5.5 or over

> Particle hit effect form solar animations can't be overwrite by other hit effects like "epicfight.cut"

Is it not within the repair plan that some hit particles and sound cannot be replaced?
Only appearing in some WOM animations.

**Comment by guivnf** [comment]
> Is it not within the repair plan that some hit particles and sound cannot be replaced? Only appearing in some WOM animations.

Wom is a different project than epic fight, you may request that fix to the WOM dev.
