### ISSUE TITLE
[Bug|Crash]: Cant load into personal dedicated server after adding epic fight

### ISSUE THREAD

**Issue by Dinksy39** [Yesssssman/epicfightmod#1885]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

dedicated server runs fine, when me or any of my friends try to load in, it reaches "Loading Terrain" then it blackscreens for a second and crashes, this is a part of the crash report:

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class net.minecraft.world.entity.decoration.ArmorStand (net.minecraft.client.player.LocalPlayer and net.minecraft.world.entity.decoration.ArmorStand are in module minecraft@1.20.1 of loader 'TRANSFORMER' @67c020c8)

```
-- Head --
Thread: Render thread
Suspected Mods: 
	Oculus (oculus), Version: 1.7.0
		Issue tracker URL: https://github.com/Asek3/Oculus/issues
		at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.pathways.HandRenderer.renderSolid(HandRenderer.java:96)

	Epic Fight (epicfight), Version: 20.9.6
		Issue tracker URL: https://github.com/Yesssssman/epicfightmod/issues
		at TRANSFORMER/epicfight@20.9.6/yesman.epicfight.client.renderer.patched.layer.WearableItemLayer.renderLayer(WearableItemLayer.java:160)
```
		
Here is the full crash report:
[crash-2024-11-30_12.00.13-client.txt](https://github.com/user-attachments/files/17966814/crash-2024-11-30_12.00.13-client.txt)

### Steps to Reproduce

im using bettermc modpack with some personal mod additions:
![image](https://github.com/user-attachments/assets/0acd1eaa-a6a7-461f-a83b-105f0790082e)
all the mods highlighted are the ones i personally added, they all work until I add EpicFight.

**Comment by Sebas2K25** [comment]
The exact same thing happens to me, and with the same modpack, I deleted the oculus and still the same thing happens to me

**Comment by d1ew** [comment]
Same here.. everything is fine until I add epic fight. I was able to use it for awhile and it only occasionally caused crashing. Now I immediately crash if I try to join my server with it added.

**Comment by itsdeadfrosty** [comment]
[crash-2025-01-24_20.58.08-client.txt](https://github.com/user-attachments/files/18544646/crash-2025-01-24_20.58.08-client.txt)

something about armor stand rendering for me. epic fight feels so clunky in larger modpacks when its code is put to the test it always is a problem.

**Comment by Yesssssman** [comment]
Classified as bclib/ better nether & better end. I can't fix much things from Fabric & Sinytra connector.
