### ISSUE TITLE
ERROR MAGMA/MOHIST SERVERS SPIGOT/FORGE GRASH 1.12.2

### ISSUE THREAD

**Issue by WerelWolf** [Yesssssman/epicfightmod#192]
Hey man help me I am having problems with your mod on my rpg server, it is having some conflict I will send the logs for you to check 
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6332650/latest.log)

**Comment by WerelWolf** [comment]
it consists of shutting down the server automatically after relogging on the server with any sword in hand, it gets worse when you leave the server with Katana, in addition he is incompatible with the quark and even taking out the quark he still has the same problem

**Comment by WerelWolf** [comment]
VERSION 1.12.2 - 2.2.0

**Comment by WerelWolf** [comment]
could you create a discord?

**Comment by WerelWolf** [comment]
[22:41:54] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEquipmentChangeEvent@174ded05:
 java.lang.NullPointerException: null
        at maninthehouse.epicfight.skill.KatanaPassive.onInitiate(KatanaPassive.java:29) ~[KatanaPassive.class:?]
        at maninthehouse.epicfight.skill.SkillContainer.setSkill(SkillContainer.java:40) ~[SkillContainer.class:?]
        at maninthehouse.epicfight.capabilities.item.CapabilityItem.onHeld(CapabilityItem.java:140) ~[CapabilityItem.class:?]
        at maninthehouse.epicfight.capabilities.entity.player.ServerPlayerData.onHeldItemChange(ServerPlayerData.java:87) ~[ServerPlayerData.class:?]
        at maninthehouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:282) ~[EntityEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:48ec0a1]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:48ec0a1]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2470) [vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:253) [aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482) [oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:253) [pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:48ec0a1]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:193) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[22:41:54] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[22:41:54] [Server thread/ERROR] [FML]: 0: NORMAL
[22:41:54] [Server thread/ERROR] [FML]: 1: ASM: class maninthehouse.epicfight.events.EntityEvents equipChangeEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
[22:41:54] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /192.168.0.105:59943
 net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:575) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:253) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:48ec0a1]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:193) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException
        at maninthehouse.epicfight.skill.KatanaPassive.onInitiate(KatanaPassive.java:29) ~[KatanaPassive.class:?]
        at maninthehouse.epicfight.skill.SkillContainer.setSkill(SkillContainer.java:40) ~[SkillContainer.class:?]
        at maninthehouse.epicfight.capabilities.item.CapabilityItem.onHeld(CapabilityItem.java:140) ~[CapabilityItem.class:?]
        at maninthehouse.epicfight.capabilities.entity.player.ServerPlayerData.onHeldItemChange(ServerPlayerData.java:87) ~[ServerPlayerData.class:?]
        at maninthehouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:282) ~[EntityEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:48ec0a1]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:48ec0a1]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2470) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:253) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482) ~[oq.class:?]
        ... 9 more

**Comment by imkappa** [comment]
a little bit similar thing happening to me, im not having a crash but sometimes attack mode bugs and it makes this unplayable. For ex. sometimes when u open the attacking mode it brokes and sounds are not coming when u attack. Not just sounds, it brokes the attack too. If this happens u can not deal damage to anybody or any mob. (sorry for bad English)

**Comment by imkappa** [comment]
and yeah the same thing is happening too but not crash just messes with the player data

**Comment by imkappa** [comment]
same thing is happening to me right now, if u find a solution pls tell me
