### ISSUE TITLE
Dispenser arrow hitting player crash game

### ISSUE THREAD

**Issue by HecateII** [Yesssssman/epicfightmod#208]
[23apr2021 08:03:47.934] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: **Exception caught during firing event: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity**
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class maninhouse.epicfight.events.EntityEvents hurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
java.lang.ClassCastException: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
	at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193)
	at net.minecraftforge.eventbus.ASMEventHandler_123_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2592/142991595.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362)
	at net.minecraft.entity.player.PlayerEntity.func_70665_d(PlayerEntity.java:871)
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984)
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814)
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326)
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
	at net.minecraft.world.server.ServerWorld$$Lambda$7156/1149501198.accept(Unknown Source)
	at net.minecraft.world.World.func_217390_a(World.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$6468/1680568790.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[23apr2021 08:03:47.937] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7cd34b9e-0238-4aae-aacb-e49a6572a91a
[23apr2021 08:03:47.940] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6468/1680568790.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassCastException: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
	at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_123_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2592/142991595.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70665_d(PlayerEntity.java:871) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70097_a(PlayerEntity.java:814) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_70097_a(ServerPlayerEntity.java:597) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?]
	at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?]
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?]
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$7156/1149501198.accept(Unknown Source) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by redstonerblast** [comment]
[BUMP], This needs to be fixed ASAP as it prevents this from being used in packs with more structures, or packs based on Adventure.
