### ISSUE TITLE
[Minecraft 1.16.5, EF mod 2.0.3] Crash while walking and joining world in a modpack 

### ISSUE THREAD

**Issue by Agno1a** [Yesssssman/epicfightmod#25]
I've had a total of three crashes while trying to load Epic Fight Mod, and I will just send the last one because it is the one I am most sure about and it is the best run I had so far. (I was able to load the world in the lastest attempt, but it crashed shortly after I started walking).

---- Minecraft Crash Report ----
// Don't do that.

Time: 2/24/21 11:42 PM
Description: Exception in server tick loop

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:1.8.0_241] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(ServerChunkProvider.java:514) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(ServerChunkProvider.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(ServerChunkProvider.java:267) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:722) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:150) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}
Caused by: java.lang.NullPointerException
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:57) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:75) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:49) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:79) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_456_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_217440_f(ServerWorld.java:829) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:763) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {}
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1037370568 bytes (989 MB) / 3213778944 bytes (3064 MB) up to 4242669568 bytes (4046 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128m -Xmx4096m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.42-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.42-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.42-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.42-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.42-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.42
	FML Language Providers: 
		javafml@36.0
		minecraft@1
		kotlinforforge@1.9.0
	Mod List: 
		DungeonsMod-1.16.3-1.2.10.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.2.10       |DONE      |NOSIGNATURE
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar          |Bountiful Baubles             |bountifulbaubles              |NONE                |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		goblintraders-1.2.2-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.2.2               |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
		EpicFightMod-1.16.4-2.0.3.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		comforts-forge-1.16.4-4.0.1.0.jar                 |Comforts                      |comforts                      |1.16.4-4.0.1.0      |DONE      |NOSIGNATURE
		citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |DONE      |NOSIGNATURE
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.4-1.1.10.jar                  |Guard Villagers               |guardvillagers                |1.1.10              |DONE      |NOSIGNATURE
		RealisticTorches-1.16.5-3.1.2.jar                 |Realistic Torches             |realistictorches              |1.16.5-3.1.2        |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		mahoutsukai-1.16.5-v1.28.0.jar                    |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.28.0      |DONE      |NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |NOSIGNATURE
		mysticalworld-1.16.4-0.3.1.8.jar                  |Mystical World                |mysticalworld                 |1.16.4-0.3.1.8      |DONE      |NOSIGNATURE
		firstaid-1.9.5.jar                                |First Aid                     |firstaid                      |1.9.5               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.42-universal.jar                |Forge                         |forge                         |36.0.42             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		[1.16.X-1.0.10]+Dragon+Mounts+Legacy.jar          |Dragon Mounts: Legacy         |dragonmounts                  |1.0.10              |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.4.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.4.1        |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.9.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.9      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE
		antiqueatlas-5.4.4-forge.jar                      |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		dungeonsarise1.16.4-1.2.61a.jar                   |Dungeons Arise                |dungeons_arise                |1.2.61a             |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.42-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		repurposed_structures-1.16.5-2.4.1.jar            |Repurposed Structures         |repurposed_structures         |1.16.5-2.4.1        |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.2.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.2               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |DONE      |NOSIGNATURE
		roughtweaks-1.16.5-2.2.2.jar                      |Rough Tweaks                  |roughtweaks                   |2.2.2               |DONE      |NOSIGNATURE
		SilentLib-1.16.3-4.9.1+64.jar                     |Silent Lib                    |silentlib                     |4.9.1+64            |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.3.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.3               |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		notreepunching-forge-1.16.5-4.1.2.jar             |No Tree Punching              |notreepunching                |4.1.2               |DONE      |NOSIGNATURE
		Bountiful-1.16.4-3.3.0.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.0        |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.4.0.jar                   |Curios API                    |curios                        |1.16.5-4.0.4.0      |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |DONE      |NOSIGNATURE
		Hardcore+Battle+Towers+4.2.3.1.jar                | Harcore Battle Towers 4.2.3  |hardcorebattletowers          |4.2.3               |DONE      |NOSIGNATURE
		structurize-0.13.135-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.135-ALPHA      |DONE      |NOSIGNATURE
		minecolonies-0.13.629-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.13.629-ALPHA      |DONE      |NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-3.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 3        |DONE      |NOSIGNATURE
		Project_MMO-1.16.4-3.44.3.jar                     |Project MMO                   |pmmo                          |1.16.4-3.44.3       |DONE      |NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		ItemPhysic_v1.4.15_mc1.16.5.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |NOSIGNATURE
		byg-1.1.10.jar                                    |Oh The Biomes You'll Go       |byg                           |1.1.10              |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.4.0.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.4.0        |DONE      |NOSIGNATURE
		switchbow-1.7.jar                                 |Switch-Bow                    |switchbow                     |1.7                 |DONE      |NOSIGNATURE
		ScalingHealth-1.16.4-4.0.3+3.jar                  |Scaling Health                |scalinghealth                 |4.0.3+3             |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.13.jar                  |GeckoLib                      |geckolib3                     |3.0.13              |DONE      |NOSIGNATURE
		ars_nouveau-1.16.4-1.11.5.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.5              |DONE      |NOSIGNATURE
		xptome-1.16.4-v2.0.1.jar                          |XP Tome                       |xpbook                        |v2.0.1              |DONE      |NOSIGNATURE
	Crash Report UUID: 071a1685-9ab7-4240-a8f5-7f6f2b250b71
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['MergerPlayer'/48, l='ServerLevel[Sobrevivência]', x=584.53, y=63.00, z=30.27]]
	Data Packs: vanilla, mod:astralsorcery, mod:bountifulbaubles (incompatible), mod:jei, mod:abnormals_core, mod:goblintraders, mod:invtweaks (incompatible), mod:neat (incompatible), mod:bettercaves (incompatible), mod:waystones (incompatible), mod:placebo (incompatible), mod:comforts (incompatible), mod:citadel (incompatible), mod:yungsapi, mod:dungeoncrawl, mod:bookshelf, mod:guardvillagers, mod:realistictorches (incompatible), mod:apotheosis (incompatible), mod:mahoutsukai (incompatible), mod:iceandfire (incompatible), mod:waila, mod:mysticalworld (incompatible), mod:firstaid (incompatible), mod:forge, mod:betterendforge, mod:dsurround, mod:antiqueatlas, mod:repurposed_structures, mod:roughtweaks, mod:valhelsia_structures (incompatible), mod:creativecore, mod:towers_of_the_wild, mod:notreepunching, mod:bountiful (incompatible), mod:curios, mod:savageandravage, mod:patchouli (incompatible), mod:structurize, mod:minecolonies (incompatible), mod:spartanweaponry, mod:pmmo (incompatible), mod:observerlib, mod:itemphysic, mod:byg, mod:switchbow, mod:bettermineshafts (incompatible), mod:geckolib3 (incompatible), mod:ars_nouveau, mod:xpbook, mod:toughasnails, file/Madeira e Pedra.zip, file/Timber_v2.1.1.zip, mod:dungeonsmod, mod:dungeons_mobs (incompatible), mod:betteranimalsplus (incompatible), mod:dragonmounts, mod:upgrade_aquatic, mod:endergetic, mod:pandoras_creatures (incompatible), mod:silentlib (incompatible), mod:enchantwithmob, mod:scalinghealth, file/Enhancer, mod:structure_gel, mod:dungeons_arise, mod:dungeons_plus, mod:hardcorebattletowers, mod:enchdesc, mod:epicfight
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G6
	OptiFine Build: 20210117-013236
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 461.40
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by Yesssssman** [comment]
Check this again when I release updated version.

**Comment by Agno1a** [comment]
If this offers a clue, I created a new world and was able to play in it pretty well, until I entered a certain area of the world. I do not know whether this is caused by a structure or not, but I do know that these areas do not crash when I'm not using EFM

**Comment by Yesssssman** [comment]
Yeah, I can't assure what causes this error too, I'm gonna modify the code simply to resolve the problem appeared in crash report. So it might be a side effect. All I can believe is result of test.
