### ISSUE TITLE
[ERROR] The server crashed and could not start ：net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity

### ISSUE THREAD

**Issue by ChihoiTse** [Yesssssman/epicfightmod#257]
```java
[04:21:28] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class maninhouse.epicfight.events.EntityEvents hurtEvent(Lnet/minecraftforge/event/entity/living/LivingHurtEvent;)V
java.lang.ClassCastException: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
        at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193)
        at net.minecraftforge.eventbus.ASMEventHandler_173_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362)
        at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472)
        at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984)
        at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73)
        at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326)
        at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118)
        at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188)
        at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103)
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
        at net.minecraft.world.World.func_217390_a(World.java:554)
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:745)

[04:21:28] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 5837751a-c8d8-4bbf-b2ca-b02e991bc40e
[04:21:28] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111] {}
Caused by: java.lang.ClassCastException: net.minecraft.entity.projectile.ArrowEntity cannot be cast to net.minecraft.entity.LivingEntity
        at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:193) ~[?:1.0] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_173_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:362) ~[?:?] {re:classloading}
        at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json
:LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntity.java:984) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:
LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.monster.MonsterEntity.func_70097_a(SourceFile:73) ~[?:?] {re:classloading}
        at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:326) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.projectile.ProjectileEntity.func_70227_a(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:188) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.j
son:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.js
on:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        ... 5 more

```

**Comment by ChihoiTse** [comment]
I don't know what caused it, but most of it can be solved by rebooting the game, now it can't be played directly, can only delete the mod

**Comment by ChihoiTse** [comment]
Did the mod cause the game to crash frequently and the developers didn't fix it?I have to remove this mod
