### ISSUE TITLE
Atum 2 crash

### ISSUE THREAD

**Issue by Mr-Syntax** [Yesssssman/epicfightmod#271]
Ive had this crash quite a few times now, and its seems to be when a zombie from another mod pack is joining the world then that can crash it

java.lang.NullPointerException
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:82)
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:54)
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:74)
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:48)
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:29)
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:22)
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:77)
	at net.minecraftforge.eventbus.ASMEventHandler_2200_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2610/1315155836.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813)
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754)
	at net.minecraft.world.IServerWorld$$Lambda$27029/597413213.accept(Unknown Source)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11)
	at net.minecraft.world.server.ServerWorld.func_242106_g(ServerWorld.java:868)
	at net.minecraft.world.spawner.AbstractSpawner.func_98278_g(AbstractSpawner.java:144)
	at net.minecraft.tileentity.MobSpawnerTileEntity.func_73660_a(SourceFile:62)
	at net.minecraft.world.World.func_217391_K(World.java:491)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$26348/1020843478.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[13:05:02] [Server thread/FATAL]: Preparing crash report with UUID 357b5bdc-853a-4d58-9ca3-194f05e39355
[13:05:02] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$26348/1020843478.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:82) ~[?:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:54) ~[?:1.0]
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:74) ~[?:1.0]
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:48) ~[?:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:29) ~[?:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:22) ~[?:1.0]
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:77) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_2200_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2610/1315155836.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?]
	at net.minecraft.world.IServerWorld$$Lambda$27029/597413213.accept(Unknown Source) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51]
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_242106_g(ServerWorld.java:868) ~[?:?]
	at net.minecraft.world.spawner.AbstractSpawner.func_98278_g(AbstractSpawner.java:144) ~[?:?]
	at net.minecraft.tileentity.MobSpawnerTileEntity.func_73660_a(SourceFile:62) ~[?:?]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

**Comment by Mr-Syntax** [comment]
im running 1.16.5 on forge 36.10.0
