### ISSUE TITLE
Mowzie's Mob 1.12.2 Crash

### ISSUE THREAD

**Issue by TailsDoll2537** [Yesssssman/epicfightmod#312]
In the 1.12.2, actually in the 2.2.0/2.1.3 Versions, i try to use Ferrous Wroughtnaut Helmet; Mask of Barako, the Sun Chief and Barakoa masks, the game crashes

**Comment by Yesssssman** [comment]
Please attach the crash report.

**Comment by TailsDoll2537** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 6/21/21 3:46 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at maninthehouse.epicfight.capabilities.item.ArmorCapability.getBipedArmorModel(ArmorCapability.java:83)
	at maninthehouse.epicfight.client.renderer.layer.WearableItemLayer.getArmorModel(WearableItemLayer.java:113)
	at maninthehouse.epicfight.client.renderer.layer.WearableItemLayer.renderLayer(WearableItemLayer.java:58)
	at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.renderLayer(ArmatureRenderer.java:81)
	at maninthehouse.epicfight.client.renderer.entity.PlayerRenderer.renderLayer(PlayerRenderer.java:20)
	at maninthehouse.epicfight.client.renderer.entity.PlayerRenderer.renderLayer(PlayerRenderer.java:10)
	at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:46)
	at maninthehouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:197)
	at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:290)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_Events_renderLivingEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at maninthehouse.epicfight.capabilities.item.ArmorCapability.getBipedArmorModel(ArmorCapability.java:83)
	at maninthehouse.epicfight.client.renderer.layer.WearableItemLayer.getArmorModel(WearableItemLayer.java:113)
	at maninthehouse.epicfight.client.renderer.layer.WearableItemLayer.renderLayer(WearableItemLayer.java:58)
	at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.renderLayer(ArmatureRenderer.java:81)
	at maninthehouse.epicfight.client.renderer.entity.PlayerRenderer.renderLayer(PlayerRenderer.java:20)
	at maninthehouse.epicfight.client.renderer.entity.PlayerRenderer.renderLayer(PlayerRenderer.java:10)
	at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:46)
	at maninthehouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:197)
	at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:290)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_48_Events_renderLivingEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28)

-- Entity being rendered --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 374
	Entity Name: TailsDoll2537
	Entity's Exact location: -119.50, 64.00, 249.50
	Entity's Block location: World: (-120,64,249), Chunk: (at 8,4,9 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderPlayer@6e6cba95
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -186.74997
	Delta: 0.09998846
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['TailsDoll2537'/374, l='MpServer', x=-119.50, y=64.00, z=249.50]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-118,64,244), Chunk: (at 10,4,4 in -8,15; contains blocks -128,0,240 to -113,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2602 game time, 2602 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 65 total; [EntitySkeleton['Esqueleto'/256, l='MpServer', x=-75.50, y=22.00, z=260.50], EntityZombie['Zombi'/258, l='MpServer', x=-73.50, y=22.00, z=260.50], EntitySkeleton['Esqueleto'/259, l='MpServer', x=-77.50, y=22.00, z=260.50], EntityItem['item.item.seeds'/140, l='MpServer', x=-150.00, y=63.00, z=235.02], EntityZombie['Zombi'/653, l='MpServer', x=-110.92, y=35.00, z=240.30], EntityCow['Vaca'/149, l='MpServer', x=-136.81, y=65.00, z=206.54], EntityCow['Vaca'/150, l='MpServer', x=-131.54, y=65.00, z=207.81], EntityCow['Vaca'/151, l='MpServer', x=-138.45, y=63.00, z=212.45], EntityCow['Vaca'/152, l='MpServer', x=-139.01, y=63.00, z=213.41], EntityZombie['Zombi'/154, l='MpServer', x=-125.26, y=45.17, z=252.50], EntitySkeleton['Esqueleto'/666, l='MpServer', x=-81.39, y=55.00, z=200.27], EntityCreeper['Creeper'/155, l='MpServer', x=-126.36, y=38.00, z=241.78], EntityZombie['Zombi'/156, l='MpServer', x=-130.85, y=39.00, z=248.27], EntityBat['Murciélago'/157, l='MpServer', x=-103.25, y=35.72, z=247.91], EntityCreeper['Creeper'/541, l='MpServer', x=-74.50, y=36.00, z=205.50], EntityCreeper['Creeper'/158, l='MpServer', x=-135.17, y=37.00, z=262.50], EntityCreeper['Creeper'/543, l='MpServer', x=-73.50, y=36.00, z=210.50], EntityBat['Murciélago'/550, l='MpServer', x=-158.75, y=39.51, z=240.65], EntitySkeleton['Esqueleto'/173, l='MpServer', x=-114.28, y=27.00, z=230.52], EntitySpider['Araña'/174, l='MpServer', x=-112.01, y=36.00, z=239.98], EntityCreeper['Creeper'/175, l='MpServer', x=-120.56, y=38.00, z=246.20], EntityZombie['Zombi'/176, l='MpServer', x=-123.81, y=38.00, z=244.52], EntityBat['Murciélago'/177, l='MpServer', x=-120.25, y=34.10, z=253.45], EntityBat['Murciélago'/561, l='MpServer', x=-131.17, y=38.29, z=286.75], EntityCreeper['Creeper'/178, l='MpServer', x=-131.20, y=40.00, z=256.40], EntityBat['Murciélago'/179, l='MpServer', x=-120.34, y=37.82, z=240.35], EntityBat['Murciélago'/563, l='MpServer', x=-129.62, y=40.07, z=240.60], EntityBat['Murciélago'/180, l='MpServer', x=-135.68, y=39.15, z=242.02], EntityBat['Murciélago'/564, l='MpServer', x=-134.18, y=39.94, z=241.36], EntityZombie['Zombi'/181, l='MpServer', x=-117.25, y=50.00, z=267.53], EntityBat['Murciélago'/565, l='MpServer', x=-148.85, y=41.33, z=241.03], EntityCreeper['Creeper'/182, l='MpServer', x=-126.08, y=38.00, z=260.46], EntityZombieVillager['Aldeano zombi'/183, l='MpServer', x=-112.50, y=45.00, z=278.23], EntitySquid['Calamar'/570, l='MpServer', x=-87.17, y=60.79, z=248.86], EntitySquid['Calamar'/571, l='MpServer', x=-82.78, y=60.88, z=249.07], EntitySquid['Calamar'/572, l='MpServer', x=-86.71, y=59.56, z=246.94], EntitySquid['Calamar'/573, l='MpServer', x=-82.61, y=60.20, z=238.56], EntitySkeleton['Esqueleto'/447, l='MpServer', x=-105.50, y=49.00, z=290.50], EntitySkeleton['Esqueleto'/448, l='MpServer', x=-103.50, y=49.00, z=290.50], EntityBat['Murciélago'/197, l='MpServer', x=-99.28, y=31.02, z=205.77], EntitySkeleton['Esqueleto'/198, l='MpServer', x=-111.50, y=27.00, z=231.50], EntityZombieVillager['Aldeano zombi'/199, l='MpServer', x=-109.49, y=36.00, z=225.73], EntitySkeleton['Esqueleto'/200, l='MpServer', x=-109.71, y=36.00, z=231.50], EntityZombieVillager['Aldeano zombi'/201, l='MpServer', x=-103.26, y=39.00, z=225.47], EntityBat['Murciélago'/202, l='MpServer', x=-111.25, y=38.10, z=234.39], EntityCreeper['Creeper'/206, l='MpServer', x=-108.15, y=37.00, z=250.49], EntityZombieVillager['Aldeano zombi'/207, l='MpServer', x=-105.50, y=38.00, z=232.70], EntitySkeleton['Esqueleto'/591, l='MpServer', x=-76.02, y=22.00, z=257.86], EntitySkeleton['Esqueleto'/592, l='MpServer', x=-82.50, y=23.00, z=265.50], EntityBat['Murciélago'/209, l='MpServer', x=-103.72, y=36.50, z=248.85], EntityZombie['Zombi'/210, l='MpServer', x=-98.50, y=40.00, z=263.50], EntityZombie['Zombi'/214, l='MpServer', x=-97.73, y=42.00, z=292.55], EntityCreeper['Creeper'/215, l='MpServer', x=-105.50, y=44.00, z=296.50], EntitySkeleton['Esqueleto'/220, l='MpServer', x=-82.30, y=24.00, z=217.60], EntityZombie['Zombi'/222, l='MpServer', x=-85.50, y=23.00, z=220.50], EntityCreeper['Creeper'/223, l='MpServer', x=-80.50, y=22.00, z=250.50], EntitySquid['Calamar'/224, l='MpServer', x=-83.14, y=62.55, z=249.01], EntityBat['Murciélago'/226, l='MpServer', x=-73.91, y=24.39, z=258.57], EntityPig['Cerdo'/227, l='MpServer', x=-104.40, y=73.00, z=296.76], EntitySkeleton['Esqueleto'/625, l='MpServer', x=-161.50, y=18.00, z=202.50], EntityPlayerSP['TailsDoll2537'/374, l='MpServer', x=-119.50, y=64.00, z=249.50], EntityItem['item.item.reeds'/119, l='MpServer', x=-166.17, y=57.00, z=235.33], EntityItem['item.item.reeds'/120, l='MpServer', x=-165.81, y=61.00, z=233.44], EntityItem['item.item.reeds'/121, l='MpServer', x=-167.06, y=59.00, z=234.47], EntitySquid['Calamar'/250, l='MpServer', x=-72.60, y=55.62, z=218.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 197300720 bytes (188 MB) / 516497408 bytes (492 MB) up to 720633856 bytes (687 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx700M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                        | Signature                                |
	|:------ |:----------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | epicfight   | 1.12.2-2.0.0 | EpicFightMod-1.12.2-2.1.3.jar | None                                     |
	| LCHIJA | llibrary    | 1.7.20       | llibrary-1.7.20-1.12.2.jar    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs | 1.5.4        | mowziesmobs-1.5.4.jar         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 9300M GS/PCIe/SSE2'
	Launched Version: Forge 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce 9300M GS/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU P8400 @ 2.26GHz

**Comment by Yesssssman** [comment]
Thanks for reporting but It seems like I can make it not be crashed, but I can't fix it to look right because they use a specific library to render the model.

**Comment by TailsDoll2537** [comment]
Not Problem, really ^-^
