### ISSUE TITLE
Epic Fight Mod 2.0.0 causing server crash on start (Dedicated Server)

### ISSUE THREAD

**Issue by koderian** [Yesssssman/epicfightmod#4]
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Epic Fight Mod (epicfight) has failed to load correctly
§7java.lang.NoSuchFieldError: LOGICAL_CLIENT
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}

Running Forge 36.0.42
Forge Server

**Comment by koderian** [comment]
Crash Report UUID: d9ad4094-edb1-4f66-94ac-33e98a90916a[19:52:58] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Epic Fight Mod (epicfight) has failed to load correctly
§7java.lang.NoSuchFieldError: LOGICAL_CLIENT
]
at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282] {}
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282] {}
at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.42.jar:36.0] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.42.jar:?] {}
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.42.jar:?] {}
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.42.jar:?] {}

**Comment by koderian** [comment]
@Yesssssman

**Comment by Yesssssman** [comment]
Yes so I deleted 2.0.0. Instead, I uploaded 2.0.1 version and you can download it once it approved.

**Comment by koderian** [comment]
K, thanks!
