### ISSUE TITLE
Ticking entity crash on server (1.16.5 | EpicFightMod 4.1.5)

### ISSUE THREAD

**Issue by Librarian-Nose** [Yesssssman/epicfightmod#404]
The mod seemed to do fine with the others I had up until the point when my friend spawned a guard villager and it attacked some drowned sitting in the water during the day, which crashed my game crash. I removed all other mods except guard villagers and epic fight mod and my game only crashed when they attack drowned in the water during the day.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 7/16/21 7:56 AM
Description: Ticking entity

java.lang.RuntimeException: Attempted to load class maninhouse/epicfight/client/capabilites/entity/ClientPlayerData for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.35.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] {}
	at maninhouse.epicfight.animation.types.BasicAttackAnimation.getCoordVector(BasicAttackAnimation.java:61) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.ActionAnimation.move(ActionAnimation.java:92) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.ActionAnimation.updateOnLinkAnimation(ActionAnimation.java:75) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.LinkAnimation.onUpdate(LinkAnimation.java:12) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.AnimatorServer.update(AnimatorServer.java:57) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:134) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:101) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_22_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:guardvillagers.mixins.json:ZombieEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.35.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] {}
	at maninhouse.epicfight.animation.types.BasicAttackAnimation.getCoordVector(BasicAttackAnimation.java:61) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.ActionAnimation.move(ActionAnimation.java:92) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.ActionAnimation.updateOnLinkAnimation(ActionAnimation.java:75) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.LinkAnimation.onUpdate(LinkAnimation.java:12) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.AnimatorServer.update(AnimatorServer.java:57) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:134) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:101) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_22_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:339) ~[forge:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.monster.ZombieEntity.func_70071_h_(ZombieEntity.java:205) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:guardvillagers.mixins.json:ZombieEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:drowned (net.minecraft.entity.monster.DrownedEntity)
	Entity ID: 76
	Entity Name: Drowned
	Entity's Exact location: 341.47, 62.00, -177.36
	Entity's Block location: World: (341,62,-178), Chunk: (at 5,3,14 in 21,-12; contains blocks 336,0,-192 to 351,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2136
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,75,-192), Chunk: (at 0,4,0 in 15,-12; contains blocks 240,0,-192 to 255,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1591 game time, 1591 day time
	Level name: Dewie Land
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 109422 (now: false), thunder time: 25515 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5223903984 bytes (4981 MB) / 6294077440 bytes (6002 MB) up to 6294077440 bytes (6002 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xmx6G -Xms6G
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.35
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.35-universal.jar                |Forge                         |forge                         |36.1.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		guardvillagers-1.16.5.1.2.4.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |Manifest: NOSIGNATURE
		EpicFightMod-1.16.5-4.1.5.jar                     |Epic Fight Mod                |epicfight                     |4.1.5               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: cab1f99c-cc1a-4930-ae68-7064f7065a58
	Player Count: 0 / 15; []
	Data Packs: vanilla, mod:forge, mod:guardvillagers, mod:epicfight
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Yesssssman** [comment]
Try this again when new update is released. thanks.
