### ISSUE TITLE
Latest epic fight version /  forge 36.1.61 / 1.16.5 (replace second hand weapon crash)

### ISSUE THREAD

**Issue by FurryApocalypse** [Yesssssman/epicfightmod#411]
Not sure if there was such topic so i will write new one.
Epic fight allow to held 2 swords, one each hand.
Dungeons gears have double handed daggers that overwrite second hand even when you still held sword.
So if you have 2 swords in 2 hands, switch mine hand to daggers and go back to sword game will crash.

heres some logs:

[17lip2021 21:51:15.079] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Modifier is already applied on this attribute!
	Index: 6
	Listeners:
		0: NORMAL
		1: ASM: class mod.vemerion.wizardstaff.event.ForgeEventSubscriber updateStaffAttributes(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		2: ASM: class twilightforest.TFEventListener armorChanged(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		3: ASM: class com.infamous.dungeons_gear.items.melee.MeleeEvents dualWield(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		4: ASM: class com.infamous.dungeons_gear.items.armor.ArmorEvents onSpelunkerArmorEquipped(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		5: ASM: class com.infamous.dungeons_gear.GlobalEvents resetCombo(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		6: ASM: class maninhouse.epicfight.events.EntityEvents equipChangeEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		7: ASM: class com.ma.progression.ProgressionEventHandler onLivingEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		8: ASM: class com.ma.items.armor.ArmorEventHandler onEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		9: ASM: de.teamlapen.vampirism.entity.ModEntityEventHandler@7dd537da onEntityEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		10: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		11: ASM: net.mcreator.leosmushrooms.procedures.HealthIndecatorProcedure@508c46d onEntity(Lnet/minecraftforge/event/entity/EntityEvent;)V
		12: LOW
		13: ASM: de.teamlapen.vampirism.entity.ModEntityEventHandler@7dd537da onLivingEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:73)
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233767_b_(SourceFile:81)
	at maninhouse.epicfight.capabilities.entity.player.ServerPlayerData.onHeldItemChange(ServerPlayerData.java:117)
	at maninhouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:308)
	at net.minecraftforge.eventbus.ASMEventHandler_1415_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2420/176196547.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.entity.LivingEntity.func_241354_r_(LivingEntity.java:2268)
	at net.minecraft.entity.LivingEntity.func_241353_q_(LivingEntity.java:2239)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2141)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$23880/1052372215.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

[17lip2021 21:51:15.088] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 84a377dd-8daf-483e-9b4e-0b67843c3a0a
[17lip2021 21:51:15.091] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$23880/1052372215.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_111121_a(SourceFile:73) ~[?:?]
	at net.minecraft.entity.ai.attributes.ModifiableAttributeInstance.func_233767_b_(SourceFile:81) ~[?:?]
	at maninhouse.epicfight.capabilities.entity.player.ServerPlayerData.onHeldItemChange(ServerPlayerData.java:117) ~[?:1.0]
	at maninhouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:308) ~[?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_1415_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2420/176196547.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraft.entity.LivingEntity.func_241354_r_(LivingEntity.java:2268) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_241353_q_(LivingEntity.java:2239) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2141) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	... 7 more

**Comment by FurryApocalypse** [comment]
I've posted this also at Dungeons Gear issues

**Comment by FurryApocalypse** [comment]
ok it seems its not only for dungeon gears. I tried to replace sword in second hand with a simple wood log. Crashes again. 
Heres complete log
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6835404/latest.log)
and crash report
[crash-2021-07-18_01.03.13-server.txt](https://github.com/Yesssssman/epicfightmod/files/6835405/crash-2021-07-18_01.03.13-server.txt)

**Comment by FurryApocalypse** [comment]
I found a mod that was causing the crashes while swapping vanilla swords.
It was iguana tweaks reborn.
If anyone have same problem you can fix it by changing iguana tweaks configs in [combat.stats] sector to false.
Hope i was any helpful <3
