### ISSUE TITLE
[1.16.5] crash in alpha

### ISSUE THREAD

**Issue by kny6548** [Yesssssman/epicfightmod#469]
I haven't tested any other items, but the game turns off when I use the Nederite Longsword and the kill command.

**Comment by kny6548** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 21. 8. 20 오후 6:57
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.getSkill(PlayerData.java:154) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.skill.LiechtenauerSkill.lambda$onInitiate$2(LiechtenauerSkill.java:89) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.skill.LiechtenauerSkill$$Lambda$5055/1305564302.apply(Unknown Source) ~[?:?] {}
	at maninhouse.epicfight.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:23) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.entity.eventlistener.PlayerEventListener.activateEvents(PlayerEventListener.java:39) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.client.events.engine.ControllEngine$Events.moveInputEvent(ControllEngine.java:347) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_56_Events_moveInputEvent_InputUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2585/1929253120.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onInputUpdate(ForgeHooksClient.java:609) ~[?:?] {re:classloading}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70636_d(ClientPlayerEntity.java:604) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5046/1090424789.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$443/1160106451.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.getSkill(PlayerData.java:154) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.skill.LiechtenauerSkill.lambda$onInitiate$2(LiechtenauerSkill.java:89) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.skill.LiechtenauerSkill$$Lambda$5055/1305564302.apply(Unknown Source) ~[?:?] {}
	at maninhouse.epicfight.entity.eventlistener.EventTrigger.trigger(EventTrigger.java:23) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.entity.eventlistener.PlayerEventListener.activateEvents(PlayerEventListener.java:39) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.client.events.engine.ControllEngine$Events.moveInputEvent(ControllEngine.java:347) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_56_Events_moveInputEvent_InputUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2585/1929253120.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onInputUpdate(ForgeHooksClient.java:609) ~[?:?] {re:classloading}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70636_d(ClientPlayerEntity.java:604) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5046/1090424789.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.client.entity.player.ClientPlayerEntity)
	Entity ID: 1282
	Entity Name: kny6548
	Entity's Exact location: -16.11, 68.00, -6.72
	Entity's Block location: World: (-17,68,-7), Chunk: (at 15,4,9 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['kny6548'/1282, l='ClientLevel', x=-16.11, y=68.00, z=-6.72]]
	Chunk stats: Client Chunk Cache: 729, 420
	Level dimension: minecraft:overworld
	Level spawn location: World: (2,70,1), Chunk: (at 2,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 54257 game time, 8691 day time
	Server brand: forge arclight
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$443/1160106451.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1124943520 bytes (1072 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		EpicFightMod-1.16.5-5.0.0-alpha.jar               |Epic Fight Mod                |epicfight                     |5.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7dba94d5-5d81-4678-8ffc-edb5c2f14535
	Launched Version: 1.16.5-forge-36.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.27, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/5.zip (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
