### ISSUE TITLE
This is happening in my minecraft server , hope you can reply me with a solution , thanks!

### ISSUE THREAD

**Issue by timthaboihenson** [Yesssssman/epicfightmod#47]
[05Mar2021 17:20:11.111] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Can't find attribute epicfight:epicfight.weight
	Index: 3
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2855/0x0000000801436af8@678b9025
		2: ASM: class com.oblivioussp.spartanweaponry.event.CommonEventHandler onEquipmentChange(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
		3: ASM: class maninhouse.epicfight.events.EntityEvents equipChangeEvent(Lnet/minecraftforge/event/entity/living/LivingEquipmentChangeEvent;)V
java.lang.IllegalArgumentException: Can't find attribute epicfight:epicfight.weight
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(SourceFile:22)
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(SourceFile:28)
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62)
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1729)
	at maninhouse.epicfight.capabilities.entity.LivingData.getWeight(LivingData.java:281)
	at maninhouse.epicfight.capabilities.entity.player.ServerPlayerData.onArmorSlotChanged(ServerPlayerData.java:145)
	at maninhouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:342)
	at net.minecraftforge.eventbus.ASMEventHandler_489_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraft.entity.LivingEntity.func_241354_r_(LivingEntity.java:2268)
	at net.minecraft.entity.LivingEntity.func_241353_q_(LivingEntity.java:2239)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2141)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:832)

[05Mar2021 17:20:11.115] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 34298be7-1473-4487-9ffd-c8004e59e1e4
[05Mar2021 17:20:11.117] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /58.182.190.21:65324
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: Can't find attribute epicfight:epicfight.weight
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233810_d_(SourceFile:22) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierMap.func_233804_a_(SourceFile:28) ~[?:?]
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1729) ~[?:?]
	at maninhouse.epicfight.capabilities.entity.LivingData.getWeight(LivingData.java:281) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.player.ServerPlayerData.onArmorSlotChanged(ServerPlayerData.java:145) ~[epicfight:1.0]
	at maninhouse.epicfight.events.EntityEvents.equipChangeEvent(EntityEvents.java:342) ~[epicfight:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_489_EntityEvents_equipChangeEvent_LivingEquipmentChangeEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraft.entity.LivingEntity.func_241354_r_(LivingEntity.java:2268) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_241353_q_(LivingEntity.java:2239) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2141) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more

**Comment by timthaboihenson** [comment]
keeps giving my friends internal server error

**Comment by Yesssssman** [comment]
This is exactly the same issue from
#42

there might be a mod that using a custom attribute to the player. For now, forge doesn't provide a proper way to register attributes without mod confliction so I guess I need some rough way.

**Comment by timthaboihenson** [comment]
alright no worries , thanks for the reply

**Comment by timthaboihenson** [comment]
alright no worries , but I suspect that it could forgeendertech and its mods
