### ISSUE TITLE
Crash (seems to be) caused by EpicFightMod

### ISSUE THREAD

**Issue by FlexGamesYT** [Yesssssman/epicfightmod#491]
When I die Minecraft is crashing. This seems to be caused by this part in the logs:
```
java.lang.NullPointerException
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.getSkill(PlayerData.java:158)
	at maninhouse.epicfight.client.events.engine.ControllEngine.tick(ControllEngine.java:223)
	at maninhouse.epicfight.client.events.engine.ControllEngine$Events.preProcessKeyBindings(ControllEngine.java:357)
	at net.minecraftforge.eventbus.ASMEventHandler_914_Events_preProcessKeyBindings_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2594/708969759.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1414)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$478/217389263.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```
The full log:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/7049479/latest.log)

If you need any more information just ask

**Comment by Yesssssman** [comment]
Is this fixed?

**Comment by FlexGamesYT** [comment]
So, the first time I tried it (only have gotten 5 mins to test it so only died once) it worked, but right now I can't further test it as I'm in vacation

**Comment by Yesssssman** [comment]
Ok. Please send me the crash report again if it occurs again.
