### ISSUE TITLE
Compatability issue, Crash upon enter Desert Biome (Crash Report)

### ISSUE THREAD

**Issue by raponoves** [Yesssssman/epicfightmod#5]
With Dungeon mobs Installed, the server crashes whenever you enter a desert (Or perhaps when a monster spawns in the desert) with Dungeon Mobs installed. Last we spoke I believe you said it might have something to do with custom Zombie types spawning causing an issue.

Seeing as Dungeon Mobs and Dungeon gear are very popular mods, I thought it'd be worth mentioning.

[crash-2021-02-17_23.47.18-server.txt](https://github.com/Yesssssman/epicfightmod/files/6024909/crash-2021-02-17_23.47.18-server.txt)

**Comment by raponoves** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/23/21 1:05 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:80) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:57) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.init(LivingData.java:71) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.init(MobData.java:49) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:80) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_397_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$11030/2053417371.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:388) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$10576/1282905767.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$10263/977533323.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:80) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:57) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.init(LivingData.java:71) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.init(MobData.java:49) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:80) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_397_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$11030/2053417371.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:388) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$10576/1282905767.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['0tlus'/164, l='ServerLevel[New World]', x=1256.63, y=95.36, z=836.35]]
	Chunk stats: ServerChunkCache: 4326
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,63,231), Chunk: (at 0,3,7 in 5,14; contains blocks 80,0,224 to 95,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 22248 game time, 22248 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 126454 (now: false), thunder time: 83767 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$10263/977533323.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1193487056 bytes (1138 MB) / 5337776128 bytes (5090 MB) up to 7456948224 bytes (7111 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		EndRemastered-R352.jar                            |End Remastered 3.5.2          |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		TRansliterationLib-1.0.2.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.2               |DONE      |NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.3.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		notenoughanimations-1.1.0.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.1.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.4.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.4.0              |DONE      |NOSIGNATURE
		PassableFoliage-1.16.4-2.2.0.jar                  |Passable Foliage              |passablefoliage               |2.2.0               |DONE      |NOSIGNATURE
		EpicFightMod-1.16.4-2.0.2.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
		XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.12.0              |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
		citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
		alexsmobs-1.5.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.1               |DONE      |NOSIGNATURE
		earthmobsmod-1.16.4-0.4.2.jar                     |Earth Mobs Mod                |earthmobsmod                  |1.16.4-0.4.2        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guardvillagers-1.16.4-1.1.10.jar                  |Guard Villagers               |guardvillagers                |1.1.10              |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.13.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.13            |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.126.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.126           |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.4.0.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.4.0        |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		charmonium-forge-1.16.4-2.2.2.jar                 |Charmonium                    |charmonium                    |2.2.1               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		SubWild-1.16.5-1.1.2.jar                          |Subterranean Wilderness       |subwild                       |1.1.2               |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
	Crash Report UUID: cf30cc3e-0a5a-4c56-9223-bd7452ee5b34
	Player Count: 1 / 8; [ServerPlayerEntity['0tlus'/164, l='ServerLevel[New World]', x=1256.63, y=95.36, z=836.35]]
	Data Packs: vanilla, mod:endrem, mod:valhelsia_structures (incompatible), mod:transliterationlib (incompatible), mod:shouldersurfing (incompatible), mod:abnormals_core, mod:buzzier_bees, mod:atmospheric, mod:upgrade_aquatic, mod:notenoughanimations (incompatible), mod:savageandravage, mod:create (incompatible), mod:bettercaves (incompatible), mod:xaerominimap, mod:passablefoliage, mod:xaeroworldmap, mod:autumnity, mod:citadel (incompatible), mod:alexsmobs, mod:earthmobsmod (incompatible), mod:yungsapi, mod:mutantbeasts (incompatible), mod:guardvillagers, mod:endergetic, mod:jeitweaker, mod:crafttweaker, mod:enchantwithmob, mod:charm (incompatible), mod:charmonium (incompatible), mod:forge, mod:bettermineshafts (incompatible), mod:subwild, mod:dungeons_gear, mod:dungeons_mobs (incompatible), mod:epicfight
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.2.2 27.20.14535.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6
