### ISSUE TITLE
crash with galacticraft minecraft 1.12.2

### ISSUE THREAD

**Issue by LordStom** [Yesssssman/epicfightmod#506]
when starting the world and breaking a block or changing the camera, the game closes.
sometimes it doesn't even let you enter the world.
with all the latest versions of epic fight.

**crash report(break block):** 
WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 8/27/21 5:06 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at maninthehouse.epicfight.client.events.engine.ControllEngine.attackKeyPressed(ControllEngine.java:113)
	at maninthehouse.epicfight.client.events.engine.ControllEngine$Events.mouseEvent(ControllEngine.java:336)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_Events_mouseEvent_MouseInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireMouseInput(FMLCommonHandler.java:560)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2332)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1800)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at maninthehouse.epicfight.client.events.engine.ControllEngine.attackKeyPressed(ControllEngine.java:113)
	at maninthehouse.epicfight.client.events.engine.ControllEngine$Events.mouseEvent(ControllEngine.java:336)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_Events_mouseEvent_MouseInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireMouseInput(FMLCommonHandler.java:560)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2332)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LordStom'/28, l='MpServer', x=-469.63, y=4.00, z=-592.60]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-472,4,-591), Chunk: (at 8,0,1 in -30,-37; contains blocks -480,0,-592 to -465,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 85 game time, 85 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityVillager['Aldeano'/2, l='MpServer', x=-417.50, y=5.00, z=-654.50], EntityVillager['Aldeano'/3, l='MpServer', x=-422.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/4, l='MpServer', x=-410.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/5, l='MpServer', x=-409.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/8, l='MpServer', x=-399.50, y=5.00, z=-658.50], EntityVillager['Aldeano'/9, l='MpServer', x=-399.50, y=5.00, z=-657.50], EntityVillager['Aldeano'/10, l='MpServer', x=-401.41, y=5.00, z=-625.53], EntityVillager['Aldeano'/11, l='MpServer', x=-399.41, y=5.00, z=-625.30], EntityVillager['Aldeano'/13, l='MpServer', x=-391.50, y=5.00, z=-671.50], EntityVillager['Aldeano'/14, l='MpServer', x=-391.50, y=5.00, z=-670.50], EntityVillager['Aldeano'/16, l='MpServer', x=-392.99, y=5.00, z=-648.52], EntityVillager['Aldeano'/17, l='MpServer', x=-391.53, y=5.00, z=-635.50], EntityVillager['Aldeano'/18, l='MpServer', x=-391.50, y=5.00, z=-624.50], GCEntityClientPlayerMP['LordStom'/28, l='MpServer', x=-469.63, y=4.00, z=-592.60]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 724903848 bytes (691 MB) / 1174405120 bytes (1120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 9 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | epicfight           | 1.12.2-2.2.6 | EpicFightMod-1.12.2-2.2.6.jar             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.280    | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.280    | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.12.zip
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**crash report (change camera):**

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/27/21 5:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at maninthehouse.epicfight.client.events.engine.RenderEngine.updateCameraInfo(RenderEngine.java:229)
	at maninthehouse.epicfight.client.events.engine.RenderEngine.access$000(RenderEngine.java:106)
	at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.cameraSetupEvent(RenderEngine.java:337)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_Events_cameraSetupEvent_CameraSetup.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.EntityRenderer.func_78467_g(EntityRenderer.java:651)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:716)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1276)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at maninthehouse.epicfight.client.events.engine.RenderEngine.updateCameraInfo(RenderEngine.java:229)
	at maninthehouse.epicfight.client.events.engine.RenderEngine.access$000(RenderEngine.java:106)
	at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.cameraSetupEvent(RenderEngine.java:337)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_Events_cameraSetupEvent_CameraSetup.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.EntityRenderer.func_78467_g(EntityRenderer.java:651)
	at net.minecraft.client.renderer.EntityRenderer.func_78479_a(EntityRenderer.java:716)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1276)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['LordStom'/35, l='MpServer', x=-469.63, y=4.00, z=-592.60]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-472,4,-591), Chunk: (at 8,0,1 in -30,-37; contains blocks -480,0,-592 to -465,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 167 game time, 167 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 14 total; [EntityVillager['Aldeano'/6, l='MpServer', x=-417.50, y=5.00, z=-654.50], EntityVillager['Aldeano'/7, l='MpServer', x=-422.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/9, l='MpServer', x=-410.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/10, l='MpServer', x=-409.50, y=5.00, z=-647.50], EntityVillager['Aldeano'/11, l='MpServer', x=-401.41, y=5.00, z=-625.53], EntityVillager['Aldeano'/14, l='MpServer', x=-399.50, y=5.00, z=-658.50], EntityVillager['Aldeano'/15, l='MpServer', x=-399.50, y=5.00, z=-657.50], EntityVillager['Aldeano'/16, l='MpServer', x=-388.32, y=5.00, z=-670.14], EntityVillager['Aldeano'/17, l='MpServer', x=-391.50, y=5.00, z=-670.50], EntityVillager['Aldeano'/18, l='MpServer', x=-391.41, y=4.00, z=-649.84], EntityVillager['Aldeano'/19, l='MpServer', x=-399.41, y=5.00, z=-625.30], EntityVillager['Aldeano'/20, l='MpServer', x=-394.42, y=5.00, z=-635.14], GCEntityClientPlayerMP['LordStom'/35, l='MpServer', x=-469.63, y=4.00, z=-592.60], EntityVillager['Aldeano'/21, l='MpServer', x=-391.50, y=5.00, z=-624.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.a.m.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 353677328 bytes (337 MB) / 1174405120 bytes (1120 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 9 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                    | Signature                                |
	|:------ |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |              | minecraft.jar                             | None                                     |
	| LCHIJA | epicfight           | 1.12.2-2.2.6 | EpicFightMod-1.12.2-2.2.6.jar             | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.280    | GalacticraftCore-1.12.2-4.0.2.280.jar     | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.280    | Galacticraft-Planets-1.12.2-4.0.2.280.jar | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 456.71' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 1.12.zip
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

It also closes when you touch r

My English is bad, I'm translating, excuse me.

**Comment by Yesssssman** [comment]
Hello, can you try this again when 2.2.7 is released?

**Comment by LordStom** [comment]
Yes thanks.

**Comment by dhgameryt** [comment]
I have the same problem with the 2.2.6 version
and the galacticraft last version.
I understand that it is because the galacticraft alters the way to render the character in order to show the space equipment.

**Comment by Yesssssman** [comment]
Hello, I fixed the crash in my scope. So check it works fine in 2.2.7.

**Comment by LordStom** [comment]
hello, amazing thank you very much. 
works perfect for now.
