### ISSUE TITLE
[Bug] java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.EntityTeleportEvent$EnderEntity Stacktrace:

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#531]
It happens when i start the game.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/09/21 02:28 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:UtilMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.2.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.2.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraft.a.m.main(Unknown Source) [laulib-1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_301] {}
-- MOD epicfight --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent$EnderEntity
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301] {}
		at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_301] {}
		at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_301] {}
		at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_301] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
		at maninhouse.epicfight.main.EpicFightMod.<init>(EpicFightMod.java:79) ~[epicfight:1.0] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301] {}
		at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

	Mod File: EpicFightMod-1.16.5-5.0.4.jar
	Failure message: Epic Fight Mod (epicfight) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent$EnderEntity
	Mod Version: 5.0.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.EntityTeleportEvent$EnderEntity
Stacktrace:
	at java.lang.ClassLoader.findClass(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_301] {}
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-4.0.0.jar:?] {}
	at maninhouse.epicfight.main.EpicFightMod.<init>(EpicFightMod.java:79) ~[epicfight:1.0] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3491906832 bytes (3330 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.2
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |CREATE_REG|NOSIGNATURE
		BetterDungeons-1.16.4-1.2.jar                     |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2          |CREATE_REG|NOSIGNATURE
		blue_skies-1.16.5-1.1.3.jar                       |Blue Skies                    |blue_skies                    |1.1.3               |CREATE_REG|NOSIGNATURE
		infernal-expansion-2.1.1.jar                      |Infernal Expansion            |infernalexp                   |2.1.1               |CREATE_REG|NOSIGNATURE
		Shrines-1.16.5-1.8.1.jar                          |Shrines                       |shrines                       |1.16.5-1.8.1        |CREATE_REG|NOSIGNATURE
		treeharvester_1.16.5-2.4.jar                      |Tree Harvester                |treeharvester                 |2.4                 |CREATE_REG|NOSIGNATURE
		jei-1.16.5-7.7.1.110.jar                          |Just Enough Items             |jei                           |7.7.1.110           |CREATE_REG|NOSIGNATURE
		prefab-1.6.5.9.jar                                |Prefab                        |prefab                        |1.6.5.9             |CREATE_REG|NOSIGNATURE
		abnormals_core-1.16.5-3.1.0.jar                   |Abnormals Core                |abnormals_core                |3.1.0               |CREATE_REG|NOSIGNATURE
		Mekanism-1.16.5-10.0.21.448.jar                   |Mekanism                      |mekanism                      |10.0.21             |CREATE_REG|NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.1.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.1      |CREATE_REG|NOSIGNATURE
		stalwart-dungeons-1.16.5-1.1.1.jar                |Stalwart Dungeons             |stalwart_dungeons             |1.1.1               |CREATE_REG|NOSIGNATURE
		Kobolds-1.3.3.jar                                 |Kobolds                       |kobolds                       |1.0.0               |CREATE_REG|NOSIGNATURE
		ChickenDropFeathers-1.0-forge-1.16.5-36.0.0.jar   |ChickenDropFeathers           |chickendropfeathersmod        |1.0                 |CREATE_REG|NOSIGNATURE
		Waystones_1.16.5-7.6.2.jar                        |Waystones                     |waystones                     |7.6.2               |CREATE_REG|NOSIGNATURE
		EpicFightMod-1.16.5-5.0.4.jar                     |Epic Fight Mod                |epicfight                     |5.0.4               |ERROR     |NOSIGNATURE
		Rev's+Better+Structures+1.2B.jar                  |Rev's Better Structures       |revs_better_structures        |1.2B                |CREATE_REG|NOSIGNATURE
		citadel-1.7.2-1.16.5.jar                          |Citadel                       |citadel                       |1.7.2               |CREATE_REG|NOSIGNATURE
		alexsmobs-1.11.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.11.1              |CREATE_REG|NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.3.jar                |Traveler's Backpack           |travelersbackpack             |5.4.3               |CREATE_REG|NOSIGNATURE
		MekanismMatter-1.20.1-Beta-1.16.5.jar             |Mekanism: Matter              |mekanismmatter                |1.19.0              |CREATE_REG|NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |CREATE_REG|NOSIGNATURE
		compactmachines-4.0.0-beta.2.jar                  |Compact Machines 4            |compactmachines               |4.0.0-beta.2        |CREATE_REG|NOSIGNATURE
		curioofundying-forge-1.16.5-5.2.0.0.jar           |Curio of Undying              |curioofundying                |1.16.5-5.2.0.0      |CREATE_REG|NOSIGNATURE
		magicaljewelry-1.16.5_1.2.8.jar                   |Magical Jewelry               |magicaljewelry                |1.16.5_1.2.8        |CREATE_REG|NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.21.448.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.21             |CREATE_REG|NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |CREATE_REG|NOSIGNATURE
		inventorypets-1.16.5-2.0.15.jar                   |Inventory Pets                |inventorypets                 |2.0.15              |CREATE_REG|NOSIGNATURE
		sodium-forge-2.9.1+rev.63112e3.jar                |SodiumReforged                |sodium                        |2.9.1+rev.63112e3   |CREATE_REG|NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.127.jar         |Just Enough Resources         |jeresources                   |0.12.1.127          |CREATE_REG|NOSIGNATURE
		cazfps_the_dead_sea_1.16.4.jar                    |cazfps_the_dead_sea           |cazfps_the_dead_sea           |0.1.0               |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.2-universal.jar                 |Forge                         |forge                         |36.1.2              |CREATE_REG|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BloodMagic-1.16.4-3.1.0-15.jar                    |Blood Magic                   |bloodmagic                    |1.16.4-3.1.0-15     |CREATE_REG|NOSIGNATURE
		netherite-plus-mod-1.4.5-1.16.5-forge.jar         |Netherite Plus                |netherite_plus                |1.4.5-1.16.5        |CREATE_REG|NOSIGNATURE
		twilightforest-1.16.5-4.0.490-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|NOSIGNATURE
		refinedstorage-1.9.15.jar                         |Refined Storage               |refinedstorage                |1.9.15              |CREATE_REG|NOSIGNATURE
		meetyourfight-1.16.5-1.1.2.jar                    |Meet Your Fight               |meetyourfight                 |1.1.2               |CREATE_REG|NOSIGNATURE
		betterendforge-1.16.4-1.6.0.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.6.0        |CREATE_REG|NOSIGNATURE
		Upgraded+Netherite+1.10.0.jar                     |Upgraded Netherite            |upgradednetherite             |1.10.0              |CREATE_REG|NOSIGNATURE
		easy_piglins-1.16.5-1.0.2.jar                     |Easy Piglins                  |easy_piglins                  |1.16.5-1.0.2        |CREATE_REG|NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |CREATE_REG|NOSIGNATURE
		forge-1.16.5-36.1.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |CREATE_REG|NOSIGNATURE
		repurposed_structures_forge-3.2.0+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.2.0+1.16.5        |CREATE_REG|NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.4.jar              |More Villagers                |morevillagers                 |1.5.4               |CREATE_REG|NOSIGNATURE
		ToolBelt-1.16.3-1.15.2.jar                        |Tool Belt                     |toolbelt                      |1.15.2              |CREATE_REG|NOSIGNATURE
		Psi+1.16-95.jar                                   |Psi                           |psi                           |1.16-95             |CREATE_REG|NOSIGNATURE
		mana-and-artifice-1.4.0.8.jar                     |Mana and Artifice             |mana-and-artifice             |1.4.0.8             |CREATE_REG|NOSIGNATURE
		MekanismAdditions-1.16.5-10.0.21.448.jar          |Mekanism: Additions           |mekanismadditions             |10.0.21             |CREATE_REG|NOSIGNATURE
		EndRemastered-R36.jar                             |End Remastered 3.6            |endrem                        |1.16.3              |CREATE_REG|NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.3.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.3        |CREATE_REG|NOSIGNATURE
		CraftableSlimeBalls.jar                           |CraftableSlimeBalls           |craftableslimeballs           |1.0.0               |CREATE_REG|NOSIGNATURE
		easy_villagers-1.16.4-1.1.28.jar                  |Easy Villagers                |easy_villagers                |1.16.4-1.1.28       |CREATE_REG|NOSIGNATURE
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |CREATE_REG|NOSIGNATURE
		SchoolsOfMagic1.16.5-2.1.02.jar                   |Schools of Magic: Second Semes|schoolsofmagic                |2.1.02              |CREATE_REG|NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |CREATE_REG|NOSIGNATURE
		Atum-1.16.5-2.2.5.jar                             |Atum 2                        |atum                          |1.16.5-2.2.5        |CREATE_REG|NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |CREATE_REG|NOSIGNATURE
		rats-7.2.0-1.16.5.jar                             |Rats                          |rats                          |7.2.0               |CREATE_REG|NOSIGNATURE
		ratlantis-1.0.0-1.16.3.jar                        |Rats: Ratlantis               |ratlantis                     |1.0.0-1.16.3        |CREATE_REG|NOSIGNATURE
		collective-1.16.5-2.24.jar                        |Collective                    |collective                    |2.24                |CREATE_REG|NOSIGNATURE
		polymorph-forge-1.16.5-0.25.jar                   |Polymorph                     |polymorph                     |1.16.5-0.25         |CREATE_REG|NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |CREATE_REG|NOSIGNATURE
		petbuddy-1.16.5-3.1.0.0.jar                       |Pet Buddy                     |petbuddy                      |1.16.5-3.1.0.0      |CREATE_REG|NOSIGNATURE
		Cazfps_chronicles_v1.2_fix_1.16.4.jar             |cazfps chronicle              |cazfps_chronicle              |BETA1               |CREATE_REG|NOSIGNATURE
		TheAbyss2+2.0.0-snapshot-0.2980.jar               |TheAbyss                      |theabyss                      |2.0.0-snapshot-0.298|CREATE_REG|NOSIGNATURE
		MekanismTools-1.16.5-10.0.21.448.jar              |Mekanism: Tools               |mekanismtools                 |10.0.21             |CREATE_REG|NOSIGNATURE
		architectury-1.20.28-forge.jar                    |Architectury                  |architectury                  |1.20.28             |CREATE_REG|NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |CREATE_REG|NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.3.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.3      |CREATE_REG|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |CREATE_REG|NOSIGNATURE
		The_Undergarden-1.16.5-0.5.4.jar                  |The Undergarden               |undergarden                   |0.5.4               |CREATE_REG|NOSIGNATURE
		byg-1.2.9.jar                                     |Oh The Biomes You'll Go       |byg                           |1.2.9               |CREATE_REG|NOSIGNATURE
		FriendlyFire-1.16.5-7.0.2.jar                     |FriendlyFire                  |friendlyfire                  |7.0.2               |CREATE_REG|NOSIGNATURE
		TA2+beginning+1.0.9+1.16.5.jar                    |[Add-on] The Abyss: The Beginn|thebeginning                  |1.0.9               |CREATE_REG|NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v3a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v3a          |CREATE_REG|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |CREATE_REG|NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.4.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.4        |CREATE_REG|NOSIGNATURE
		expanded_combat-2.3.0-1.16.5.jar                  |Expanded Combat               |expanded_combat               |2.3.0               |CREATE_REG|NOSIGNATURE
		geckolib-forge-1.16.5-3.0.15.jar                  |GeckoLib                      |geckolib3                     |3.0.15              |CREATE_REG|NOSIGNATURE
		ars_nouveau-1.16.5-1.19.6.jar                     |Ars Nouveau                   |ars_nouveau                   |1.19.6              |CREATE_REG|NOSIGNATURE
		tomeofblood-1.16.5-1.1.jar                        |Tome of Blood                 |tomeofblood                   |1.16.5-1.1          |CREATE_REG|NOSIGNATURE
		effortlessbuilding-1.16.3-2.23.jar                |Effortless Building           |effortlessbuilding            |1.16.3-2.23         |CREATE_REG|NOSIGNATURE
		farlanders-1.16.4-1.3.9.jar                       |The Farlanders                |farlanders                    |1.3.9               |CREATE_REG|NOSIGNATURE
	Crash Report UUID: b0b7b195-e7df-4c89-a189-4424651dd56b

**Comment by Yesssssman** [comment]
Your forge version is old. Please use version 36.2.0 or above.
