### ISSUE TITLE
Crash when attacking while wearing dungeons content clothes in combat mode

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#551]
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_clouds
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_terrain
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Draw buffers: 08 -> 01
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_damagedblock
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_block
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_beaconbeam
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_entities
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:00] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_entities_glowing
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_armor_glint
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_spidereyes
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_hand
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_weather
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: deferred
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex8 mipmap enabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex9 clear disabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: deferred1
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Draw buffers: 059 -> 051
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: gbuffers_water
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex2 clear disabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex1 mipmap enabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite1
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program disabled: composite2
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program disabled: composite3
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex0 mipmap enabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite4
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite5
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex1 mipmap enabled
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite6
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:01] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: composite7
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Sun path rotation: -40.0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map resolution: 1024
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow map distance: 128.0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex0 format: R11F_G11F_B10F
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex1 format: RGB8
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex2 format: RGBA16
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex3 format: RGB8
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] gaux1 format: R8
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] gaux2 format: RGB8
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] gaux3 format: RG16
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] gaux4 format: RGB8
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex8 format: RGB16
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] colortex9 format: RGB16
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Hardware shadow filtering enabled.
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Shadow distance render mul: 1.0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Noise texture enabled
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Noise texture resolution: 512
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Dryness halflife: 300.0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Wetness halflife: 300.0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Program loaded: final
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedColorBuffers: 10
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedDepthBuffers: 2
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedShadowColorBuffers: 0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedShadowDepthBuffers: 0
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedColorAttachs: 10
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] usedDrawBuffers: 3
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] bindImageTextures: false
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Framebuffer created: dfb
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Reset model renderers
[22:41:02] [Render thread/INFO] [ne.op.sh.SMCLog/]: [Shaders] Reset world renderers
[22:41:08] [Render thread/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[22:41:08] [Render thread/INFO] [DynamicSurroundings/Lib]: JavaScript engine provided: Oracle Nashorn
[22:41:08] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [StepUp] 启用平滑自动上坡
[22:41:17] [SoundControl Sound Processor/WARN] [SoundControl/SoundFXProcessor]: SoundControl Sound Processor is lagging; behind 15 msecs
[22:41:18] [Worker-Main6/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=4049, y=3, z=6246}
[22:41:18] [Worker-Main6/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=4049, y=3, z=6246}
[22:41:18] [Worker-Main6/WARN] [minecraft/WorldGenRegion]: Tried to access a block entity before it was created. BlockPos{x=4049, y=3, z=6246}
[22:41:56] [Server thread/INFO] [minecraft/MinecraftServer]: [h_wushen: 你的游戏模式已被设置为生存模式 ]
[22:41:56] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] 你的游戏模式已被设置为生存模式 
[22:41:56] [Render thread/WARN] [SoundControl/MOD]: Unable to locate sound 'mobeffects:empty'
[22:42:01] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class org.orecruncher.lib.effects.EntityEffectHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: class maninhouse.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NullPointerException
	at net.minecraft.world.World.func_175674_a(World.java:717)
	at net.minecraft.world.IEntityReader.func_72839_b(SourceFile:32)
	at maninhouse.epicfight.physics.MultiCollider.updateAndFilterCollideEntity(MultiCollider.java:76)
	at maninhouse.epicfight.animation.types.AttackAnimation.onUpdate(AttackAnimation.java:111)
	at maninhouse.epicfight.animation.AnimatorServer.update(AnimatorServer.java:52)
	at maninhouse.epicfight.capabilities.entity.LivingData.updateOnServer(LivingData.java:130)
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.updateOnServer(PlayerData.java:121)
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:140)
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.update(PlayerData.java:149)
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98)
	at net.minecraftforge.eventbus.ASMEventHandler_814_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)

[22:42:01] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 4559684d-096d-4e8c-a878-408e95957449
[22:42:01] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:137) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.func_175674_a(World.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.world.WorldMixin,pl:mixin:A}
	at net.minecraft.world.IEntityReader.func_72839_b(SourceFile:32) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
	at maninhouse.epicfight.physics.MultiCollider.updateAndFilterCollideEntity(MultiCollider.java:76) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.types.AttackAnimation.onUpdate(AttackAnimation.java:111) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.animation.AnimatorServer.update(AnimatorServer.java:52) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.updateOnServer(LivingData.java:130) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.updateOnServer(PlayerData.java:121) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:140) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.player.PlayerData.update(PlayerData.java:149) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_814_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:340) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:origins.forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:placebo:placeboshieldblock,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:origins.mixins.json:LivingEntityMixin,pl:mixin:APP:origins.forge.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:origins.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:origins.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	... 6 more
libpng warning: iCCP: cHRM chunk does not match sRGB
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Yesssssman** [comment]
Fixed in 5.1.0.
