### ISSUE TITLE
Null Pointer crash rendering Tech Guns [MC 1.12.2]

### ISSUE THREAD

**Issue by ubergarm** [Yesssssman/epicfightmod#564]
#### Summary
Repeatable crashing when using Epic Fight with Tech Guns when an enemy zombie holding a gun is within render distance. You can also cheat up a gun (one or two-handed both crash) and run around for a minute to cause a crash. Disabling OptiFine did not help, but disabling Epic Fight reliably stops the crashing.

Thanks!

#### Versions
Minecraft 1.12.2: `forge-1.12.2-14.23.5.2855.jar`
EpicFight: `EpicFightMod-1.12.2-2.2.7.jar`
Tech Guns: `techguns-1.12.2-2.0.2.0_pre3.2.jar`

#### Crash Report

[Full Crash Report](https://gist.github.com/ubergarm/538117c9e67239d70b6584c0d7d1ccb0)

Snippet from crash report stack trace:
```
 Description: Rendering entity in world

 java.lang.NullPointerException: Rendering entity in world
     at techguns.client.render.ItemRenderHack.shouldRenderItem(ItemRenderHack.java:124)
     at techguns.client.render.ItemRenderHack.renderItem(ItemRenderHack.java:54)
     at net.minecraft.client.renderer.RenderItem.func_181564_a(RenderItem.java:238)
     at codechicken.lib.render.item.CCRenderItem.func_181564_a(CCRenderItem.java:293)
     at maninthehouse.epicfight.client.renderer.item.RenderItemBase.renderItemInHand(RenderItemBase.java:42)
     at maninthehouse.epicfight.client.renderer.layer.HeldItemLayer.renderLayer(HeldItemLayer.java:44)
     at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.renderLayer(ArmatureRenderer.java:81)
     at maninthehouse.epicfight.client.renderer.entity.ArmatureRenderer.render(ArmatureRenderer.java:46)
     at maninthehouse.epicfight.client.events.engine.RenderEngine.renderEntityArmatureModel(RenderEngine.java:202)
     at maninthehouse.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:307)
     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_252_Events_renderLivingEvent_Pre.invoke(.dynamic)
     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
     at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
     at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:78)
     at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
```

#### Related Issues
[Tech Guns Issue 269](https://github.com/pWn3d1337/Techguns2/issues/269)

**Comment by ubergarm** [comment]
Quick update: I just tested with the slightly older version of Tech Guns techguns-1.12.2-2.0.2.0_pre3.1.jar and the crash seems to go away!

Gonna just use old version for now until maybe someone figures it out on either side.

Cheers and thanks!

**Comment by ubergarm** [comment]
If anyone wants to recreate check out my modpack [Rotten Economy](https://www.curseforge.com/minecraft/modpacks/rotten-economy) with open source here [Rotten Economy Source](https://github.com/ubergarm/RottenEconomy)
