### ISSUE TITLE
Game crash when Skill Book Used

### ISSUE THREAD

**Issue by LakshyaKAChauhan** [Yesssssman/epicfightmod#574]
Bug:
1. When i typed a command : /give LAKSHYACHAUHAN epicfight:skillbook then i got a skill book but with no skill and then when i try to open it, the game crashes.

Suggesstion For Fix this Bug:
1. The Command is: /give \<Player Name\> epicfight:skillbook, Change the command to this:
 /give \<Player Name\> epicfight:skillbook_\<Skill of the skill book\>
e.g. --> /give LAKSHYACHAUHAN epicfight:skillbook_roll, /give LAKSHYACHAUHAN epicfight:skillbook_berserker
ETC.

Version:
Latest version of EPIC FIGHT

**Comment by FlameyFaucet** [comment]
The skill books use NBT data to show you the skill they're meant to give. Imo there shouldn't need to be a fix for this, as the game crashing when trying to retrieve data from NBT that is nonexistent is normal.

**Comment by shinoharatsuru** [comment]
java.lang.NullPointerException: Unexpected error
	at maninhouse.epicfight.item.SkillBookItem.getContainSkill(SkillBookItem.java:39) ~[epicfight:1.0] {re:classloading}
	at maninhouse.epicfight.client.gui.SkillDescriptionGui.<init>(SkillDescriptionGui.java:38) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.client.capabilites.entity.ClientPlayerData.openSkillBook(ClientPlayerData.java:133) ~[epicfight:1.0] {re:classloading,pl:runtimedistcleaner:A}
	at maninhouse.epicfight.item.SkillBookItem.lambda$onItemRightClick$1(SkillBookItem.java:77) ~[epicfight:1.0] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:165) ~[forge:?] {re:classloading,re:mixin}
	at maninhouse.epicfight.item.SkillBookItem.func_77659_a(SkillBookItem.java:75) ~[epicfight:1.0] {re:classloading}
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[?:?] {re:mixin,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187101_a(PlayerController.java:328) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:81) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1389) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1645) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1460) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf::default,xf::default,xf::default,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.6.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.6.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


This is my error report

**Comment by LakshyaKAChauhan** [comment]
yes, this it that error report showed in my pc
