### ISSUE TITLE
【bug】The server crashes when killing all mobs using commands

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#589]
The following is the crash report：

[0410月2021 14:26:42.725] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: wushen was slain by h_wushen
[0410月2021 14:26:48.963] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: h_wushen issued server command: /kill @e
[0410月2021 14:26:49.123] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: h_wushen fell out of the world
[0410月2021 14:26:49.132] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: [h_wushen: Killed 190 entities]
[0410月2021 14:26:50.063] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@c5d2a8c onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		2: ASM: class maninhouse.epicfight.events.EntityEvents updateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NullPointerException
	at net.minecraft.entity.ai.goal.PrioritizedGoal.hashCode(SourceFile:93)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at java.base/java.util.HashSet.add(HashSet.java:220)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75776_a(SourceFile:46)
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.convertRage(EndermanData.java:210)
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.updateOnServer(EndermanData.java:110)
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:140)
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.update(EndermanData.java:125)
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98)
	at net.minecraftforge.eventbus.ASMEventHandler_73_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooksMixin.java:340)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2112)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntityMixin.java:300)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorldMixin.java:611)
	at net.minecraft.world.World.func_217390_a(WorldMixin.java:554)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:404)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)

[0410月2021 14:26:50.072] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 678af656-21cf-48db-af71-8e50b76dcba3
[0410月2021 14:26:50.096] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.entity.ai.goal.PrioritizedGoal.hashCode(SourceFile:93) ~[?:?]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
	at java.util.HashMap.put(HashMap.java:607) ~[?:?]
	at java.util.HashSet.add(HashSet.java:220) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75776_a(SourceFile:46) ~[?:?]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.convertRage(EndermanData.java:210) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.updateOnServer(EndermanData.java:110) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:140) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.update(EndermanData.java:125) ~[epicfight:1.0]
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98) ~[epicfight:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_73_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooksMixin.java:340) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2112) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntityMixin.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorldMixin.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(WorldMixin.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?]
	... 5 more
[0410月2021 14:26:50.105] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.entity.ai.goal.PrioritizedGoal.hashCode(SourceFile:93) ~[?:?]
	at java.util.HashMap.hash(HashMap.java:339) ~[?:?]
	at java.util.HashMap.put(HashMap.java:607) ~[?:?]
	at java.util.HashSet.add(HashSet.java:220) ~[?:?]
	at net.minecraft.entity.ai.goal.GoalSelector.func_75776_a(SourceFile:46) ~[?:?]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.convertRage(EndermanData.java:210) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.updateOnServer(EndermanData.java:110) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:140) ~[epicfight:1.0]
	at maninhouse.epicfight.capabilities.entity.mob.EndermanData.update(EndermanData.java:125) ~[epicfight:1.0]
	at maninhouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:98) ~[epicfight:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_73_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooksMixin.java:340) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2112) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntityMixin.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorldMixin.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(WorldMixin.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Yesssssman** [comment]
Have you installed optifine or any other mods?

**Comment by Yesssssman** [comment]
#436

**Comment by wushen233** [comment]
I tested it on the server, and optifine has been installed. Then the crash caused by the enderman in the related problem, I killed it normally and did not crash

**Comment by wushen233** [comment]
> 您是否安装了 optifine 或任何其他模组？

I just tested it, single player will not crash. The server will crash

**Comment by wushen233** [comment]
> 您是否安装了 optifine 或任何其他模组？

Regarding the crash of the enderman, I probably found the problem. I found that if the enderman is holding a block and is attacked by the player to the frenzy stage, it will crash. And an enderman who doesn't hold a cube won't encounter it.

**Comment by KomiMoe** [comment]
i have the same issue. i'm running on LoliServer 1.16.5
