### ISSUE TITLE
Eating honey will crash the server.

### ISSUE THREAD

**Issue by raponoves** [Yesssssman/epicfightmod#6]
Any time honey is eaten, the entire server crashes, this does not happen in single player worlds.

Apparently the issue may be due to honey's ability to remove poison effects, causing the "Epic Fight Mod" to spam an error regarding this event in console and crashing the server.

**Comment by koderian** [comment]
I feel like the same issue has happened to me

**Comment by raponoves** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/22/21 4:51 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at maninhouse.epicfight.events.EntityEvents.effectRemoveEvent(EntityEvents.java:372) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_394_EntityEvents_effectRemoveEvent_PotionRemoveEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.entity.LivingEntity.func_195063_d(LivingEntity.java:873) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at com.minecraftabnormals.buzzier_bees.common.items.CuringItem.func_77654_b(CuringItem.java:51) ~[?:3.0.0] {re:classloading}
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:218) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1056) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:transliterationlib.forge.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$10263/873939211.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maninhouse.epicfight.events.EntityEvents.effectRemoveEvent(EntityEvents.java:372) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_394_EntityEvents_effectRemoveEvent_PotionRemoveEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraft.entity.LivingEntity.func_195063_d(LivingEntity.java:873) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at com.minecraftabnormals.buzzier_bees.common.items.CuringItem.func_77654_b(CuringItem.java:51) ~[?:3.0.0] {re:classloading}
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:218) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_71036_o(LivingEntity.java:2843) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71036_o(ServerPlayerEntity.java:1056) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_184608_ct(LivingEntity.java:2723) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:upgrade_aquatic.mixins.json:LivingEntityMixin,pl:mixin:APP:charm.mixins.json:LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_playerentity_iswearing,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:transliterationlib.forge.mixins.json:PlayerEntityMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinPlayerEntity,pl:mixin:APP:endergetic.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:PlayerEntityMixin,pl:mixin:APP:charm.mixins.json:accessor.PlayerEntityAccessor,pl:mixin:APP:dungeons_gear.mixins.json:PlayerEntityMixin,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 17
	Entity Name: 0tlus
	Entity's Exact location: -2239.94, 4.00, 291.82
	Entity's Block location: World: (-2240,4,291), Chunk: (at 0,0,3 in -140,18; contains blocks -2240,0,288 to -2225,255,303), Region: (-5,0; contains chunks -160,0 to -129,31, blocks -2560,0,0 to -2049,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endergetic.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$10263/873939211.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1372900392 bytes (1309 MB) / 3645374464 bytes (3476 MB) up to 4831838208 bytes (4608 MB)
	CPUs: 6
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5184m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		EndRemastered-R352.jar                            |End Remastered 3.5.2          |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |DONE      |NOSIGNATURE
		TRansliterationLib-1.0.2.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.2               |DONE      |NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.3.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.3        |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
		atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		notenoughanimations-1.1.0.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.1.0               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.4.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.4.0              |DONE      |NOSIGNATURE
		PassableFoliage-1.16.4-2.2.0.jar                  |Passable Foliage              |passablefoliage               |2.2.0               |DONE      |NOSIGNATURE
		EpicFightMod-1.16.4-2.0.1.jar                     |Epic Fight Mod                |epicfight                     |1.0.0               |DONE      |NOSIGNATURE
		XaerosWorldMap_1.12.0.2_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.12.0              |DONE      |NOSIGNATURE
		autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
		citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
		alexsmobs-1.5.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.1               |DONE      |NOSIGNATURE
		earthmobsmod-1.16.4-0.4.2.jar                     |Earth Mobs Mod                |earthmobsmod                  |1.16.4-0.4.2        |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guardvillagers-1.16.4-1.1.10.jar                  |Guard Villagers               |guardvillagers                |1.1.10              |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.13.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.13            |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.126.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.126           |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.4.0.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.4.0        |DONE      |NOSIGNATURE
		charm-forge-1.16.4-2.2.2.jar                      |Charm                         |charm                         |2.2.2               |DONE      |NOSIGNATURE
		charmonium-forge-1.16.4-2.2.2.jar                 |Charmonium                    |charmonium                    |2.2.1               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		SubWild-1.16.5-1.1.2.jar                          |Subterranean Wilderness       |subwild                       |1.1.2               |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
	Crash Report UUID: 5778e46f-b39e-4773-9267-0f247a189f24
	Player Count: 1 / 8; [ServerPlayerEntity['0tlus'/17, l='ServerLevel[New World]', x=-2239.94, y=4.00, z=291.82]]
	Data Packs: vanilla, mod:endrem, mod:valhelsia_structures (incompatible), mod:transliterationlib (incompatible), mod:shouldersurfing (incompatible), mod:dungeons_mobs (incompatible), mod:abnormals_core, mod:buzzier_bees, mod:atmospheric, mod:upgrade_aquatic, mod:notenoughanimations (incompatible), mod:savageandravage, mod:create (incompatible), mod:bettercaves (incompatible), mod:xaerominimap, mod:passablefoliage, mod:epicfight, mod:xaeroworldmap, mod:autumnity, mod:citadel (incompatible), mod:alexsmobs, mod:earthmobsmod (incompatible), mod:yungsapi, mod:mutantbeasts (incompatible), mod:guardvillagers, mod:endergetic, mod:jeitweaker, mod:crafttweaker, mod:enchantwithmob, mod:forge, mod:charm (incompatible), mod:charmonium (incompatible), mod:bettermineshafts (incompatible), mod:subwild, mod:dungeons_gear
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Enhanced Default v1.12.zip
	OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.2.2 27.20.14535.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by raponoves** [comment]
In this crash report I ate an item from the mod "Buzzier Bees" Which has the same effect as honey, and also results in a crash.

All items from the mod that are honey based, and thus share it's poison removal property cause crashes. Thus I assume this mod has some sort of issue with the "remove poison" effect. This crash does not occure with milk, which removes potion effects.

**Comment by Yesssssman** [comment]
Alr I found the reason on the dubugging mod. this will be fixed in new version.
