### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by Evadinfeelies** [Yesssssman/epicfightmod#617]
As others mentioned there are a lot of crash issues the main problem i am having is when i use the mod with another mod it causes crashes, for example if used with dungeon crawler mod when mobs spawn from spawners inside dungeon crawler's mod it will crash. I am assuming its because dungeon crawler is tryna spawn normal mob and yours is tryna override its battling mode but this can be solved by using ; https://www.curseforge.com/minecraft/mc-mods/spawner-fix 

The problem i am having now is when i use this mod with Apotheosis mod, when i am in the same chunk of Apotheosis structure, mostly when im on surface and when its underground it crashes the player. not the server but the player. i thought this was my problem but i saw other players crash too. here is what crash log looks like 

edit : also loved your mod

-- Head --
Thread: Render thread
Stacktrace:
	at yesman.epicfight.client.animation.AnimatorClient.playInitialLivingMotion(AnimatorClient.java:94) ~[?:1.0] {re:classloading}
	at yesman.epicfight.capabilities.entity.LivingData.onEntityConstructed(LivingData.java:73) ~[?:1.0] {re:classloading}
	at yesman.epicfight.capabilities.entity.LivingData.onEntityConstructed(LivingData.java:59) ~[?:1.0] {re:classloading}
	at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:38) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_178_CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2642/927540558.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:597) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:591) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.Entity.<init>(Entity.java:221) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:performant.mixins.json:client.EntityMixin,pl:mixin:APP:abnormals_core.mixins.json:EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:origins.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:performant.mixins.json:entity.EntityUpdateMixin,pl:mixin:APP:performant.mixins.json:entity.EntityMixin,pl:mixin:A}
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:205) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:tenshilib.mixins.json:LivingEntityMixin,pl:mixin:APP:origins.mixins.json:LivingEntityMixin,pl:mixin:APP:origins.forge.mixins.json:LivingEntityMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinLivingEntity,pl:mixin:APP:improvedmobs.mixins.json:GuardianMixin,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:improvedmobs.mixins.json:MobEntityMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityDespawnMixin,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A}
	at net.minecraft.entity.CreatureEntity.<init>(SourceFile:12) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:entity.CreatureEntityMixin,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.<init>(SourceFile:30) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.monster.VexEntity.<init>(SourceFile:55) ~[?:?] {re:classloading}
	at net.minecraft.entity.EntityType$$Lambda$1714/2069804672.create(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:445) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at shadows.apotheosis.spawn.spawner.ApothSpawnerTile$SpawnerLogicExt.lambda$getOrCreateDisplayEntity$0(ApothSpawnerTile.java:88) ~[?:4.8.0] {re:classloading}
	at shadows.apotheosis.spawn.spawner.ApothSpawnerTile$SpawnerLogicExt$$Lambda$15051/1493549500.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:?] {}
	at shadows.apotheosis.spawn.spawner.ApothSpawnerTile$SpawnerLogicExt.func_184994_d(ApothSpawnerTile.java:87) ~[?:4.8.0] {re:classloading}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.MobSpawnerTileEntityRenderer.func_225616_a_(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:126) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:101) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher$$Lambda$14916/487065371.run(Unknown Source) ~[?:?] {}

-- Block Entity Details --
Details:
	Name: minecraft:mob_spawner // shadows.apotheosis.spawn.spawner.ApothSpawnerTile
	Block: Block{minecraft:spawner}
	Block location: World: (-1537,41,-1380), Chunk: (at 15,2,12 in -97,-87; contains blocks -1552,0,-1392 to -1537,255,-1377), Region: (-4,-3; contains chunks -128,-96 to -97,-65, blocks -2048,0,-1536 to -1537,255,-1025)
	Block: Block{minecraft:spawner}
	Block location: World: (-1537,41,-1380), Chunk: (at 15,2,12 in -97,-87; contains blocks -1552,0,-1392 to -1537,255,-1377), Region: (-4,-3; contains chunks -128,-96 to -97,-65, blocks -2048,0,-1536 to -1537,255,-1025)
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:185) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228850_a_(TileEntityRendererDispatcher.java:99) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1814) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:tenshilib.mixins.json:WorldRenderAccessor,pl:mixin:APP:quark.mixins.json:client.WorldRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:origins.mixins.json:GameRendererMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['slycraze'/32491, l='ClientLevel', x=-1545.50, y=61.75, z=-1332.50]]
	Chunk stats: Client Chunk Cache: 289, 257
	Level dimension: minecraft:overworld
	Level spawn location: World: (5,64,1), Chunk: (at 5,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1057272 game time, 1477423 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,re:classloading,xf:OptiFine:default,xf:fml:astralsorcery:sun_brightness_client,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/572302485.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3820982944 bytes (3643 MB) / 5200936960 bytes (4960 MB) up to 5200936960 bytes (4960 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx4948M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.8.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.8.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.8
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		DungeonsMod-1.16.3-1.4.40.jar                     |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.4.40       |DONE      |Manifest: NOSIGNATURE
		astralsorcery-1.16-1.16.5-1.13.12.jar             |Astral Sorcery                |astralsorcery                 |1.16.5-1.13.12      |DONE      |Manifest: 45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		CC(FG1.16.5)+v1.1.5.jar                           |Caves And Cliffs              |caves_and_cliffs              |1.1.5               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.122.jar                          |Just Enough Items             |jei                           |7.7.1.122           |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.6.0-1.16.3.jar                    |Goblin Traders                |goblintraders                 |1.6.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.1.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.1      |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |DONE      |Manifest: NOSIGNATURE
		EpicFightMod-1.16.5-5.1.0.jar                     |Epic Fight Mod                |epicfight                     |5.1.0               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.17.1_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.17.1              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.0.jar                          |Placebo                       |placebo                       |4.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.2.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.2       |DONE      |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.0.jar             |Simple Storage Network        |storagenetwork                |1.16.5-1.5.0        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		PlayerMobs-1.1.0.9.jar                            |Player Mobs                   |player_mobs                   |1.1.0.9             |DONE      |Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |DONE      |Manifest: NOSIGNATURE
		OuterEnd-0.2.14.jar                               |The Outer End                 |outer_end                     |0.2.9               |DONE      |Manifest: NOSIGNATURE
		champions-forge-1.16.5-2.0.1.7.jar                |Champions                     |champions                     |1.16.5-2.0.1.7      |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.16.5-2.3.2.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.2               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.2.12.337.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.2.12.337   |DONE      |Manifest: NOSIGNATURE
		Apotheosis-1.16.5-4.8.0.jar                       |Apotheosis                    |apotheosis                    |4.8.0               |DONE      |Manifest: NOSIGNATURE
		Morpheus-1.16.5-4.2.70.jar                        |Morpheus                      |morpheus                      |4.2.70              |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		forge-1.16.5-36.2.8-universal.jar                 |Forge                         |forge                         |36.2.8              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		subwild-1.3.0.jar                                 |Subterranean Wilderness       |subwild                       |1.3.0               |DONE      |Manifest: NOSIGNATURE
		w2w-1.16.1-0.0.5.2.jar                            |w2w                           |w2w                           |NONE                |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.8-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		TenshiLib-1.16.3-1.3.0.jar                        |TenshiLib                     |tenshilib                     |1.16.3-1.3.0        |DONE      |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.3.271.jar                   |Tinkers' Construct            |tconstruct                    |3.1.3.271           |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-3.2.5+1.16.5.jar      |Repurposed Structures         |repurposed_structures         |3.2.5+1.16.5        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.1.jar                    |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		SpawnerFix-1.16.2-1.0.0.2.jar                     |Spawner Fix                   |sf                            |1.0.0.2             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		savageandravage-1.16.5-3.1.0.jar                  |Savage & Ravage               |savageandravage               |3.1.0               |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Origins-1.16.5-0.7.3.9-forge.jar                  |Origins                       |origins                       |0.7.3.9             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.17.2_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.17.2             |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		performant-1.16.2-5-3.72m.jar                     |Performant                    |performant                    |3.56m               |DONE      |Manifest: NOSIGNATURE
		villagertools-1.16.5-1.0.1.jar                    |villagertools                 |villagertools                 |1.16.5-1.0.1        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		tombstone-1.16.5-6.5.3.jar                        |Corail Tombstone              |tombstone                     |6.5.3               |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-316.jar                                |Quark                         |quark                         |r2.4-316            |DONE      |Manifest: NOSIGNATURE
		EnigmaticLegacy-2.11.5.jar                        |Enigmatic Legacy              |enigmaticlegacy               |2.11.5              |DONE      |Manifest: NOSIGNATURE
		TheAbyss2+1.9.7+1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |DONE      |Manifest: NOSIGNATURE
		architectury-1.23.33-forge.jar                    |Architectury                  |architectury                  |1.23.33             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.3-build.74.jar           |FTB Library                   |ftblibrary                    |1605.3.3-build.74   |DONE      |Manifest: NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-1605.2.3-build.75.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.75   |DONE      |Manifest: NOSIGNATURE
		lootr-1.16.5-0.0.8.24.jar                         |Lootr                         |lootr                         |0.0.8.23            |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.0.7-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.7               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		observerlib-1.16.5-1.5.3.jar                      |ObserverLib                   |observerlib                   |1.16.5-1.5.3        |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |DONE      |Manifest: NOSIGNATURE
		enhancedcelestials-2.0.8-1.16.5.jar               |Enhanced Celestials           |enhancedcelestials            |2.0.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
		collectionorigins1-1.0.jar                        |Imperium Origins Collection 1 |collectionorigins1            |1.0                 |DONE      |Manifest: NOSIGNATURE
		cursery-2.5-1.16.5.jar                            |Cursery Mod                   |cursery                       |2.5-1.16.5          |DONE      |Manifest: NOSIGNATURE
		collectionorigins2-1.0.jar                        |Imperium Origins Collection 2 |collectionorigins2            |1.0                 |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.16.5-1.7.9.jar                     |Improved Mobs Mod             |improvedmobs                  |1.16.5-1.7.9        |DONE      |Manifest: NOSIGNATURE
		expandability-2.0.2-forge.jar                     |ExpandAbility                 |expandability                 |2.0.2               |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.16.5-0.12.jar                  |Vein Mining                   |veinmining                    |1.16.5-0.12         |DONE      |Manifest: NOSIGNATURE

**Comment by Yesssssman** [comment]
This crash happens when vex was spawned in 5.1.0. But it was fixed in 5.1.1, so please update your Epic Fight version. If this problem keeps occurring, let me know again.
