### ISSUE TITLE
Crash when creating new world.

### ISSUE THREAD

**Issue by LoSilopante** [Yesssssman/epicfightmod#629]
I'm trying to make a modpack and recently I updated both EpicFight and Forge to the latest release; now I'm getting this error whenever I create a new world:

### [OPTIFINE]  java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:809)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:90)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at net.minecraft.server.MinecraftServer$$Lambda$50836/567826808.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
### Caused by: java.lang.NoClassDefFoundError: maninhouse/epicfight/capabilities/item/CapabilityItem
	at github.pitbox46.epicfightnbt.Config.<clinit>(Config.java:28)
	at github.pitbox46.epicfightnbt.EpicFightNBT.onServerStarting(EpicFightNBT.java:31)
	at net.minecraftforge.eventbus.ASMEventHandler_487_EpicFightNBT_onServerStarting_FMLServerStartingEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2434/63955537.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:101)
	... 10 more
### Caused by: java.lang.ClassNotFoundException: maninhouse.epicfight.capabilities.item.CapabilityItem
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
	Suppressed: java.lang.ClassNotFoundException
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282)
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)

**Comment by Yesssssman** [comment]
Remove the Epic Fight NBT. It's not compatible with recent updates.
