### ISSUE TITLE
I have a null pointer exception when dying on nether

### ISSUE THREAD

**Issue by Arzeriuwu** [Yesssssman/epicfightmod#697]
This Error is always show when someone die on the nether 
(this crash report is from an aternos server with other mods )

[21:08:11 WARN]: java.lang.NullPointerException
[21:08:11 WARN]: 	at yesman.epicfight.events.PlayerEvents.changeDimensionEvent(PlayerEvents.java:83)
[21:08:11 WARN]: 	at net.minecraftforge.eventbus.ASMEventHandler_164_PlayerEvents_changeDimensionEvent_PlayerChangedDimensionEvent.invoke(.dynamic)
[21:08:11 WARN]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[21:08:11 WARN]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[21:08:11 WARN]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[21:08:11 WARN]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerChangedDimensionEvent(BasicEventHooks.java:51)
[21:08:11 WARN]: 	at net.minecraft.server.management.PlayerList.moveToWorld(PlayerList.java:720)
[21:08:11 WARN]: 	at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:542)
[21:08:11 WARN]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2051)
[21:08:11 WARN]: 	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
[21:08:11 WARN]: 	at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
[21:08:11 WARN]: 	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[21:08:11 WARN]: 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[21:08:11 WARN]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[21:08:11 WARN]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
[21:08:11 WARN]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
[21:08:11 WARN]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
[21:08:11 WARN]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[21:08:11 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Yesssssman** [comment]
Is this still on 16.5.13?
