### ISSUE TITLE
ERROR Entity Configure 1.16.5

### ISSUE THREAD

**Issue by WerelWolf** [Yesssssman/epicfightmod#760]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 11/13/21 2:41 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.0-launcher.jar:36.2] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at com.electronwill.nightconfig.toml.StringParser.escape(StringParser.java:130) ~[toml-3.6.3.jar:?] {}
-- MOD epicfight --
Details:
Caused by 0: java.lang.ExceptionInInitializerError
at yesman.epicfight.main.EpicFightMod.(EpicFightMod.java:73) ~[epicfight:1.0] {re:classloading}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301] {}
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

Mod File: EpicFightMod-16.5.9.jar
Failure message: Epic Fight Mod (epicfight) has failed to load correctly
	java.lang.ExceptionInInitializerError: null
Mod Version: 16.5.9
Mod Issue URL: NOT PROVIDED
Exception message: com.electronwill.nightconfig.core.io.ParsingException: Invalid escapement: \s
Stacktrace:
at com.electronwill.nightconfig.toml.StringParser.escape(StringParser.java:130) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.StringParser.parseBasic(StringParser.java:25) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:44) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?] {}
at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?] {}
at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?] {}
at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
at yesman.epicfight.config.ConfigManager.(ConfigManager.java:21) ~[epicfight:1.0] {re:classloading}
at yesman.epicfight.main.EpicFightMod.(EpicFightMod.java:73) ~[epicfight:1.0] {re:classloading}
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_301] {}
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_301] {}
at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.2] {re:classloading}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {}
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_301, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 4818281664 bytes (4595 MB) / 5301600256 bytes (5056 MB) up to 5301600256 bytes (5056 MB)
CPUs: 8
JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5120m -Xmx5120m
ModLauncher: 8.0.9+86+master.3cf110c
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services:
/mixin-0.8.2.jar mixin PLUGINSERVICE
/eventbus-4.0.0.jar eventbus PLUGINSERVICE
/forge-1.16.5-36.2.0-launcher.jar object_holder_definalize PLUGINSERVICE
/forge-1.16.5-36.2.0-launcher.jar runtime_enum_extender PLUGINSERVICE
/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
/forge-1.16.5-36.2.0-launcher.jar capability_inject_definalize PLUGINSERVICE
/forge-1.16.5-36.2.0-launcher.jar runtimedistcleaner PLUGINSERVICE
/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE
/forge-1.16.5-36.2.0-launcher.jar fml TRANSFORMATIONSERVICE
FML: 36.2
Forge: net.minecraftforge:36.2.0
FML Language Providers:
javafml@36.2
minecraft@1
Mod List:
forge-1.16.5-36.2.0-client.jar |Minecraft |minecraft |1.16.5 |CREATE_REG|Manifest: NOSIGNATURE
MedievalCraft-1.16.5-1.16.0.jar |Medieval craft |medieval_craft |1.14.4 |CREATE_REG|Manifest: NOSIGNATURE
forge-1.16.5-36.2.0-universal.jar |Forge |forge |36.2.0 |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
curios-forge-1.16.5-4.0.5.3.jar |Curios API |curios |1.16.5-4.0.5.3 |CREATE_REG|Manifest: NOSIGNATURE
EpicFightMod-16.5.9.jar |Epic Fight Mod |epicfight |16.5.9 |ERROR |Manifest: NOSIGNATURE
Crash Report UUID: 6d463b3a-27c8-454a-9f37-ab2a53911caf

**Comment by WerelWolf** [comment]
I tried to do the same procedure you did in your video with the tuna mummys but you are having this error, in the entity settings

**Comment by Yesssssman** [comment]
Your config file has invalid syntax. Check it again.

**Comment by WerelWolf** [comment]
![image](https://user-images.githubusercontent.com/67131150/141668841-7cda10cb-47f4-4e1c-922e-c84e8f50140b.png)

**Comment by Yesssssman** [comment]
I'm not responsible for config parsing errors. Sometimes the file itself makes the crash so I recommend deleting the file and rewrite it.

**Comment by WerelWolf** [comment]
still with the same error

**Comment by WerelWolf** [comment]
I don't know what to do, I've tried everything

**Comment by Yesssssman** [comment]
Delete the config file then copy and paste every single line.

**Comment by WerelWolf** [comment]
ok thanks
