### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by IanIury13** [Yesssssman/epicfightmod#78]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (Skillable-beta-10.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/14/21 9:19 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70665_d(BaseCreatureEntity.java:3284)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70097_a(BaseCreatureEntity.java:3325)
	at com.lycanitesmobs.core.entity.TameableCreatureEntity.func_70097_a(TameableCreatureEntity.java:637)
	at com.lycanitesmobs.core.entity.BaseProjectileEntity.func_70184_a(BaseProjectileEntity.java:248)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at com.lycanitesmobs.core.entity.BaseProjectileEntity.func_70071_h_(BaseProjectileEntity.java:121)
	at com.lycanitesmobs.core.entity.CustomProjectileEntity.func_70071_h_(CustomProjectileEntity.java:168)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:117)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_223_EntityEvents_hurtEvent_LivingHurtEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:604)
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70665_d(BaseCreatureEntity.java:3284)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:926)
	at com.lycanitesmobs.core.entity.BaseCreatureEntity.func_70097_a(BaseCreatureEntity.java:3325)
	at com.lycanitesmobs.core.entity.TameableCreatureEntity.func_70097_a(TameableCreatureEntity.java:637)
	at com.lycanitesmobs.core.entity.BaseProjectileEntity.func_70184_a(BaseProjectileEntity.java:248)
	at net.minecraft.entity.projectile.EntityThrowable.func_70071_h_(EntityThrowable.java:249)
	at com.lycanitesmobs.core.entity.BaseProjectileEntity.func_70071_h_(BaseProjectileEntity.java:121)
	at com.lycanitesmobs.core.entity.CustomProjectileEntity.func_70071_h_(CustomProjectileEntity.java:168)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: lycanitesmobs:tricksterflare (com.lycanitesmobs.core.entity.CustomProjectileEntity)
	Entity ID: 289
	Entity Name: entity.lycanitesmobs:tricksterflare.name
	Entity's Exact location: 335.28, 47.84, 448.59
	Entity's Block location: World: (335,47,448), Chunk: (at 15,2,0 in 20,28; contains blocks 320,0,448 to 335,255,463), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.00, -0.26, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: HardCore
	All players: 1 total; [EntityPlayerMP['IanIury13'/363, l='HardCore', x=326.31, y=64.00, z=348.37]]
	Chunk stats: ServerChunkCache: 641 Drop: 0
	Level seed: 418170913
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (204,64,256), Chunk: (at 12,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 47168 game time, 47168 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 50586 (now: false), thunder time: 107881 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1031958504 bytes (984 MB) / 2348285952 bytes (2239 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version                | Source                                        | Signature                                |
	|:------ |:---------------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2                 | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                    | 9.42                   | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                  | 14.23.5.2854           | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | aiimprovements         | 0.0.1.3                | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
	| LCHIJA | skillable              | beta-10                | Skillable-beta-10.jar                         | None                                     |
	| LCHIJA | autoreglib             | 1.3-32                 | AutoRegLib-1.3-32.jar                         | None                                     |
	| LCHIJA | baubles                | 1.5.2                  | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | jei                    | 4.16.1.301             | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | cqrepoured             | 2.3.0B                 | Chocolate_Quest_Repoured-1.12.2-2.3.0B.jar    | None                                     |
	| LCHIJA | mantle                 | 1.12-1.3.3.55          | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | ctm                    | MC1.12.2-1.0.2.31      | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LCHIJA | twilightforest         | 3.11.1021              | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tconstruct             | 1.12.2-2.13.0.183      | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | conarm                 | 1.2.5.10               | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | epicfight              | 1.12.2.0               | EpicFightMod-1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | mod_lavacow            | 1.2.3                  | Fish's Undead Rising-1.2.3.jar                | None                                     |
	| LCHIJA | llibrary               | 1.7.20                 | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire             | 1.9.1                  | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LCHIJA | journeymap             | 1.12.2-5.7.1           | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | jeresources            | 0.9.2.60               | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHIJA | lycanitesmobs          | 2.0.7.2 - MC 1.12.2    | lycanitesmobs-1.12.2-2.0.7.2.jar              | None                                     |
	| LCHIJA | mowziesmobs            | 1.5.8                  | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJA | mutantbeasts           | 1.12.2-1.0.2           | MutantBeasts-1.12.2-1.0.2.jar                 | None                                     |
	| LCHIJA | patchouli              | 1.0-23.6               | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCHIJA | silentlib              | 3.0.13                 | SilentLib-1.12.2-3.0.14+168.jar               | None                                     |
	| LCHIJA | scalinghealth          | 1.3.37                 | ScalingHealth-1.12.2-1.3.42+147.jar           | None                                     |
	| LCHIJA | scp                    | 2.3.1                  | SCP Lockdown-1.12.2-2.3.1-dev.jar             | None                                     |
	| LCHIJA | srparasites            | 1.8.2                  | SRParasites-1.12.2v1.8.2.jar                  | None                                     |
	| LCHIJA | toughasnails           | 3.1.0.139              | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
	| LCHIJA | vampirism              | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                    | None                                     |
	| LCHIJA | teamlapen-lib          | 1.6.2                  | Vampirism-1.12.2-1.6.2.jar                    | None                                     |
	| LCHIJA | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.3.0.jar        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (Skillable-beta-10.jar)
  vazkii.skillable.base.asm.ClassTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['IanIury13'/363, l='HardCore', x=326.31, y=64.00, z=348.37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.2.2 27.20.14535.1000
	OpenGlRenderer: Radeon RX550/550 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Yesssssman** [comment]
The 1.12.2 version is outdated now, please wait until I update the whole code.
