### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Scornage** [Yesssssman/epicfightmod#80]
Sorry if I did something wrong.

Time: 3/16/21 6:22 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:58) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:72) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:44) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:29) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:22) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:76) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1504_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2604/595572116.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$26530/729722260.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$25622/1493712201.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$25017/549942867.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.initAttributes(ZombieData.java:58) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.LivingData.onEntityJoinWorld(LivingData.java:72) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.MobData.onEntityJoinWorld(MobData.java:44) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:29) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.capabilities.entity.mob.ZombieData.onEntityJoinWorld(ZombieData.java:22) ~[?:1.0] {re:classloading}
	at maninhouse.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:76) ~[?:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1504_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2604/595572116.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.world.server.ServerWorld.func_72838_d(ServerWorld.java:813) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217376_c(ServerWorld.java:754) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}
	at net.minecraft.world.IServerWorld$$Lambda$26530/729722260.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.IServerWorld.func_242417_l(SourceFile:11) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:178) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$25622/1493712201.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:ServerWorldMixin,pl:mixin:APP:charm.mixins.json:accessor.ServerWorldAccessor,pl:mixin:A}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5359396200 bytes (5111 MB) / 14797504512 bytes (14112 MB) up to 25769803776 bytes (24576 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.58.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.58.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.58.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.58.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G7.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.58.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.58
	FML Language Providers: 
		javafml@36.0
		minecraft@1

**Comment by Yesssssman** [comment]
Have you installed another mods? I'm sure about this, but It would happend when you installed 1.16.4 version mod that using incompatible function.

**Comment by LyricaPrismriver** [comment]
Is that a dungeon mod spawner problem? I had same problem like this.
[https://pastebin.com/xiZ8Q37S](url)

**Comment by Baenjamin** [comment]
I think it perhaps has to do something with the mod '[Dungeons Mobs](https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs)' by the_infamous_1, but only when certain mobs from that mod spawns naturally it seems. I think that mod has also been let off due to creators personal issues. Imma see if the same crash happens without the mod on my private pack with 195 mods installed B)
