### ISSUE TITLE
I can not run the game moded epicfight and XaerosWorldMap+Minimap!!!

### ISSUE THREAD

**Issue by DurianGIT** [Yesssssman/epicfightmod#834]
TITLE:I can not run the game moded epicfight and XaerosWorldMap+Minimap!!!
Error report:
Command: "C:\\Program Files\\Microsoft\\jdk-17.0.1.12-hotspot\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.17.1\1.17.1.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx4082m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -Dlog4j2.formatMsgNoLookups=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=D:\Desktop\momod\.minecraft\versions\1.17.1\natives-windows-x86_64 -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.4.211 -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-,1.17.1.jar,1.17.1.jar -DmergeModules=jna-5.8.0.jar,jna-platform-58.0.jar,java-objc-bridge-1.0.0.jar -DlibraryDirectory=D:\Desktop\momod\.minecraft\libraries -p D:\Desktop\momod\.minecraft\libraries/cpw/mods/bootstraplauncher/0.1.17/bootstraplauncher-0.1.17.jar;D:\Desktop\momod\.minecraft\libraries/cpw/mods/securejarhandler/0.9.54/securejarhandler-0.9.54.jar;D:\Desktop\momod\.minecraft\libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar;D:\Desktop\momod\.minecraft\libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar;D:\Desktop\momod\.minecraft\libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar;D:\Desktop\momod\.minecraft\libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar;D:\Desktop\momod\.minecraft\libraries/org/ow2/asm/asm/9.1/asm-9.1.jar --add-modules ALL-MODULE-PATH --add-opens java.base/java.util.jar=cpw.mods.securejarhandler --add-exports java.base/sun.security.util=cpw.mods.securejarhandler --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming cpw.mods.bootstraplauncher.BootstrapLauncher --username Durian --version 1.17.1 --gameDir D:\Desktop\momod\.minecraft --assetsDir D:\Desktop\momod\.minecraft\assets --assetIndex 1.17 --uuid 14aaa1bca9663d80b45ff27c5fe0779b --accessToken 0f14a8f68b7c4c6db1e933958bbfcaf5 --userType mojang --versionType "HMCL 3.4.211" --width 854 --height 480 --launchTarget forgeclient --fml.forgeVersion 37.0.112 --fml.mcVersion 1.17.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210706.113038
ClassPath: D:\Desktop\momod\.minecraft\libraries\cpw\mods\securejarhandler\0.9.54\securejarhandler-0.9.54.jar;D:\Desktop\momod\.minecraft\libraries\org\ow2\asm\asm\9.1\asm-9.1.jar;D:\Desktop\momod\.minecraft\libraries\org\ow2\asm\asm-commons\9.1\asm-commons-9.1.jar;D:\Desktop\momod\.minecraft\libraries\org\ow2\asm\asm-tree\9.1\asm-tree-9.1.jar;D:\Desktop\momod\.minecraft\libraries\org\ow2\asm\asm-util\9.1\asm-util-9.1.jar;D:\Desktop\momod\.minecraft\libraries\org\ow2\asm\asm-analysis\9.1\asm-analysis-9.1.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\accesstransformers\8.0.4\accesstransformers-8.0.4.jar;D:\Desktop\momod\.minecraft\libraries\org\antlr\antlr4-runtime\4.9.1\antlr4-runtime-4.9.1.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\eventbus\5.0.3\eventbus-5.0.3.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\forgespi\4.0.10\forgespi-4.0.10.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\coremods\5.0.1\coremods-5.0.1.jar;D:\Desktop\momod\.minecraft\libraries\cpw\mods\modlauncher\9.0.7\modlauncher-9.0.7.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\unsafe\0.2.0\unsafe-0.2.0.jar;D:\Desktop\momod\.minecraft\libraries\com\electronwill\night-config\core\3.6.3\core-3.6.3.jar;D:\Desktop\momod\.minecraft\libraries\com\electronwill\night-config\toml\3.6.3\toml-3.6.3.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;D:\Desktop\momod\.minecraft\libraries\net\jodah\typetools\0.8.3\typetools-0.8.3.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.14.1\log4j-api-2.14.1.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.14.1\log4j-core-2.14.1.jar;D:\Desktop\momod\.minecraft\libraries\net\minecrell\terminalconsoleappender\1.2.0\terminalconsoleappender-1.2.0.jar;D:\Desktop\momod\.minecraft\libraries\org\jline\jline-reader\3.12.1\jline-reader-3.12.1.jar;D:\Desktop\momod\.minecraft\libraries\org\jline\jline-terminal\3.12.1\jline-terminal-3.12.1.jar;D:\Desktop\momod\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;D:\Desktop\momod\.minecraft\libraries\org\spongepowered\mixin\0.8.4\mixin-0.8.4.jar;D:\Desktop\momod\.minecraft\libraries\org\openjdk\nashorn\nashorn-core\15.3\nashorn-core-15.3.jar;D:\Desktop\momod\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;D:\Desktop\momod\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;D:\Desktop\momod\.minecraft\libraries\cpw\mods\bootstraplauncher\0.1.17\bootstraplauncher-0.1.17.jar;D:\Desktop\momod\.minecraft\libraries\net\minecraftforge\fmlloader\1.17.1-37.0.112\fmlloader-1.17.1-37.0.112.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\blocklist\1.0.5\blocklist-1.0.5.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\patchy\2.1.6\patchy-2.1.6.jar;D:\Desktop\momod\.minecraft\libraries\com\github\oshi\oshi-core\5.7.5\oshi-core-5.7.5.jar;D:\Desktop\momod\.minecraft\libraries\net\java\dev\jna\jna\5.8.0\jna-5.8.0.jar;D:\Desktop\momod\.minecraft\libraries\net\java\dev\jna\jna-platform\5.8.0\jna-platform-5.8.0.jar;D:\Desktop\momod\.minecraft\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.14.1\log4j-slf4j18-impl-2.14.1.jar;D:\Desktop\momod\.minecraft\libraries\com\ibm\icu\icu4j\66.1\icu4j-66.1.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\javabridge\1.1.23\javabridge-1.1.23.jar;D:\Desktop\momod\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;D:\Desktop\momod\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;D:\Desktop\momod\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;D:\Desktop\momod\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;D:\Desktop\momod\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\datafixerupper\4.0.26\datafixerupper-4.0.26.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\authlib\2.3.31\authlib-2.3.31.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;D:\Desktop\momod\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;D:\Desktop\momod\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;D:\Desktop\momod\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;D:\Desktop\momod\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;D:\Desktop\momod\.minecraft\versions\1.17.1\1.17.1.jar
2021-12-11 23:47:36,130 main WARN Advanced terminal features are not available in this environment
[23:47:36] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Durian, --version, 1.17.1, --gameDir, D:\Desktop\momod\.minecraft, --assetsDir, D:\Desktop\momod\.minecraft\assets, --assetIndex, 1.17, --uuid, 14aaa1bca9663d80b45ff27c5fe0779b, --accessToken, ????????, --userType, mojang, --versionType, HMCL 3.4.211, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 37.0.112, --fml.mcVersion, 1.17.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210706.113038]
[23:47:36] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft
[23:47:36] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[23:47:36] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/D:/Desktop/momod/.minecraft/mods/OptiFine_1.17.1_HD_U_H1%20(1).jar%2353!
[23:47:36] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: D:\Desktop\momod\.minecraft\mods\OptiFine_1.17.1_HD_U_H1 (1).jar
[23:47:36] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[23:47:36] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=union:/D:/Desktop/momod/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar%2318! Service=ModLauncher Env=CLIENT
[23:47:36] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[23:47:38] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[23:47:38] [main/INFO] [op.OptiFineTransformer/]: Targets: 336
[23:47:39] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
Exception in thread "main" java.lang.module.ResolutionException: Modules xaerobetterpvp and xaerominimap export package xaero.common.category.ui.data.options.range to module ceilingtorch
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

**Comment by Yesssssman** [comment]
Do you have another crash report?
