### ISSUE TITLE
Server won't let me respawn with the mod (Epic Fight Mod 16.5.3)

### ISSUE THREAD

**Issue by Megas02** [Yesssssman/epicfightmod#879]
Im using the last version of this Epic Fight Mod but i'm having this error: Epic Fight Mod 16.5.3

[19:29:08 FATAL]: Error executing task on Server
[19:29:08 WARN]: java.lang.IllegalArgumentException: Duplicate id value for 252!
[19:29:08 WARN]:        at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:86)
[19:29:08 WARN]:        at yesman.epicfight.capabilities.entity.LivingData.onEntityConstructed(LivingData.java:78)
[19:29:08 WARN]:        at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:51)
[19:29:08 WARN]:        at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:38)
[19:29:08 WARN]:        at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:35)
[19:29:08 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler_160_CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic)
[19:29:08 WARN]:        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[19:29:08 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[19:29:08 WARN]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[19:29:08 WARN]:        at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:601)
[19:29:08 WARN]:        at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:595)
[19:29:08 WARN]:        at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:90)
[19:29:08 WARN]:        at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:85)
[19:29:08 WARN]:        at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:64)
[19:29:08 WARN]:        at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapsAndRevive(CapabilityProvider.java:68)
[19:29:08 WARN]:        at net.minecraft.server.management.PlayerList.respawn(PlayerList.java:563)
[19:29:08 WARN]:        at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:535)
[19:29:08 WARN]:        at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2064)
[19:29:08 WARN]:        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
[19:29:08 WARN]:        at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
[19:29:08 WARN]:        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[19:29:08 WARN]:        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[19:29:08 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[19:29:08 WARN]:        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
[19:29:08 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
[19:29:08 WARN]:        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
[19:29:08 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[19:29:08 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
