### ISSUE TITLE
Hybrid server goes into the end and crashes

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#970]
[11:01:36 ERROR]: Exception caught during firing event: Index 11 out of bounds for length 11
        Index: 6
        Listeners:
                0: HIGH
                1: ASM: net.minecraftforge.common.ForgeInternalHandler@57d1ad4d onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                2: NORMAL
                3: ASM: class noobanidus.mods.lootr.event.HandleCart onEntityJoin(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                4: ASM: class com.calculusmaster.difficultraids.events.DRForgeModEvents addSpawn(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                5: ASM: class com.baguchan.enchantwithmob.mobenchant.MultiShotMobEnchant onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                6: ASM: class yesman.epicfight.events.EntityEvents spawnEvent(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
                7: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@3e264c1 entityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinWorldEvent;)V
java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
        at TRANSFORMER/arclight@1.18.2-1.0.3-c609b197/org.bukkit.craftbukkit.v1_18_R2.entity.CraftEnderDragon.getBukkitPhase(CraftEnderDragon.java:61)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhaseManager.m_31416_(EnderDragonPhaseManagerMixin.java:541)
        at TRANSFORMER/epicfight@18.1.6/yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.PhaseManagerPatch.m_31416_(PhaseManagerPatch.java:34)
        at TRANSFORMER/epicfight@18.1.6/yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:75)
        at TRANSFORMER/epicfight@18.1.6/yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:45)
        at TRANSFORMER/epicfight@18.1.6/yesman.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:77)
        at net.minecraftforge.eventbus.ASMEventHandler_174_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManagerMixin.java:80)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157533_(PersistentEntitySectionManagerMixin.java:72)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8872_(ServerLevelMixin.java:846)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_7967_(ServerLevelMixin.java:754)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.dimension.end.EndDragonFight.m_64110_(EndDragonFight.java:407)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.dimension.end.EndDragonFight.m_64103_(EndDragonFight.java:234)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.dimension.end.EndDragonFight.m_64095_(EndDragonFight.java:180)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:295)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:902)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)

[11:01:36 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:906) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEnderDragon.getBukkitPhase(CraftEnderDragon.java:61) ~[arclight-1.18.2-1.0.3-c609b197.jar%2368!/:arclight-1.18.2-1.0.3-c609b197]
        at net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhaseManager.m_31416_(EnderDragonPhaseManagerMixin.java:541) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.PhaseManagerPatch.m_31416_(PhaseManagerPatch.java:34) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:75) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:45) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:77) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler_174_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManagerMixin.java:80) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157533_(PersistentEntitySectionManagerMixin.java:72) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_8872_(ServerLevelMixin.java:846) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_7967_(ServerLevelMixin.java:754) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64110_(EndDragonFight.java:407) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64103_(EndDragonFight.java:234) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64095_(EndDragonFight.java:180) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:295) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        ... 5 more
[11:01:36 ERROR]:       Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 11
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEnderDragon.getBukkitPhase(CraftEnderDragon.java:61) ~[arclight-1.18.2-1.0.3-c609b197.jar%2368!/:arclight-1.18.2-1.0.3-c609b197]
        at net.minecraft.world.entity.boss.enderdragon.phases.EnderDragonPhaseManager.m_31416_(EnderDragonPhaseManagerMixin.java:541) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.PhaseManagerPatch.m_31416_(PhaseManagerPatch.java:34) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:75) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.EnderDragonPatch.onJoinWorld(EnderDragonPatch.java:45) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at yesman.epicfight.events.EntityEvents.spawnEvent(EntityEvents.java:77) ~[【冒险】%5B史诗战斗%5D%20EpicFight-18.1.6-beta.jar%2374!/:?]
        at net.minecraftforge.eventbus.ASMEventHandler_174_EntityEvents_spawnEvent_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%234!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157538_(PersistentEntitySectionManagerMixin.java:80) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157533_(PersistentEntitySectionManagerMixin.java:72) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_8872_(ServerLevelMixin.java:846) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_7967_(ServerLevelMixin.java:754) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64110_(EndDragonFight.java:407) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64103_(EndDragonFight.java:234) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.world.level.dimension.end.EndDragonFight.m_64095_(EndDragonFight.java:180) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevelMixin.java:295) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2135) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23103!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[11:01:36 FATAL]: Preparing crash report with UUID e0b27724-279e-43f0-a17d-005a988c0636
[11:01:36 ERROR]: This crash report has been saved to: D:\UserData\Desktop\史诗战斗boss更新服务端\螺端\.\crash-reports\crash-2022-05-02_11.01.36-server.txt

**Comment by Yesssssman** [comment]
This crash is unfixable unless modifying the bukkit code... sorry
