### ISSUE TITLE
Crash randomly editing auto switch items list

### ISSUE THREAD

**Issue by Zano1999** [Yesssssman/epicfightmod#994]
java.lang.NullPointerException: Cannot read field "f_19853_" because "player" is null
	at net.blay09.mods.waystones.core.PlayerWaystoneManager.getWarpStoneCooldownUntil(PlayerWaystoneManager.java:507) ~[waystones-forge-1.18.2-10.0.0.jar%23202!/:10.0.0] {re:classloading}
	at net.blay09.mods.waystones.core.PlayerWaystoneManager.getWarpStoneCooldownLeft(PlayerWaystoneManager.java:511) ~[waystones-forge-1.18.2-10.0.0.jar%23202!/:10.0.0] {re:classloading}
	at net.blay09.mods.waystones.core.PlayerWaystoneManager.canUseWarpStone(PlayerWaystoneManager.java:200) ~[waystones-forge-1.18.2-10.0.0.jar%23202!/:10.0.0] {re:classloading}
	at net.blay09.mods.waystones.item.WarpStoneItem.m_5812_(WarpStoneItem.java:131) ~[waystones-forge-1.18.2-10.0.0.jar%23202!/:10.0.0] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41790_(ItemStack.java:823) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:biomemakeover-common.mixins.json:enchantment.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:219) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:eatinganimation.mixins.json:ItemRendererMixin,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:446) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:eatinganimation.mixins.json:ItemRendererMixin,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115123_(ItemRenderer.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:eatinganimation.mixins.json:ItemRendererMixin,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:A}
	at yesman.epicfight.client.gui.screen.EditItemListScreen$ItemButton.m_6305_(EditItemListScreen.java:360) ~[EpicFight-18.1.13-beta.jar%23119!/:18.1.13] {re:classloading}
	at yesman.epicfight.client.gui.screen.EditItemListScreen$ButtonList$ButtonEntry.m_6311_(EditItemListScreen.java:303) ~[EpicFight-18.1.13-beta.jar%23119!/:18.1.13] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_93451_(AbstractSelectionList.java:466) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:configured:set_background_texture_1,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:configured:set_background_texture_1,pl:mixin:APP:flytre_lib.mixins.json:config.EntryListWidgetAccessor,pl:mixin:APP:flytre_lib.mixins.json:gui.EntryListWidgetAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.gui.screen.EditItemListScreen$ButtonList.m_6305_(EditItemListScreen.java:214) ~[EpicFight-18.1.13-beta.jar%23119!/:18.1.13] {re:classloading}
	at yesman.epicfight.client.gui.screen.EditItemListScreen.m_6305_(EditItemListScreen.java:72) ~[EpicFight-18.1.13-beta.jar%23119!/:18.1.13] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:385) ~[forge-1.18.2-40.1.16-universal.jar%23221!/:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:378) ~[forge-1.18.2-40.1.16-universal.jar%23221!/:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor47.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:685) ~[OptiFine_1.18.2_HD_U_H6.jar%23222!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1278) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:biomemakeover-common.mixins.json:multipart.client.GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:lod.mixins.json:fabric.mixin.networking.accessor.MinecraftClientAccessor,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftClientMixin,pl:mixin:APP:spyglass_improvements.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23217!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.16.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

**Comment by MetalKnight56** [comment]
Just got this crash on latest version [18.1.13] Forge ver: 40.1.0,
[latest.log](https://github.com/Yesssssman/epicfightmod/files/8655733/latest.log)

**Comment by Yesssssman** [comment]
Fixed in 18.1.15
